#!/usr/bin/env python3
"""Writes the HLSL vector types and the intrinsics of Csl.Types (Csl.Hlsl namespace).

Run from CSharpShaders/: python3 tools/gen_hlsl_types.py. The output is committed; the script is
the source of truth for anything repetitive (swizzles, operators, intrinsic overloads)."""
import itertools, os, textwrap

OUT = os.path.join(os.path.dirname(__file__), '..', 'Csl.Types', 'Hlsl')
SCALARS = {
    'float': dict(zero='0f', one='1f', cs='float', lit=lambda v: f'{v}f', math=True, integer=False, boolean=False),
    'int':   dict(zero='0', one='1', cs='int', lit=lambda v: str(v), math=False, integer=True, boolean=False),
    'uint':  dict(zero='0u', one='1u', cs='uint', lit=lambda v: f'{v}u', math=False, integer=True, boolean=False),
    'bool':  dict(zero='false', one='true', cs='bool', lit=None, math=False, integer=False, boolean=True),
}
COMPONENTS = ['x', 'y', 'z', 'w']
COLORS = ['r', 'g', 'b', 'a']
HEADER = '''// <auto-generated>
// Written by tools/gen_hlsl_types.py. Do not edit; edit the script and run it again.
// </auto-generated>
#nullable enable
#pragma warning disable IDE1006, CS1591
using System;
using System.Runtime.InteropServices;

namespace Csl.Hlsl;
'''

def vec(scalar, n): return f'{scalar}{n}'

def emit_vector(scalar, n):
    s = SCALARS[scalar]
    one = s['one']
    name = vec(scalar, n)
    comps = COMPONENTS[:n]
    out = [HEADER, f'/// <summary>HLSL {name}: {n} components of {scalar}. Runs on the GPU; the C# operations exist so shader code type-checks and can be unit tested.</summary>',
           '[StructLayout(LayoutKind.Sequential)]', f'public struct {name} : IEquatable<{name}>', '{']
    out.append(f'    public {scalar} ' + ', '.join(comps) + ';')
    # constructors
    out.append(f'    public {name}({", ".join(f"{scalar} {c}" for c in comps)}) {{ {" ".join(f"this.{c} = {c};" for c in comps)} }}')
    out.append(f'    public {name}({scalar} v) {{ {" ".join(f"{c} = v;" for c in comps)} }}')
    # mixed constructors from smaller vectors
    if n == 3:
        out.append(f'    public {name}({scalar}2 xy, {scalar} z) {{ x = xy.x; y = xy.y; this.z = z; }}')
        out.append(f'    public {name}({scalar} x, {scalar}2 yz) {{ this.x = x; y = yz.x; z = yz.y; }}')
    if n == 4:
        out.append(f'    public {name}({scalar}3 xyz, {scalar} w) {{ x = xyz.x; y = xyz.y; z = xyz.z; this.w = w; }}')
        out.append(f'    public {name}({scalar} x, {scalar}3 yzw) {{ this.x = x; y = yzw.x; z = yzw.y; w = yzw.z; }}')
        out.append(f'    public {name}({scalar}2 xy, {scalar}2 zw) {{ x = xy.x; y = xy.y; z = zw.x; w = zw.y; }}')
        out.append(f'    public {name}({scalar}2 xy, {scalar} z, {scalar} w) {{ x = xy.x; y = xy.y; this.z = z; this.w = w; }}')
    # conversions from other scalar vectors of the same size
    for other in SCALARS:
        if other == scalar or SCALARS[other]['boolean'] or s['boolean']:
            continue
        oname = vec(other, n)
        out.append(f'    public {name}({oname} v) {{ {" ".join(f"{c} = ({scalar})v.{c};" for c in comps)} }}')
        # HLSL converts freely between same-size vectors; C# keeps narrowing explicit.
        widening = (other in ('int', 'uint') and scalar == 'float') or (other == 'int' and scalar == 'uint' and False)
        kind = 'implicit' if widening else 'explicit'
        out.append(f'    public static {kind} operator {name}({oname} v) => new {name}(v);')
    out.append(f'    public static implicit operator {name}({scalar} v) => new {name}(v);')
    # indexer
    out.append(f'    public {scalar} this[int i]')
    out.append('    {')
    out.append('        get => i switch { ' + ', '.join(f'{i} => {c}' for i, c in enumerate(comps)) + ', _ => throw new IndexOutOfRangeException() };')
    out.append('        set { switch (i) { ' + ' '.join(f'case {i}: {c} = value; break;' for i, c in enumerate(comps)) + ' default: throw new IndexOutOfRangeException(); } }')
    out.append('    }')
    # arithmetic
    if not s['boolean']:
        for op in ['+', '-', '*', '/', '%']:
            out.append(f'    public static {name} operator {op}({name} a, {name} b) => new {name}({", ".join(f"({scalar})(a.{c} {op} b.{c})" for c in comps)});')
            out.append(f'    public static {name} operator {op}({name} a, {scalar} b) => new {name}({", ".join(f"({scalar})(a.{c} {op} b)" for c in comps)});')
            out.append(f'    public static {name} operator {op}({scalar} a, {name} b) => new {name}({", ".join(f"({scalar})(a {op} b.{c})" for c in comps)});')
        if scalar != 'uint':
            out.append(f'    public static {name} operator -({name} a) => new {name}({", ".join(f"({scalar})(-a.{c})" for c in comps)});')
        out.append(f'    public static {name} operator +({name} a) => a;')
        out.append(f'    public static {name} operator ++({name} a) => new {name}({", ".join(f"({scalar})(a.{c} + {one})" for c in comps)});')
        out.append(f'    public static {name} operator --({name} a) => new {name}({", ".join(f"({scalar})(a.{c} - {one})" for c in comps)});')
        for op in ['<', '>', '<=', '>=']:
            out.append(f'    public static bool{n} operator {op}({name} a, {name} b) => new bool{n}({", ".join(f"a.{c} {op} b.{c}" for c in comps)});')
            out.append(f'    public static bool{n} operator {op}({name} a, {scalar} b) => new bool{n}({", ".join(f"a.{c} {op} b" for c in comps)});')
            out.append(f'    public static bool{n} operator {op}({scalar} a, {name} b) => new bool{n}({", ".join(f"a {op} b.{c}" for c in comps)});')
    if s['integer']:
        for op in ['&', '|', '^']:
            out.append(f'    public static {name} operator {op}({name} a, {name} b) => new {name}({", ".join(f"({scalar})(a.{c} {op} b.{c})" for c in comps)});')
            out.append(f'    public static {name} operator {op}({name} a, {scalar} b) => new {name}({", ".join(f"({scalar})(a.{c} {op} b)" for c in comps)});')
        for op in ['<<', '>>']:
            out.append(f'    public static {name} operator {op}({name} a, int b) => new {name}({", ".join(f"({scalar})(a.{c} {op} b)" for c in comps)});')
        out.append(f'    public static {name} operator ~({name} a) => new {name}({", ".join(f"({scalar})(~a.{c})" for c in comps)});')
    if s['boolean']:
        for op in ['&', '|', '^']:
            out.append(f'    public static {name} operator {op}({name} a, {name} b) => new {name}({", ".join(f"a.{c} {op} b.{c}" for c in comps)});')
        out.append(f'    public static {name} operator !({name} a) => new {name}({", ".join(f"!a.{c}" for c in comps)});')
    # equality, component-wise like HLSL
    out.append(f'    public static bool{n} operator ==({name} a, {name} b) => new bool{n}({", ".join(f"a.{c} == b.{c}" for c in comps)});')
    out.append(f'    public static bool{n} operator !=({name} a, {name} b) => new bool{n}({", ".join(f"a.{c} != b.{c}" for c in comps)});')
    out.append(f'    public static bool{n} operator ==({name} a, {scalar} b) => new bool{n}({", ".join(f"a.{c} == b" for c in comps)});')
    out.append(f'    public static bool{n} operator !=({name} a, {scalar} b) => new bool{n}({", ".join(f"a.{c} != b" for c in comps)});')
    out.append(f'    public bool Equals({name} other) => {" && ".join(f"{c} == other.{c}" for c in comps)};')
    out.append(f'    public override bool Equals(object? obj) => obj is {name} other && Equals(other);')
    out.append(f'    public override int GetHashCode() => HashCode.Combine({", ".join(comps)});')
    out.append(f'    public override string ToString() => $"{name}({", ".join("{" + c + "}" for c in comps)})";')
    # swizzles
    out.append('')
    out.append('    // Swizzles, xyzw and rgba. Setters only where no component repeats.')
    for names in (COMPONENTS[:n], COLORS[:n]):
        mapping = dict(zip(names, comps))
        if names == COLORS[:n]:
            for a, c in zip(names, comps):
                out.append(f'    public {scalar} {a} {{ get => {c}; set => {c} = value; }}')
        for length in (2, 3, 4):
            for combo in itertools.product(names, repeat=length):
                sw = ''.join(combo)
                fields = [mapping[k] for k in combo]
                ctor = f'new {scalar}{length}({", ".join(fields)})'
                if len(set(combo)) == length:
                    setter = ' '.join(f'{f} = value.{COMPONENTS[i]};' for i, f in enumerate(fields))
                    out.append(f'    public {scalar}{length} {sw} {{ get => {ctor}; set {{ {setter} }} }}')
                else:
                    out.append(f'    public {scalar}{length} {sw} => {ctor};')
    out.append('}')
    return '\n'.join(out) + '\n'

def emit_intrinsics():
    out = [HEADER.replace('namespace Csl.Hlsl;', 'namespace Csl.Hlsl;\n\n/// <summary>HLSL intrinsic functions. <c>using static Csl.Hlsl.Intrinsics;</c> in a shader file, then write them as in HLSL.</summary>\npublic static partial class Intrinsics\n{')]
    def comp(fn, scalar, n, args):
        # apply fn component-wise: args are names of vector params
        if n == 1:
            return fn(*[f'{a}' for a in args])
        parts = [fn(*[f'{a}.{c}' for a in args]) for c in COMPONENTS[:n]]
        return f'new {scalar}{n}({", ".join(parts)})'
    def t(scalar, n): return scalar if n == 1 else f'{scalar}{n}'
    unary_float = {
        'abs': lambda a: f'MathF.Abs({a})', 'floor': lambda a: f'MathF.Floor({a})', 'ceil': lambda a: f'MathF.Ceiling({a})',
        'round': lambda a: f'MathF.Round({a}, MidpointRounding.AwayFromZero)', 'trunc': lambda a: f'MathF.Truncate({a})',
        'frac': lambda a: f'({a} - MathF.Floor({a}))', 'sqrt': lambda a: f'MathF.Sqrt({a})', 'rsqrt': lambda a: f'(1f / MathF.Sqrt({a}))',
        'exp': lambda a: f'MathF.Exp({a})', 'exp2': lambda a: f'MathF.Pow(2f, {a})', 'log': lambda a: f'MathF.Log({a})', 'log2': lambda a: f'MathF.Log2({a})',
        'log10': lambda a: f'MathF.Log10({a})', 'sin': lambda a: f'MathF.Sin({a})', 'cos': lambda a: f'MathF.Cos({a})', 'tan': lambda a: f'MathF.Tan({a})',
        'asin': lambda a: f'MathF.Asin({a})', 'acos': lambda a: f'MathF.Acos({a})', 'atan': lambda a: f'MathF.Atan({a})',
        'saturate': lambda a: f'Math.Clamp({a}, 0f, 1f)', 'sign': lambda a: f'(float)MathF.Sign({a})', 'rcp': lambda a: f'(1f / {a})',
        'radians': lambda a: f'({a} * (MathF.PI / 180f))', 'degrees': lambda a: f'({a} * (180f / MathF.PI))',
    }
    for fn, body in unary_float.items():
        for n in (1, 2, 3, 4):
            out.append(f'    public static {t("float", n)} {fn}({t("float", n)} v) => {comp(body, "float", n, ["v"])};')
    for fn, body in {'abs': lambda a: f'Math.Abs({a})', 'sign': lambda a: f'Math.Sign({a})'}.items():
        for n in (1, 2, 3, 4):
            out.append(f'    public static {t("int", n)} {fn}({t("int", n)} v) => {comp(body, "int", n, ["v"])};')
    binary_float = {
        'pow': lambda a, b: f'MathF.Pow({a}, {b})', 'atan2': lambda a, b: f'MathF.Atan2({a}, {b})', 'fmod': lambda a, b: f'({a} % {b})',
        'step': lambda a, b: f'({b} >= {a} ? 1f : 0f)', 'ldexp': lambda a, b: f'({a} * MathF.Pow(2f, {b}))',
    }
    for fn, body in binary_float.items():
        for n in (1, 2, 3, 4):
            out.append(f'    public static {t("float", n)} {fn}({t("float", n)} a, {t("float", n)} b) => {comp(body, "float", n, ["a", "b"])};')
    for scalar, mn, mx in (('float', 'MathF.Min', 'MathF.Max'), ('int', 'Math.Min', 'Math.Max'), ('uint', 'Math.Min', 'Math.Max')):
        for n in (1, 2, 3, 4):
            out.append(f'    public static {t(scalar, n)} min({t(scalar, n)} a, {t(scalar, n)} b) => {comp(lambda a, b: f"{mn}({a}, {b})", scalar, n, ["a", "b"])};')
            out.append(f'    public static {t(scalar, n)} max({t(scalar, n)} a, {t(scalar, n)} b) => {comp(lambda a, b: f"{mx}({a}, {b})", scalar, n, ["a", "b"])};')
            out.append(f'    public static {t(scalar, n)} clamp({t(scalar, n)} v, {t(scalar, n)} lo, {t(scalar, n)} hi) => {comp(lambda v, lo, hi: f"Math.Clamp({v}, {lo}, {hi})", scalar, n, ["v", "lo", "hi"])};')
    for n in (1, 2, 3, 4):
        out.append(f'    public static {t("float", n)} lerp({t("float", n)} a, {t("float", n)} b, {t("float", n)} s) => {comp(lambda a, b, s: f"({a} + ({b} - {a}) * {s})", "float", n, ["a", "b", "s"])};')
        if n > 1:
            out.append(f'    public static {t("float", n)} lerp({t("float", n)} a, {t("float", n)} b, float s) => {comp(lambda a, b: f"({a} + ({b} - {a}) * s)", "float", n, ["a", "b"])};')
        out.append(f'    public static {t("float", n)} smoothstep({t("float", n)} lo, {t("float", n)} hi, {t("float", n)} v) => {comp(lambda lo, hi, v: f"SmoothStep({lo}, {hi}, {v})", "float", n, ["lo", "hi", "v"])};')
        out.append(f'    public static {t("float", n)} mad({t("float", n)} a, {t("float", n)} b, {t("float", n)} c) => {comp(lambda a, b, c: f"({a} * {b} + {c})", "float", n, ["a", "b", "c"])};')
        out.append(f'    public static bool{"" if n == 1 else n} isnan({t("float", n)} v) => {comp(lambda a: f"float.IsNaN({a})", "bool", n, ["v"])};')
        out.append(f'    public static bool{"" if n == 1 else n} isinf({t("float", n)} v) => {comp(lambda a: f"float.IsInfinity({a})", "bool", n, ["v"])};')
    out.append('    private static float SmoothStep(float lo, float hi, float v) { var x = Math.Clamp((v - lo) / (hi - lo), 0f, 1f); return x * x * (3f - 2f * x); }')
    # vector-only
    for n in (2, 3, 4):
        comps = COMPONENTS[:n]
        out.append(f'    public static float dot(float{n} a, float{n} b) => {" + ".join(f"a.{c} * b.{c}" for c in comps)};')
        out.append(f'    public static int dot(int{n} a, int{n} b) => {" + ".join(f"a.{c} * b.{c}" for c in comps)};')
        out.append(f'    public static float length(float{n} v) => MathF.Sqrt(dot(v, v));')
        out.append(f'    public static float distance(float{n} a, float{n} b) => length(a - b);')
        out.append(f'    public static float{n} normalize(float{n} v) => v / length(v);')
        for scalar in ('float', 'int', 'uint'):
            out.append(f'    public static bool any({scalar}{n} v) => {" || ".join(f"v.{c} != 0" for c in comps)};')
            out.append(f'    public static bool all({scalar}{n} v) => {" && ".join(f"v.{c} != 0" for c in comps)};')
        out.append(f'    public static bool any(bool{n} v) => {" || ".join(f"v.{c}" for c in comps)};')
        out.append(f'    public static bool all(bool{n} v) => {" && ".join(f"v.{c}" for c in comps)};')
    out.append('    public static bool any(bool v) => v;')
    out.append('    public static bool all(bool v) => v;')
    out.append('    public static bool any(float v) => v != 0;')
    out.append('    public static bool all(float v) => v != 0;')
    out.append('    public static bool any(int v) => v != 0;')
    out.append('    public static bool all(int v) => v != 0;')
    out.append('    public static bool any(uint v) => v != 0;')
    out.append('    public static bool all(uint v) => v != 0;')
    out.append('    public static float3 cross(float3 a, float3 b) => new float3(a.y * b.z - a.z * b.y, a.z * b.x - a.x * b.z, a.x * b.y - a.y * b.x);')
    out.append('    public static float asfloat(uint v) => BitConverter.Int32BitsToSingle((int)v);')
    out.append('    public static float asfloat(int v) => BitConverter.Int32BitsToSingle(v);')
    out.append('    public static uint asuint(float v) => (uint)BitConverter.SingleToInt32Bits(v);')
    out.append('    public static int asint(float v) => BitConverter.SingleToInt32Bits(v);')
    out.append('    public static int asint(uint v) => (int)v;')
    out.append('    public static uint asuint(int v) => (uint)v;')
    out.append('    public static uint countbits(uint v) => (uint)System.Numerics.BitOperations.PopCount(v);')
    out.append('    public static uint firstbitlow(uint v) => (uint)System.Numerics.BitOperations.TrailingZeroCount(v);')
    out.append('    public static uint firstbithigh(uint v) => v == 0 ? uint.MaxValue : (uint)(31 - System.Numerics.BitOperations.LeadingZeroCount(v));')
    out.append('    public static uint reversebits(uint v) { uint r = 0; for (int i = 0; i < 32; i++) { r = (r << 1) | (v & 1); v >>= 1; } return r; }')
    out.append('}')
    return '\n'.join(out) + '\n'

os.makedirs(OUT, exist_ok=True)
for scalar in SCALARS:
    for n in (2, 3, 4):
        with open(os.path.join(OUT, f'{vec(scalar, n)}.g.cs'), 'w') as f:
            f.write(emit_vector(scalar, n))
with open(os.path.join(OUT, 'Intrinsics.g.cs'), 'w') as f:
    f.write(emit_intrinsics())
print('written', OUT)
