// <auto-generated>
// Stub of the engine's ComputeShaderBase.sdsl (Stride.Rendering package, stride/Assets), written by Csl.Stubs. Do not edit; run the tool again.
// Nothing is generated from this class: it describes a shader that exists elsewhere, so C# shaders
// can inherit it. Method bodies are placeholders.
// </auto-generated>
#nullable enable
#pragma warning disable CS0649, CS8618, CS1591
using Csl.Hlsl;

namespace Csl.Engine;

/// <summary>
/// Base compute shader.
/// </summary>
/// <remarks>
/// ThreadNumberX: Macro - number of threads on the X axis.
/// ThreadNumberY: Macro - number of threads on the Y axis.
/// ThreadNumberZ: Macro - number of threads on the Z axis.
/// </remarks>
[Shader(External = true)]
public abstract partial class ComputeShaderBase
{
    [Stage, Stream("SV_GroupID")] public uint3 GroupId;
    [Stage, Stream("SV_DispatchThreadID")] public uint3 DispatchThreadId;
    [Stage, Stream("SV_GroupThreadID")] public uint3 GroupThreadId;
    [Stage, Stream("SV_GroupIndex")] public uint GroupIndex;
    [Stage, Stream] public uint3 ThreadGroupCount;
    [Stage, Stream] public uint ThreadCountPerGroup;
    [Stage, Stream] public uint ThreadGroupIndex;
    [Stage, Stream] public int ThreadCountX;
    [Stage, Stream] public int ThreadCountY;
    [Stage, Stream] public int ThreadCountZ;
    [Stage, Link("ComputeShaderBase.ThreadGroupCountGlobal")] public int3 ThreadGroupCountGlobal;

    public virtual void CSMain() { }

    public virtual void Compute() { }

    public virtual bool IsFirstThreadOfGroup() { return default; }
}
