using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Csl.Generators.CSharp;

/// <summary>
/// C# has one base class; SDSL has many. For every shader named in [Mixin], the members it brings
/// (its own and its bases') are declared again on the class as stubs, so the C# compiles and the
/// translator resolves them as shader members. A stub is not virtual: to override a method, make
/// its shader the C# base.
/// </summary>
public static class MixinStubEmitter
{
    private static readonly SymbolDisplayFormat TypeFormat = SymbolDisplayFormat.FullyQualifiedFormat
        .WithMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier | SymbolDisplayMiscellaneousOptions.UseSpecialTypes);

    public static string Emit(INamedTypeSymbol shader, List<INamedTypeSymbol> mixins, TranslatedShader result)
    {
        // Names the class already has, from itself and its C# bases: those are not stubbed.
        var taken = new HashSet<string>(System.StringComparer.Ordinal);
        for (var type = shader; type != null && type.SpecialType != SpecialType.System_Object; type = type.BaseType)
            foreach (var member in type.GetMembers())
                taken.Add(member.Name);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Generated by Csl.Generators: the members of the [Mixin] shaders, as stubs for the C# compiler.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS0649, CS8618, CS1591");
        if (result.Namespace != null)
        {
            sb.Append("namespace ").AppendLine(result.Namespace);
            sb.AppendLine("{");
        }
        var indent = result.Namespace != null ? "    " : string.Empty;
        sb.Append(indent).Append("partial class ").AppendLine(result.ClassName);
        sb.Append(indent).AppendLine("{");

        foreach (var mixin in mixins)
        {
            for (var type = mixin; type != null && type.SpecialType != SpecialType.System_Object; type = type.BaseType)
            {
                foreach (var member in type.GetMembers().OrderBy(m => m.Locations.FirstOrDefault()?.SourceSpan.Start ?? 0))
                {
                    if (member.IsImplicitlyDeclared || member.DeclaredAccessibility == Accessibility.Private || !taken.Add(member.Name))
                        continue;
                    switch (member)
                    {
                        case IFieldSymbol field when !field.IsConst:
                            foreach (var attribute in field.GetAttributes())
                            {
                                var name = attribute.AttributeClass?.ToDisplayString();
                                if (name == "Csl.StreamAttribute")
                                {
                                    var semantic = attribute.ConstructorArguments.Length > 0 && attribute.ConstructorArguments[0].Value is string s ? "(\"" + s + "\")" : string.Empty;
                                    sb.Append(indent).Append("    [global::Csl.Stream").Append(semantic).AppendLine("]");
                                }
                                else if (name == "Csl.StageAttribute")
                                    sb.Append(indent).AppendLine("    [global::Csl.Stage]");
                            }
                            sb.Append(indent).Append("    public ").Append(field.IsStatic ? "static " : string.Empty)
                              .Append(field.Type.ToDisplayString(TypeFormat)).Append(' ').Append(field.Name).AppendLine(";");
                            break;
                        case IFieldSymbol constant:
                            sb.Append(indent).Append("    public const ").Append(constant.Type.ToDisplayString(TypeFormat)).Append(' ').Append(constant.Name)
                              .Append(" = ").Append(Literal(constant.ConstantValue)).AppendLine(";");
                            break;
                        case IMethodSymbol { MethodKind: MethodKind.Ordinary } method:
                            sb.Append(indent).Append("    public ").Append(method.IsStatic ? "static " : string.Empty)
                              .Append(method.ReturnType.ToDisplayString(TypeFormat)).Append(' ').Append(method.Name).Append('(');
                            for (int i = 0; i < method.Parameters.Length; i++)
                            {
                                var parameter = method.Parameters[i];
                                if (i > 0) sb.Append(", ");
                                sb.Append(parameter.RefKind switch { RefKind.Ref => "ref ", RefKind.Out => "out ", RefKind.In => "in ", _ => string.Empty });
                                sb.Append(parameter.Type.ToDisplayString(TypeFormat)).Append(' ').Append(parameter.Name);
                            }
                            sb.AppendLine(") => throw new global::System.NotSupportedException(\"Shader code runs on the GPU\");");
                            break;
                    }
                }
            }
        }

        sb.Append(indent).AppendLine("}");
        if (result.Namespace != null)
            sb.AppendLine("}");
        return sb.ToString();
    }

    private static string Literal(object? value) => value switch
    {
        null => "default",
        bool b => b ? "true" : "false",
        float f => f.ToString("R", System.Globalization.CultureInfo.InvariantCulture) + "f",
        double d => d.ToString("R", System.Globalization.CultureInfo.InvariantCulture) + "d",
        uint u => u.ToString(System.Globalization.CultureInfo.InvariantCulture) + "u",
        string s => "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"",
        _ => System.Convert.ToString(value, System.Globalization.CultureInfo.InvariantCulture) ?? "default",
    };
}
