// <auto-generated>
// Written by tools/gen_hlsl_types.py. Do not edit; edit the script and run it again.
// </auto-generated>
#nullable enable
#pragma warning disable IDE1006, CS1591
using System;
using System.Runtime.InteropServices;

namespace Csl.Hlsl;

/// <summary>HLSL bool3: 3 components of bool. Runs on the GPU; the C# operations exist so shader code type-checks and can be unit tested.</summary>
[StructLayout(LayoutKind.Sequential)]
public struct bool3 : IEquatable<bool3>
{
    public bool x, y, z;
    public bool3(bool x, bool y, bool z) { this.x = x; this.y = y; this.z = z; }
    public bool3(bool v) { x = v; y = v; z = v; }
    public bool3(bool2 xy, bool z) { x = xy.x; y = xy.y; this.z = z; }
    public bool3(bool x, bool2 yz) { this.x = x; y = yz.x; z = yz.y; }
    public static implicit operator bool3(bool v) => new bool3(v);
    public bool this[int i]
    {
        get => i switch { 0 => x, 1 => y, 2 => z, _ => throw new IndexOutOfRangeException() };
        set { switch (i) { case 0: x = value; break; case 1: y = value; break; case 2: z = value; break; default: throw new IndexOutOfRangeException(); } }
    }
    public static bool3 operator &(bool3 a, bool3 b) => new bool3(a.x & b.x, a.y & b.y, a.z & b.z);
    public static bool3 operator |(bool3 a, bool3 b) => new bool3(a.x | b.x, a.y | b.y, a.z | b.z);
    public static bool3 operator ^(bool3 a, bool3 b) => new bool3(a.x ^ b.x, a.y ^ b.y, a.z ^ b.z);
    public static bool3 operator !(bool3 a) => new bool3(!a.x, !a.y, !a.z);
    public static bool3 operator ==(bool3 a, bool3 b) => new bool3(a.x == b.x, a.y == b.y, a.z == b.z);
    public static bool3 operator !=(bool3 a, bool3 b) => new bool3(a.x != b.x, a.y != b.y, a.z != b.z);
    public static bool3 operator ==(bool3 a, bool b) => new bool3(a.x == b, a.y == b, a.z == b);
    public static bool3 operator !=(bool3 a, bool b) => new bool3(a.x != b, a.y != b, a.z != b);
    public bool Equals(bool3 other) => x == other.x && y == other.y && z == other.z;
    public override bool Equals(object? obj) => obj is bool3 other && Equals(other);
    public override int GetHashCode() => HashCode.Combine(x, y, z);
    public override string ToString() => $"bool3({x}, {y}, {z})";

    // Swizzles, xyzw and rgba. Setters only where no component repeats.
    public bool2 xx => new bool2(x, x);
    public bool2 xy { get => new bool2(x, y); set { x = value.x; y = value.y; } }
    public bool2 xz { get => new bool2(x, z); set { x = value.x; z = value.y; } }
    public bool2 yx { get => new bool2(y, x); set { y = value.x; x = value.y; } }
    public bool2 yy => new bool2(y, y);
    public bool2 yz { get => new bool2(y, z); set { y = value.x; z = value.y; } }
    public bool2 zx { get => new bool2(z, x); set { z = value.x; x = value.y; } }
    public bool2 zy { get => new bool2(z, y); set { z = value.x; y = value.y; } }
    public bool2 zz => new bool2(z, z);
    public bool3 xxx => new bool3(x, x, x);
    public bool3 xxy => new bool3(x, x, y);
    public bool3 xxz => new bool3(x, x, z);
    public bool3 xyx => new bool3(x, y, x);
    public bool3 xyy => new bool3(x, y, y);
    public bool3 xyz { get => new bool3(x, y, z); set { x = value.x; y = value.y; z = value.z; } }
    public bool3 xzx => new bool3(x, z, x);
    public bool3 xzy { get => new bool3(x, z, y); set { x = value.x; z = value.y; y = value.z; } }
    public bool3 xzz => new bool3(x, z, z);
    public bool3 yxx => new bool3(y, x, x);
    public bool3 yxy => new bool3(y, x, y);
    public bool3 yxz { get => new bool3(y, x, z); set { y = value.x; x = value.y; z = value.z; } }
    public bool3 yyx => new bool3(y, y, x);
    public bool3 yyy => new bool3(y, y, y);
    public bool3 yyz => new bool3(y, y, z);
    public bool3 yzx { get => new bool3(y, z, x); set { y = value.x; z = value.y; x = value.z; } }
    public bool3 yzy => new bool3(y, z, y);
    public bool3 yzz => new bool3(y, z, z);
    public bool3 zxx => new bool3(z, x, x);
    public bool3 zxy { get => new bool3(z, x, y); set { z = value.x; x = value.y; y = value.z; } }
    public bool3 zxz => new bool3(z, x, z);
    public bool3 zyx { get => new bool3(z, y, x); set { z = value.x; y = value.y; x = value.z; } }
    public bool3 zyy => new bool3(z, y, y);
    public bool3 zyz => new bool3(z, y, z);
    public bool3 zzx => new bool3(z, z, x);
    public bool3 zzy => new bool3(z, z, y);
    public bool3 zzz => new bool3(z, z, z);
    public bool4 xxxx => new bool4(x, x, x, x);
    public bool4 xxxy => new bool4(x, x, x, y);
    public bool4 xxxz => new bool4(x, x, x, z);
    public bool4 xxyx => new bool4(x, x, y, x);
    public bool4 xxyy => new bool4(x, x, y, y);
    public bool4 xxyz => new bool4(x, x, y, z);
    public bool4 xxzx => new bool4(x, x, z, x);
    public bool4 xxzy => new bool4(x, x, z, y);
    public bool4 xxzz => new bool4(x, x, z, z);
    public bool4 xyxx => new bool4(x, y, x, x);
    public bool4 xyxy => new bool4(x, y, x, y);
    public bool4 xyxz => new bool4(x, y, x, z);
    public bool4 xyyx => new bool4(x, y, y, x);
    public bool4 xyyy => new bool4(x, y, y, y);
    public bool4 xyyz => new bool4(x, y, y, z);
    public bool4 xyzx => new bool4(x, y, z, x);
    public bool4 xyzy => new bool4(x, y, z, y);
    public bool4 xyzz => new bool4(x, y, z, z);
    public bool4 xzxx => new bool4(x, z, x, x);
    public bool4 xzxy => new bool4(x, z, x, y);
    public bool4 xzxz => new bool4(x, z, x, z);
    public bool4 xzyx => new bool4(x, z, y, x);
    public bool4 xzyy => new bool4(x, z, y, y);
    public bool4 xzyz => new bool4(x, z, y, z);
    public bool4 xzzx => new bool4(x, z, z, x);
    public bool4 xzzy => new bool4(x, z, z, y);
    public bool4 xzzz => new bool4(x, z, z, z);
    public bool4 yxxx => new bool4(y, x, x, x);
    public bool4 yxxy => new bool4(y, x, x, y);
    public bool4 yxxz => new bool4(y, x, x, z);
    public bool4 yxyx => new bool4(y, x, y, x);
    public bool4 yxyy => new bool4(y, x, y, y);
    public bool4 yxyz => new bool4(y, x, y, z);
    public bool4 yxzx => new bool4(y, x, z, x);
    public bool4 yxzy => new bool4(y, x, z, y);
    public bool4 yxzz => new bool4(y, x, z, z);
    public bool4 yyxx => new bool4(y, y, x, x);
    public bool4 yyxy => new bool4(y, y, x, y);
    public bool4 yyxz => new bool4(y, y, x, z);
    public bool4 yyyx => new bool4(y, y, y, x);
    public bool4 yyyy => new bool4(y, y, y, y);
    public bool4 yyyz => new bool4(y, y, y, z);
    public bool4 yyzx => new bool4(y, y, z, x);
    public bool4 yyzy => new bool4(y, y, z, y);
    public bool4 yyzz => new bool4(y, y, z, z);
    public bool4 yzxx => new bool4(y, z, x, x);
    public bool4 yzxy => new bool4(y, z, x, y);
    public bool4 yzxz => new bool4(y, z, x, z);
    public bool4 yzyx => new bool4(y, z, y, x);
    public bool4 yzyy => new bool4(y, z, y, y);
    public bool4 yzyz => new bool4(y, z, y, z);
    public bool4 yzzx => new bool4(y, z, z, x);
    public bool4 yzzy => new bool4(y, z, z, y);
    public bool4 yzzz => new bool4(y, z, z, z);
    public bool4 zxxx => new bool4(z, x, x, x);
    public bool4 zxxy => new bool4(z, x, x, y);
    public bool4 zxxz => new bool4(z, x, x, z);
    public bool4 zxyx => new bool4(z, x, y, x);
    public bool4 zxyy => new bool4(z, x, y, y);
    public bool4 zxyz => new bool4(z, x, y, z);
    public bool4 zxzx => new bool4(z, x, z, x);
    public bool4 zxzy => new bool4(z, x, z, y);
    public bool4 zxzz => new bool4(z, x, z, z);
    public bool4 zyxx => new bool4(z, y, x, x);
    public bool4 zyxy => new bool4(z, y, x, y);
    public bool4 zyxz => new bool4(z, y, x, z);
    public bool4 zyyx => new bool4(z, y, y, x);
    public bool4 zyyy => new bool4(z, y, y, y);
    public bool4 zyyz => new bool4(z, y, y, z);
    public bool4 zyzx => new bool4(z, y, z, x);
    public bool4 zyzy => new bool4(z, y, z, y);
    public bool4 zyzz => new bool4(z, y, z, z);
    public bool4 zzxx => new bool4(z, z, x, x);
    public bool4 zzxy => new bool4(z, z, x, y);
    public bool4 zzxz => new bool4(z, z, x, z);
    public bool4 zzyx => new bool4(z, z, y, x);
    public bool4 zzyy => new bool4(z, z, y, y);
    public bool4 zzyz => new bool4(z, z, y, z);
    public bool4 zzzx => new bool4(z, z, z, x);
    public bool4 zzzy => new bool4(z, z, z, y);
    public bool4 zzzz => new bool4(z, z, z, z);
    public bool r { get => x; set => x = value; }
    public bool g { get => y; set => y = value; }
    public bool b { get => z; set => z = value; }
    public bool2 rr => new bool2(x, x);
    public bool2 rg { get => new bool2(x, y); set { x = value.x; y = value.y; } }
    public bool2 rb { get => new bool2(x, z); set { x = value.x; z = value.y; } }
    public bool2 gr { get => new bool2(y, x); set { y = value.x; x = value.y; } }
    public bool2 gg => new bool2(y, y);
    public bool2 gb { get => new bool2(y, z); set { y = value.x; z = value.y; } }
    public bool2 br { get => new bool2(z, x); set { z = value.x; x = value.y; } }
    public bool2 bg { get => new bool2(z, y); set { z = value.x; y = value.y; } }
    public bool2 bb => new bool2(z, z);
    public bool3 rrr => new bool3(x, x, x);
    public bool3 rrg => new bool3(x, x, y);
    public bool3 rrb => new bool3(x, x, z);
    public bool3 rgr => new bool3(x, y, x);
    public bool3 rgg => new bool3(x, y, y);
    public bool3 rgb { get => new bool3(x, y, z); set { x = value.x; y = value.y; z = value.z; } }
    public bool3 rbr => new bool3(x, z, x);
    public bool3 rbg { get => new bool3(x, z, y); set { x = value.x; z = value.y; y = value.z; } }
    public bool3 rbb => new bool3(x, z, z);
    public bool3 grr => new bool3(y, x, x);
    public bool3 grg => new bool3(y, x, y);
    public bool3 grb { get => new bool3(y, x, z); set { y = value.x; x = value.y; z = value.z; } }
    public bool3 ggr => new bool3(y, y, x);
    public bool3 ggg => new bool3(y, y, y);
    public bool3 ggb => new bool3(y, y, z);
    public bool3 gbr { get => new bool3(y, z, x); set { y = value.x; z = value.y; x = value.z; } }
    public bool3 gbg => new bool3(y, z, y);
    public bool3 gbb => new bool3(y, z, z);
    public bool3 brr => new bool3(z, x, x);
    public bool3 brg { get => new bool3(z, x, y); set { z = value.x; x = value.y; y = value.z; } }
    public bool3 brb => new bool3(z, x, z);
    public bool3 bgr { get => new bool3(z, y, x); set { z = value.x; y = value.y; x = value.z; } }
    public bool3 bgg => new bool3(z, y, y);
    public bool3 bgb => new bool3(z, y, z);
    public bool3 bbr => new bool3(z, z, x);
    public bool3 bbg => new bool3(z, z, y);
    public bool3 bbb => new bool3(z, z, z);
    public bool4 rrrr => new bool4(x, x, x, x);
    public bool4 rrrg => new bool4(x, x, x, y);
    public bool4 rrrb => new bool4(x, x, x, z);
    public bool4 rrgr => new bool4(x, x, y, x);
    public bool4 rrgg => new bool4(x, x, y, y);
    public bool4 rrgb => new bool4(x, x, y, z);
    public bool4 rrbr => new bool4(x, x, z, x);
    public bool4 rrbg => new bool4(x, x, z, y);
    public bool4 rrbb => new bool4(x, x, z, z);
    public bool4 rgrr => new bool4(x, y, x, x);
    public bool4 rgrg => new bool4(x, y, x, y);
    public bool4 rgrb => new bool4(x, y, x, z);
    public bool4 rggr => new bool4(x, y, y, x);
    public bool4 rggg => new bool4(x, y, y, y);
    public bool4 rggb => new bool4(x, y, y, z);
    public bool4 rgbr => new bool4(x, y, z, x);
    public bool4 rgbg => new bool4(x, y, z, y);
    public bool4 rgbb => new bool4(x, y, z, z);
    public bool4 rbrr => new bool4(x, z, x, x);
    public bool4 rbrg => new bool4(x, z, x, y);
    public bool4 rbrb => new bool4(x, z, x, z);
    public bool4 rbgr => new bool4(x, z, y, x);
    public bool4 rbgg => new bool4(x, z, y, y);
    public bool4 rbgb => new bool4(x, z, y, z);
    public bool4 rbbr => new bool4(x, z, z, x);
    public bool4 rbbg => new bool4(x, z, z, y);
    public bool4 rbbb => new bool4(x, z, z, z);
    public bool4 grrr => new bool4(y, x, x, x);
    public bool4 grrg => new bool4(y, x, x, y);
    public bool4 grrb => new bool4(y, x, x, z);
    public bool4 grgr => new bool4(y, x, y, x);
    public bool4 grgg => new bool4(y, x, y, y);
    public bool4 grgb => new bool4(y, x, y, z);
    public bool4 grbr => new bool4(y, x, z, x);
    public bool4 grbg => new bool4(y, x, z, y);
    public bool4 grbb => new bool4(y, x, z, z);
    public bool4 ggrr => new bool4(y, y, x, x);
    public bool4 ggrg => new bool4(y, y, x, y);
    public bool4 ggrb => new bool4(y, y, x, z);
    public bool4 gggr => new bool4(y, y, y, x);
    public bool4 gggg => new bool4(y, y, y, y);
    public bool4 gggb => new bool4(y, y, y, z);
    public bool4 ggbr => new bool4(y, y, z, x);
    public bool4 ggbg => new bool4(y, y, z, y);
    public bool4 ggbb => new bool4(y, y, z, z);
    public bool4 gbrr => new bool4(y, z, x, x);
    public bool4 gbrg => new bool4(y, z, x, y);
    public bool4 gbrb => new bool4(y, z, x, z);
    public bool4 gbgr => new bool4(y, z, y, x);
    public bool4 gbgg => new bool4(y, z, y, y);
    public bool4 gbgb => new bool4(y, z, y, z);
    public bool4 gbbr => new bool4(y, z, z, x);
    public bool4 gbbg => new bool4(y, z, z, y);
    public bool4 gbbb => new bool4(y, z, z, z);
    public bool4 brrr => new bool4(z, x, x, x);
    public bool4 brrg => new bool4(z, x, x, y);
    public bool4 brrb => new bool4(z, x, x, z);
    public bool4 brgr => new bool4(z, x, y, x);
    public bool4 brgg => new bool4(z, x, y, y);
    public bool4 brgb => new bool4(z, x, y, z);
    public bool4 brbr => new bool4(z, x, z, x);
    public bool4 brbg => new bool4(z, x, z, y);
    public bool4 brbb => new bool4(z, x, z, z);
    public bool4 bgrr => new bool4(z, y, x, x);
    public bool4 bgrg => new bool4(z, y, x, y);
    public bool4 bgrb => new bool4(z, y, x, z);
    public bool4 bggr => new bool4(z, y, y, x);
    public bool4 bggg => new bool4(z, y, y, y);
    public bool4 bggb => new bool4(z, y, y, z);
    public bool4 bgbr => new bool4(z, y, z, x);
    public bool4 bgbg => new bool4(z, y, z, y);
    public bool4 bgbb => new bool4(z, y, z, z);
    public bool4 bbrr => new bool4(z, z, x, x);
    public bool4 bbrg => new bool4(z, z, x, y);
    public bool4 bbrb => new bool4(z, z, x, z);
    public bool4 bbgr => new bool4(z, z, y, x);
    public bool4 bbgg => new bool4(z, z, y, y);
    public bool4 bbgb => new bool4(z, z, y, z);
    public bool4 bbbr => new bool4(z, z, z, x);
    public bool4 bbbg => new bool4(z, z, z, y);
    public bool4 bbbb => new bool4(z, z, z, z);
}
