// <auto-generated>
// Written by tools/gen_hlsl_types.py. Do not edit; edit the script and run it again.
// </auto-generated>
#nullable enable
#pragma warning disable IDE1006, CS1591
using System;
using System.Runtime.InteropServices;

namespace Csl.Hlsl;

/// <summary>HLSL bool2: 2 components of bool. Runs on the GPU; the C# operations exist so shader code type-checks and can be unit tested.</summary>
[StructLayout(LayoutKind.Sequential)]
public struct bool2 : IEquatable<bool2>
{
    public bool x, y;
    public bool2(bool x, bool y) { this.x = x; this.y = y; }
    public bool2(bool v) { x = v; y = v; }
    public static implicit operator bool2(bool v) => new bool2(v);
    public bool this[int i]
    {
        get => i switch { 0 => x, 1 => y, _ => throw new IndexOutOfRangeException() };
        set { switch (i) { case 0: x = value; break; case 1: y = value; break; default: throw new IndexOutOfRangeException(); } }
    }
    public static bool2 operator &(bool2 a, bool2 b) => new bool2(a.x & b.x, a.y & b.y);
    public static bool2 operator |(bool2 a, bool2 b) => new bool2(a.x | b.x, a.y | b.y);
    public static bool2 operator ^(bool2 a, bool2 b) => new bool2(a.x ^ b.x, a.y ^ b.y);
    public static bool2 operator !(bool2 a) => new bool2(!a.x, !a.y);
    public static bool2 operator ==(bool2 a, bool2 b) => new bool2(a.x == b.x, a.y == b.y);
    public static bool2 operator !=(bool2 a, bool2 b) => new bool2(a.x != b.x, a.y != b.y);
    public static bool2 operator ==(bool2 a, bool b) => new bool2(a.x == b, a.y == b);
    public static bool2 operator !=(bool2 a, bool b) => new bool2(a.x != b, a.y != b);
    public bool Equals(bool2 other) => x == other.x && y == other.y;
    public override bool Equals(object? obj) => obj is bool2 other && Equals(other);
    public override int GetHashCode() => HashCode.Combine(x, y);
    public override string ToString() => $"bool2({x}, {y})";

    // Swizzles, xyzw and rgba. Setters only where no component repeats.
    public bool2 xx => new bool2(x, x);
    public bool2 xy { get => new bool2(x, y); set { x = value.x; y = value.y; } }
    public bool2 yx { get => new bool2(y, x); set { y = value.x; x = value.y; } }
    public bool2 yy => new bool2(y, y);
    public bool3 xxx => new bool3(x, x, x);
    public bool3 xxy => new bool3(x, x, y);
    public bool3 xyx => new bool3(x, y, x);
    public bool3 xyy => new bool3(x, y, y);
    public bool3 yxx => new bool3(y, x, x);
    public bool3 yxy => new bool3(y, x, y);
    public bool3 yyx => new bool3(y, y, x);
    public bool3 yyy => new bool3(y, y, y);
    public bool4 xxxx => new bool4(x, x, x, x);
    public bool4 xxxy => new bool4(x, x, x, y);
    public bool4 xxyx => new bool4(x, x, y, x);
    public bool4 xxyy => new bool4(x, x, y, y);
    public bool4 xyxx => new bool4(x, y, x, x);
    public bool4 xyxy => new bool4(x, y, x, y);
    public bool4 xyyx => new bool4(x, y, y, x);
    public bool4 xyyy => new bool4(x, y, y, y);
    public bool4 yxxx => new bool4(y, x, x, x);
    public bool4 yxxy => new bool4(y, x, x, y);
    public bool4 yxyx => new bool4(y, x, y, x);
    public bool4 yxyy => new bool4(y, x, y, y);
    public bool4 yyxx => new bool4(y, y, x, x);
    public bool4 yyxy => new bool4(y, y, x, y);
    public bool4 yyyx => new bool4(y, y, y, x);
    public bool4 yyyy => new bool4(y, y, y, y);
    public bool r { get => x; set => x = value; }
    public bool g { get => y; set => y = value; }
    public bool2 rr => new bool2(x, x);
    public bool2 rg { get => new bool2(x, y); set { x = value.x; y = value.y; } }
    public bool2 gr { get => new bool2(y, x); set { y = value.x; x = value.y; } }
    public bool2 gg => new bool2(y, y);
    public bool3 rrr => new bool3(x, x, x);
    public bool3 rrg => new bool3(x, x, y);
    public bool3 rgr => new bool3(x, y, x);
    public bool3 rgg => new bool3(x, y, y);
    public bool3 grr => new bool3(y, x, x);
    public bool3 grg => new bool3(y, x, y);
    public bool3 ggr => new bool3(y, y, x);
    public bool3 ggg => new bool3(y, y, y);
    public bool4 rrrr => new bool4(x, x, x, x);
    public bool4 rrrg => new bool4(x, x, x, y);
    public bool4 rrgr => new bool4(x, x, y, x);
    public bool4 rrgg => new bool4(x, x, y, y);
    public bool4 rgrr => new bool4(x, y, x, x);
    public bool4 rgrg => new bool4(x, y, x, y);
    public bool4 rggr => new bool4(x, y, y, x);
    public bool4 rggg => new bool4(x, y, y, y);
    public bool4 grrr => new bool4(y, x, x, x);
    public bool4 grrg => new bool4(y, x, x, y);
    public bool4 grgr => new bool4(y, x, y, x);
    public bool4 grgg => new bool4(y, x, y, y);
    public bool4 ggrr => new bool4(y, y, x, x);
    public bool4 ggrg => new bool4(y, y, x, y);
    public bool4 gggr => new bool4(y, y, y, x);
    public bool4 gggg => new bool4(y, y, y, y);
}
