// <auto-generated>
// Written by tools/gen_hlsl_types.py. Do not edit; edit the script and run it again.
// </auto-generated>
#nullable enable
#pragma warning disable IDE1006, CS1591
using System;
using System.Runtime.InteropServices;

namespace Csl.Hlsl;

/// <summary>HLSL float4: 4 components of float. Runs on the GPU; the C# operations exist so shader code type-checks and can be unit tested.</summary>
[StructLayout(LayoutKind.Sequential)]
public struct float4 : IEquatable<float4>
{
    public float x, y, z, w;
    public float4(float x, float y, float z, float w) { this.x = x; this.y = y; this.z = z; this.w = w; }
    public float4(float v) { x = v; y = v; z = v; w = v; }
    public float4(float3 xyz, float w) { x = xyz.x; y = xyz.y; z = xyz.z; this.w = w; }
    public float4(float x, float3 yzw) { this.x = x; y = yzw.x; z = yzw.y; w = yzw.z; }
    public float4(float2 xy, float2 zw) { x = xy.x; y = xy.y; z = zw.x; w = zw.y; }
    public float4(float2 xy, float z, float w) { x = xy.x; y = xy.y; this.z = z; this.w = w; }
    public float4(int4 v) { x = (float)v.x; y = (float)v.y; z = (float)v.z; w = (float)v.w; }
    public static implicit operator float4(int4 v) => new float4(v);
    public float4(uint4 v) { x = (float)v.x; y = (float)v.y; z = (float)v.z; w = (float)v.w; }
    public static implicit operator float4(uint4 v) => new float4(v);
    public static implicit operator float4(float v) => new float4(v);
    public float this[int i]
    {
        get => i switch { 0 => x, 1 => y, 2 => z, 3 => w, _ => throw new IndexOutOfRangeException() };
        set { switch (i) { case 0: x = value; break; case 1: y = value; break; case 2: z = value; break; case 3: w = value; break; default: throw new IndexOutOfRangeException(); } }
    }
    public static float4 operator +(float4 a, float4 b) => new float4((float)(a.x + b.x), (float)(a.y + b.y), (float)(a.z + b.z), (float)(a.w + b.w));
    public static float4 operator +(float4 a, float b) => new float4((float)(a.x + b), (float)(a.y + b), (float)(a.z + b), (float)(a.w + b));
    public static float4 operator +(float a, float4 b) => new float4((float)(a + b.x), (float)(a + b.y), (float)(a + b.z), (float)(a + b.w));
    public static float4 operator -(float4 a, float4 b) => new float4((float)(a.x - b.x), (float)(a.y - b.y), (float)(a.z - b.z), (float)(a.w - b.w));
    public static float4 operator -(float4 a, float b) => new float4((float)(a.x - b), (float)(a.y - b), (float)(a.z - b), (float)(a.w - b));
    public static float4 operator -(float a, float4 b) => new float4((float)(a - b.x), (float)(a - b.y), (float)(a - b.z), (float)(a - b.w));
    public static float4 operator *(float4 a, float4 b) => new float4((float)(a.x * b.x), (float)(a.y * b.y), (float)(a.z * b.z), (float)(a.w * b.w));
    public static float4 operator *(float4 a, float b) => new float4((float)(a.x * b), (float)(a.y * b), (float)(a.z * b), (float)(a.w * b));
    public static float4 operator *(float a, float4 b) => new float4((float)(a * b.x), (float)(a * b.y), (float)(a * b.z), (float)(a * b.w));
    public static float4 operator /(float4 a, float4 b) => new float4((float)(a.x / b.x), (float)(a.y / b.y), (float)(a.z / b.z), (float)(a.w / b.w));
    public static float4 operator /(float4 a, float b) => new float4((float)(a.x / b), (float)(a.y / b), (float)(a.z / b), (float)(a.w / b));
    public static float4 operator /(float a, float4 b) => new float4((float)(a / b.x), (float)(a / b.y), (float)(a / b.z), (float)(a / b.w));
    public static float4 operator %(float4 a, float4 b) => new float4((float)(a.x % b.x), (float)(a.y % b.y), (float)(a.z % b.z), (float)(a.w % b.w));
    public static float4 operator %(float4 a, float b) => new float4((float)(a.x % b), (float)(a.y % b), (float)(a.z % b), (float)(a.w % b));
    public static float4 operator %(float a, float4 b) => new float4((float)(a % b.x), (float)(a % b.y), (float)(a % b.z), (float)(a % b.w));
    public static float4 operator -(float4 a) => new float4((float)(-a.x), (float)(-a.y), (float)(-a.z), (float)(-a.w));
    public static float4 operator +(float4 a) => a;
    public static float4 operator ++(float4 a) => new float4((float)(a.x + 1f), (float)(a.y + 1f), (float)(a.z + 1f), (float)(a.w + 1f));
    public static float4 operator --(float4 a) => new float4((float)(a.x - 1f), (float)(a.y - 1f), (float)(a.z - 1f), (float)(a.w - 1f));
    public static bool4 operator <(float4 a, float4 b) => new bool4(a.x < b.x, a.y < b.y, a.z < b.z, a.w < b.w);
    public static bool4 operator <(float4 a, float b) => new bool4(a.x < b, a.y < b, a.z < b, a.w < b);
    public static bool4 operator <(float a, float4 b) => new bool4(a < b.x, a < b.y, a < b.z, a < b.w);
    public static bool4 operator >(float4 a, float4 b) => new bool4(a.x > b.x, a.y > b.y, a.z > b.z, a.w > b.w);
    public static bool4 operator >(float4 a, float b) => new bool4(a.x > b, a.y > b, a.z > b, a.w > b);
    public static bool4 operator >(float a, float4 b) => new bool4(a > b.x, a > b.y, a > b.z, a > b.w);
    public static bool4 operator <=(float4 a, float4 b) => new bool4(a.x <= b.x, a.y <= b.y, a.z <= b.z, a.w <= b.w);
    public static bool4 operator <=(float4 a, float b) => new bool4(a.x <= b, a.y <= b, a.z <= b, a.w <= b);
    public static bool4 operator <=(float a, float4 b) => new bool4(a <= b.x, a <= b.y, a <= b.z, a <= b.w);
    public static bool4 operator >=(float4 a, float4 b) => new bool4(a.x >= b.x, a.y >= b.y, a.z >= b.z, a.w >= b.w);
    public static bool4 operator >=(float4 a, float b) => new bool4(a.x >= b, a.y >= b, a.z >= b, a.w >= b);
    public static bool4 operator >=(float a, float4 b) => new bool4(a >= b.x, a >= b.y, a >= b.z, a >= b.w);
    public static bool4 operator ==(float4 a, float4 b) => new bool4(a.x == b.x, a.y == b.y, a.z == b.z, a.w == b.w);
    public static bool4 operator !=(float4 a, float4 b) => new bool4(a.x != b.x, a.y != b.y, a.z != b.z, a.w != b.w);
    public static bool4 operator ==(float4 a, float b) => new bool4(a.x == b, a.y == b, a.z == b, a.w == b);
    public static bool4 operator !=(float4 a, float b) => new bool4(a.x != b, a.y != b, a.z != b, a.w != b);
    public bool Equals(float4 other) => x == other.x && y == other.y && z == other.z && w == other.w;
    public override bool Equals(object? obj) => obj is float4 other && Equals(other);
    public override int GetHashCode() => HashCode.Combine(x, y, z, w);
    public override string ToString() => $"float4({x}, {y}, {z}, {w})";

    // Swizzles, xyzw and rgba. Setters only where no component repeats.
    public float2 xx => new float2(x, x);
    public float2 xy { get => new float2(x, y); set { x = value.x; y = value.y; } }
    public float2 xz { get => new float2(x, z); set { x = value.x; z = value.y; } }
    public float2 xw { get => new float2(x, w); set { x = value.x; w = value.y; } }
    public float2 yx { get => new float2(y, x); set { y = value.x; x = value.y; } }
    public float2 yy => new float2(y, y);
    public float2 yz { get => new float2(y, z); set { y = value.x; z = value.y; } }
    public float2 yw { get => new float2(y, w); set { y = value.x; w = value.y; } }
    public float2 zx { get => new float2(z, x); set { z = value.x; x = value.y; } }
    public float2 zy { get => new float2(z, y); set { z = value.x; y = value.y; } }
    public float2 zz => new float2(z, z);
    public float2 zw { get => new float2(z, w); set { z = value.x; w = value.y; } }
    public float2 wx { get => new float2(w, x); set { w = value.x; x = value.y; } }
    public float2 wy { get => new float2(w, y); set { w = value.x; y = value.y; } }
    public float2 wz { get => new float2(w, z); set { w = value.x; z = value.y; } }
    public float2 ww => new float2(w, w);
    public float3 xxx => new float3(x, x, x);
    public float3 xxy => new float3(x, x, y);
    public float3 xxz => new float3(x, x, z);
    public float3 xxw => new float3(x, x, w);
    public float3 xyx => new float3(x, y, x);
    public float3 xyy => new float3(x, y, y);
    public float3 xyz { get => new float3(x, y, z); set { x = value.x; y = value.y; z = value.z; } }
    public float3 xyw { get => new float3(x, y, w); set { x = value.x; y = value.y; w = value.z; } }
    public float3 xzx => new float3(x, z, x);
    public float3 xzy { get => new float3(x, z, y); set { x = value.x; z = value.y; y = value.z; } }
    public float3 xzz => new float3(x, z, z);
    public float3 xzw { get => new float3(x, z, w); set { x = value.x; z = value.y; w = value.z; } }
    public float3 xwx => new float3(x, w, x);
    public float3 xwy { get => new float3(x, w, y); set { x = value.x; w = value.y; y = value.z; } }
    public float3 xwz { get => new float3(x, w, z); set { x = value.x; w = value.y; z = value.z; } }
    public float3 xww => new float3(x, w, w);
    public float3 yxx => new float3(y, x, x);
    public float3 yxy => new float3(y, x, y);
    public float3 yxz { get => new float3(y, x, z); set { y = value.x; x = value.y; z = value.z; } }
    public float3 yxw { get => new float3(y, x, w); set { y = value.x; x = value.y; w = value.z; } }
    public float3 yyx => new float3(y, y, x);
    public float3 yyy => new float3(y, y, y);
    public float3 yyz => new float3(y, y, z);
    public float3 yyw => new float3(y, y, w);
    public float3 yzx { get => new float3(y, z, x); set { y = value.x; z = value.y; x = value.z; } }
    public float3 yzy => new float3(y, z, y);
    public float3 yzz => new float3(y, z, z);
    public float3 yzw { get => new float3(y, z, w); set { y = value.x; z = value.y; w = value.z; } }
    public float3 ywx { get => new float3(y, w, x); set { y = value.x; w = value.y; x = value.z; } }
    public float3 ywy => new float3(y, w, y);
    public float3 ywz { get => new float3(y, w, z); set { y = value.x; w = value.y; z = value.z; } }
    public float3 yww => new float3(y, w, w);
    public float3 zxx => new float3(z, x, x);
    public float3 zxy { get => new float3(z, x, y); set { z = value.x; x = value.y; y = value.z; } }
    public float3 zxz => new float3(z, x, z);
    public float3 zxw { get => new float3(z, x, w); set { z = value.x; x = value.y; w = value.z; } }
    public float3 zyx { get => new float3(z, y, x); set { z = value.x; y = value.y; x = value.z; } }
    public float3 zyy => new float3(z, y, y);
    public float3 zyz => new float3(z, y, z);
    public float3 zyw { get => new float3(z, y, w); set { z = value.x; y = value.y; w = value.z; } }
    public float3 zzx => new float3(z, z, x);
    public float3 zzy => new float3(z, z, y);
    public float3 zzz => new float3(z, z, z);
    public float3 zzw => new float3(z, z, w);
    public float3 zwx { get => new float3(z, w, x); set { z = value.x; w = value.y; x = value.z; } }
    public float3 zwy { get => new float3(z, w, y); set { z = value.x; w = value.y; y = value.z; } }
    public float3 zwz => new float3(z, w, z);
    public float3 zww => new float3(z, w, w);
    public float3 wxx => new float3(w, x, x);
    public float3 wxy { get => new float3(w, x, y); set { w = value.x; x = value.y; y = value.z; } }
    public float3 wxz { get => new float3(w, x, z); set { w = value.x; x = value.y; z = value.z; } }
    public float3 wxw => new float3(w, x, w);
    public float3 wyx { get => new float3(w, y, x); set { w = value.x; y = value.y; x = value.z; } }
    public float3 wyy => new float3(w, y, y);
    public float3 wyz { get => new float3(w, y, z); set { w = value.x; y = value.y; z = value.z; } }
    public float3 wyw => new float3(w, y, w);
    public float3 wzx { get => new float3(w, z, x); set { w = value.x; z = value.y; x = value.z; } }
    public float3 wzy { get => new float3(w, z, y); set { w = value.x; z = value.y; y = value.z; } }
    public float3 wzz => new float3(w, z, z);
    public float3 wzw => new float3(w, z, w);
    public float3 wwx => new float3(w, w, x);
    public float3 wwy => new float3(w, w, y);
    public float3 wwz => new float3(w, w, z);
    public float3 www => new float3(w, w, w);
    public float4 xxxx => new float4(x, x, x, x);
    public float4 xxxy => new float4(x, x, x, y);
    public float4 xxxz => new float4(x, x, x, z);
    public float4 xxxw => new float4(x, x, x, w);
    public float4 xxyx => new float4(x, x, y, x);
    public float4 xxyy => new float4(x, x, y, y);
    public float4 xxyz => new float4(x, x, y, z);
    public float4 xxyw => new float4(x, x, y, w);
    public float4 xxzx => new float4(x, x, z, x);
    public float4 xxzy => new float4(x, x, z, y);
    public float4 xxzz => new float4(x, x, z, z);
    public float4 xxzw => new float4(x, x, z, w);
    public float4 xxwx => new float4(x, x, w, x);
    public float4 xxwy => new float4(x, x, w, y);
    public float4 xxwz => new float4(x, x, w, z);
    public float4 xxww => new float4(x, x, w, w);
    public float4 xyxx => new float4(x, y, x, x);
    public float4 xyxy => new float4(x, y, x, y);
    public float4 xyxz => new float4(x, y, x, z);
    public float4 xyxw => new float4(x, y, x, w);
    public float4 xyyx => new float4(x, y, y, x);
    public float4 xyyy => new float4(x, y, y, y);
    public float4 xyyz => new float4(x, y, y, z);
    public float4 xyyw => new float4(x, y, y, w);
    public float4 xyzx => new float4(x, y, z, x);
    public float4 xyzy => new float4(x, y, z, y);
    public float4 xyzz => new float4(x, y, z, z);
    public float4 xyzw { get => new float4(x, y, z, w); set { x = value.x; y = value.y; z = value.z; w = value.w; } }
    public float4 xywx => new float4(x, y, w, x);
    public float4 xywy => new float4(x, y, w, y);
    public float4 xywz { get => new float4(x, y, w, z); set { x = value.x; y = value.y; w = value.z; z = value.w; } }
    public float4 xyww => new float4(x, y, w, w);
    public float4 xzxx => new float4(x, z, x, x);
    public float4 xzxy => new float4(x, z, x, y);
    public float4 xzxz => new float4(x, z, x, z);
    public float4 xzxw => new float4(x, z, x, w);
    public float4 xzyx => new float4(x, z, y, x);
    public float4 xzyy => new float4(x, z, y, y);
    public float4 xzyz => new float4(x, z, y, z);
    public float4 xzyw { get => new float4(x, z, y, w); set { x = value.x; z = value.y; y = value.z; w = value.w; } }
    public float4 xzzx => new float4(x, z, z, x);
    public float4 xzzy => new float4(x, z, z, y);
    public float4 xzzz => new float4(x, z, z, z);
    public float4 xzzw => new float4(x, z, z, w);
    public float4 xzwx => new float4(x, z, w, x);
    public float4 xzwy { get => new float4(x, z, w, y); set { x = value.x; z = value.y; w = value.z; y = value.w; } }
    public float4 xzwz => new float4(x, z, w, z);
    public float4 xzww => new float4(x, z, w, w);
    public float4 xwxx => new float4(x, w, x, x);
    public float4 xwxy => new float4(x, w, x, y);
    public float4 xwxz => new float4(x, w, x, z);
    public float4 xwxw => new float4(x, w, x, w);
    public float4 xwyx => new float4(x, w, y, x);
    public float4 xwyy => new float4(x, w, y, y);
    public float4 xwyz { get => new float4(x, w, y, z); set { x = value.x; w = value.y; y = value.z; z = value.w; } }
    public float4 xwyw => new float4(x, w, y, w);
    public float4 xwzx => new float4(x, w, z, x);
    public float4 xwzy { get => new float4(x, w, z, y); set { x = value.x; w = value.y; z = value.z; y = value.w; } }
    public float4 xwzz => new float4(x, w, z, z);
    public float4 xwzw => new float4(x, w, z, w);
    public float4 xwwx => new float4(x, w, w, x);
    public float4 xwwy => new float4(x, w, w, y);
    public float4 xwwz => new float4(x, w, w, z);
    public float4 xwww => new float4(x, w, w, w);
    public float4 yxxx => new float4(y, x, x, x);
    public float4 yxxy => new float4(y, x, x, y);
    public float4 yxxz => new float4(y, x, x, z);
    public float4 yxxw => new float4(y, x, x, w);
    public float4 yxyx => new float4(y, x, y, x);
    public float4 yxyy => new float4(y, x, y, y);
    public float4 yxyz => new float4(y, x, y, z);
    public float4 yxyw => new float4(y, x, y, w);
    public float4 yxzx => new float4(y, x, z, x);
    public float4 yxzy => new float4(y, x, z, y);
    public float4 yxzz => new float4(y, x, z, z);
    public float4 yxzw { get => new float4(y, x, z, w); set { y = value.x; x = value.y; z = value.z; w = value.w; } }
    public float4 yxwx => new float4(y, x, w, x);
    public float4 yxwy => new float4(y, x, w, y);
    public float4 yxwz { get => new float4(y, x, w, z); set { y = value.x; x = value.y; w = value.z; z = value.w; } }
    public float4 yxww => new float4(y, x, w, w);
    public float4 yyxx => new float4(y, y, x, x);
    public float4 yyxy => new float4(y, y, x, y);
    public float4 yyxz => new float4(y, y, x, z);
    public float4 yyxw => new float4(y, y, x, w);
    public float4 yyyx => new float4(y, y, y, x);
    public float4 yyyy => new float4(y, y, y, y);
    public float4 yyyz => new float4(y, y, y, z);
    public float4 yyyw => new float4(y, y, y, w);
    public float4 yyzx => new float4(y, y, z, x);
    public float4 yyzy => new float4(y, y, z, y);
    public float4 yyzz => new float4(y, y, z, z);
    public float4 yyzw => new float4(y, y, z, w);
    public float4 yywx => new float4(y, y, w, x);
    public float4 yywy => new float4(y, y, w, y);
    public float4 yywz => new float4(y, y, w, z);
    public float4 yyww => new float4(y, y, w, w);
    public float4 yzxx => new float4(y, z, x, x);
    public float4 yzxy => new float4(y, z, x, y);
    public float4 yzxz => new float4(y, z, x, z);
    public float4 yzxw { get => new float4(y, z, x, w); set { y = value.x; z = value.y; x = value.z; w = value.w; } }
    public float4 yzyx => new float4(y, z, y, x);
    public float4 yzyy => new float4(y, z, y, y);
    public float4 yzyz => new float4(y, z, y, z);
    public float4 yzyw => new float4(y, z, y, w);
    public float4 yzzx => new float4(y, z, z, x);
    public float4 yzzy => new float4(y, z, z, y);
    public float4 yzzz => new float4(y, z, z, z);
    public float4 yzzw => new float4(y, z, z, w);
    public float4 yzwx { get => new float4(y, z, w, x); set { y = value.x; z = value.y; w = value.z; x = value.w; } }
    public float4 yzwy => new float4(y, z, w, y);
    public float4 yzwz => new float4(y, z, w, z);
    public float4 yzww => new float4(y, z, w, w);
    public float4 ywxx => new float4(y, w, x, x);
    public float4 ywxy => new float4(y, w, x, y);
    public float4 ywxz { get => new float4(y, w, x, z); set { y = value.x; w = value.y; x = value.z; z = value.w; } }
    public float4 ywxw => new float4(y, w, x, w);
    public float4 ywyx => new float4(y, w, y, x);
    public float4 ywyy => new float4(y, w, y, y);
    public float4 ywyz => new float4(y, w, y, z);
    public float4 ywyw => new float4(y, w, y, w);
    public float4 ywzx { get => new float4(y, w, z, x); set { y = value.x; w = value.y; z = value.z; x = value.w; } }
    public float4 ywzy => new float4(y, w, z, y);
    public float4 ywzz => new float4(y, w, z, z);
    public float4 ywzw => new float4(y, w, z, w);
    public float4 ywwx => new float4(y, w, w, x);
    public float4 ywwy => new float4(y, w, w, y);
    public float4 ywwz => new float4(y, w, w, z);
    public float4 ywww => new float4(y, w, w, w);
    public float4 zxxx => new float4(z, x, x, x);
    public float4 zxxy => new float4(z, x, x, y);
    public float4 zxxz => new float4(z, x, x, z);
    public float4 zxxw => new float4(z, x, x, w);
    public float4 zxyx => new float4(z, x, y, x);
    public float4 zxyy => new float4(z, x, y, y);
    public float4 zxyz => new float4(z, x, y, z);
    public float4 zxyw { get => new float4(z, x, y, w); set { z = value.x; x = value.y; y = value.z; w = value.w; } }
    public float4 zxzx => new float4(z, x, z, x);
    public float4 zxzy => new float4(z, x, z, y);
    public float4 zxzz => new float4(z, x, z, z);
    public float4 zxzw => new float4(z, x, z, w);
    public float4 zxwx => new float4(z, x, w, x);
    public float4 zxwy { get => new float4(z, x, w, y); set { z = value.x; x = value.y; w = value.z; y = value.w; } }
    public float4 zxwz => new float4(z, x, w, z);
    public float4 zxww => new float4(z, x, w, w);
    public float4 zyxx => new float4(z, y, x, x);
    public float4 zyxy => new float4(z, y, x, y);
    public float4 zyxz => new float4(z, y, x, z);
    public float4 zyxw { get => new float4(z, y, x, w); set { z = value.x; y = value.y; x = value.z; w = value.w; } }
    public float4 zyyx => new float4(z, y, y, x);
    public float4 zyyy => new float4(z, y, y, y);
    public float4 zyyz => new float4(z, y, y, z);
    public float4 zyyw => new float4(z, y, y, w);
    public float4 zyzx => new float4(z, y, z, x);
    public float4 zyzy => new float4(z, y, z, y);
    public float4 zyzz => new float4(z, y, z, z);
    public float4 zyzw => new float4(z, y, z, w);
    public float4 zywx { get => new float4(z, y, w, x); set { z = value.x; y = value.y; w = value.z; x = value.w; } }
    public float4 zywy => new float4(z, y, w, y);
    public float4 zywz => new float4(z, y, w, z);
    public float4 zyww => new float4(z, y, w, w);
    public float4 zzxx => new float4(z, z, x, x);
    public float4 zzxy => new float4(z, z, x, y);
    public float4 zzxz => new float4(z, z, x, z);
    public float4 zzxw => new float4(z, z, x, w);
    public float4 zzyx => new float4(z, z, y, x);
    public float4 zzyy => new float4(z, z, y, y);
    public float4 zzyz => new float4(z, z, y, z);
    public float4 zzyw => new float4(z, z, y, w);
    public float4 zzzx => new float4(z, z, z, x);
    public float4 zzzy => new float4(z, z, z, y);
    public float4 zzzz => new float4(z, z, z, z);
    public float4 zzzw => new float4(z, z, z, w);
    public float4 zzwx => new float4(z, z, w, x);
    public float4 zzwy => new float4(z, z, w, y);
    public float4 zzwz => new float4(z, z, w, z);
    public float4 zzww => new float4(z, z, w, w);
    public float4 zwxx => new float4(z, w, x, x);
    public float4 zwxy { get => new float4(z, w, x, y); set { z = value.x; w = value.y; x = value.z; y = value.w; } }
    public float4 zwxz => new float4(z, w, x, z);
    public float4 zwxw => new float4(z, w, x, w);
    public float4 zwyx { get => new float4(z, w, y, x); set { z = value.x; w = value.y; y = value.z; x = value.w; } }
    public float4 zwyy => new float4(z, w, y, y);
    public float4 zwyz => new float4(z, w, y, z);
    public float4 zwyw => new float4(z, w, y, w);
    public float4 zwzx => new float4(z, w, z, x);
    public float4 zwzy => new float4(z, w, z, y);
    public float4 zwzz => new float4(z, w, z, z);
    public float4 zwzw => new float4(z, w, z, w);
    public float4 zwwx => new float4(z, w, w, x);
    public float4 zwwy => new float4(z, w, w, y);
    public float4 zwwz => new float4(z, w, w, z);
    public float4 zwww => new float4(z, w, w, w);
    public float4 wxxx => new float4(w, x, x, x);
    public float4 wxxy => new float4(w, x, x, y);
    public float4 wxxz => new float4(w, x, x, z);
    public float4 wxxw => new float4(w, x, x, w);
    public float4 wxyx => new float4(w, x, y, x);
    public float4 wxyy => new float4(w, x, y, y);
    public float4 wxyz { get => new float4(w, x, y, z); set { w = value.x; x = value.y; y = value.z; z = value.w; } }
    public float4 wxyw => new float4(w, x, y, w);
    public float4 wxzx => new float4(w, x, z, x);
    public float4 wxzy { get => new float4(w, x, z, y); set { w = value.x; x = value.y; z = value.z; y = value.w; } }
    public float4 wxzz => new float4(w, x, z, z);
    public float4 wxzw => new float4(w, x, z, w);
    public float4 wxwx => new float4(w, x, w, x);
    public float4 wxwy => new float4(w, x, w, y);
    public float4 wxwz => new float4(w, x, w, z);
    public float4 wxww => new float4(w, x, w, w);
    public float4 wyxx => new float4(w, y, x, x);
    public float4 wyxy => new float4(w, y, x, y);
    public float4 wyxz { get => new float4(w, y, x, z); set { w = value.x; y = value.y; x = value.z; z = value.w; } }
    public float4 wyxw => new float4(w, y, x, w);
    public float4 wyyx => new float4(w, y, y, x);
    public float4 wyyy => new float4(w, y, y, y);
    public float4 wyyz => new float4(w, y, y, z);
    public float4 wyyw => new float4(w, y, y, w);
    public float4 wyzx { get => new float4(w, y, z, x); set { w = value.x; y = value.y; z = value.z; x = value.w; } }
    public float4 wyzy => new float4(w, y, z, y);
    public float4 wyzz => new float4(w, y, z, z);
    public float4 wyzw => new float4(w, y, z, w);
    public float4 wywx => new float4(w, y, w, x);
    public float4 wywy => new float4(w, y, w, y);
    public float4 wywz => new float4(w, y, w, z);
    public float4 wyww => new float4(w, y, w, w);
    public float4 wzxx => new float4(w, z, x, x);
    public float4 wzxy { get => new float4(w, z, x, y); set { w = value.x; z = value.y; x = value.z; y = value.w; } }
    public float4 wzxz => new float4(w, z, x, z);
    public float4 wzxw => new float4(w, z, x, w);
    public float4 wzyx { get => new float4(w, z, y, x); set { w = value.x; z = value.y; y = value.z; x = value.w; } }
    public float4 wzyy => new float4(w, z, y, y);
    public float4 wzyz => new float4(w, z, y, z);
    public float4 wzyw => new float4(w, z, y, w);
    public float4 wzzx => new float4(w, z, z, x);
    public float4 wzzy => new float4(w, z, z, y);
    public float4 wzzz => new float4(w, z, z, z);
    public float4 wzzw => new float4(w, z, z, w);
    public float4 wzwx => new float4(w, z, w, x);
    public float4 wzwy => new float4(w, z, w, y);
    public float4 wzwz => new float4(w, z, w, z);
    public float4 wzww => new float4(w, z, w, w);
    public float4 wwxx => new float4(w, w, x, x);
    public float4 wwxy => new float4(w, w, x, y);
    public float4 wwxz => new float4(w, w, x, z);
    public float4 wwxw => new float4(w, w, x, w);
    public float4 wwyx => new float4(w, w, y, x);
    public float4 wwyy => new float4(w, w, y, y);
    public float4 wwyz => new float4(w, w, y, z);
    public float4 wwyw => new float4(w, w, y, w);
    public float4 wwzx => new float4(w, w, z, x);
    public float4 wwzy => new float4(w, w, z, y);
    public float4 wwzz => new float4(w, w, z, z);
    public float4 wwzw => new float4(w, w, z, w);
    public float4 wwwx => new float4(w, w, w, x);
    public float4 wwwy => new float4(w, w, w, y);
    public float4 wwwz => new float4(w, w, w, z);
    public float4 wwww => new float4(w, w, w, w);
    public float r { get => x; set => x = value; }
    public float g { get => y; set => y = value; }
    public float b { get => z; set => z = value; }
    public float a { get => w; set => w = value; }
    public float2 rr => new float2(x, x);
    public float2 rg { get => new float2(x, y); set { x = value.x; y = value.y; } }
    public float2 rb { get => new float2(x, z); set { x = value.x; z = value.y; } }
    public float2 ra { get => new float2(x, w); set { x = value.x; w = value.y; } }
    public float2 gr { get => new float2(y, x); set { y = value.x; x = value.y; } }
    public float2 gg => new float2(y, y);
    public float2 gb { get => new float2(y, z); set { y = value.x; z = value.y; } }
    public float2 ga { get => new float2(y, w); set { y = value.x; w = value.y; } }
    public float2 br { get => new float2(z, x); set { z = value.x; x = value.y; } }
    public float2 bg { get => new float2(z, y); set { z = value.x; y = value.y; } }
    public float2 bb => new float2(z, z);
    public float2 ba { get => new float2(z, w); set { z = value.x; w = value.y; } }
    public float2 ar { get => new float2(w, x); set { w = value.x; x = value.y; } }
    public float2 ag { get => new float2(w, y); set { w = value.x; y = value.y; } }
    public float2 ab { get => new float2(w, z); set { w = value.x; z = value.y; } }
    public float2 aa => new float2(w, w);
    public float3 rrr => new float3(x, x, x);
    public float3 rrg => new float3(x, x, y);
    public float3 rrb => new float3(x, x, z);
    public float3 rra => new float3(x, x, w);
    public float3 rgr => new float3(x, y, x);
    public float3 rgg => new float3(x, y, y);
    public float3 rgb { get => new float3(x, y, z); set { x = value.x; y = value.y; z = value.z; } }
    public float3 rga { get => new float3(x, y, w); set { x = value.x; y = value.y; w = value.z; } }
    public float3 rbr => new float3(x, z, x);
    public float3 rbg { get => new float3(x, z, y); set { x = value.x; z = value.y; y = value.z; } }
    public float3 rbb => new float3(x, z, z);
    public float3 rba { get => new float3(x, z, w); set { x = value.x; z = value.y; w = value.z; } }
    public float3 rar => new float3(x, w, x);
    public float3 rag { get => new float3(x, w, y); set { x = value.x; w = value.y; y = value.z; } }
    public float3 rab { get => new float3(x, w, z); set { x = value.x; w = value.y; z = value.z; } }
    public float3 raa => new float3(x, w, w);
    public float3 grr => new float3(y, x, x);
    public float3 grg => new float3(y, x, y);
    public float3 grb { get => new float3(y, x, z); set { y = value.x; x = value.y; z = value.z; } }
    public float3 gra { get => new float3(y, x, w); set { y = value.x; x = value.y; w = value.z; } }
    public float3 ggr => new float3(y, y, x);
    public float3 ggg => new float3(y, y, y);
    public float3 ggb => new float3(y, y, z);
    public float3 gga => new float3(y, y, w);
    public float3 gbr { get => new float3(y, z, x); set { y = value.x; z = value.y; x = value.z; } }
    public float3 gbg => new float3(y, z, y);
    public float3 gbb => new float3(y, z, z);
    public float3 gba { get => new float3(y, z, w); set { y = value.x; z = value.y; w = value.z; } }
    public float3 gar { get => new float3(y, w, x); set { y = value.x; w = value.y; x = value.z; } }
    public float3 gag => new float3(y, w, y);
    public float3 gab { get => new float3(y, w, z); set { y = value.x; w = value.y; z = value.z; } }
    public float3 gaa => new float3(y, w, w);
    public float3 brr => new float3(z, x, x);
    public float3 brg { get => new float3(z, x, y); set { z = value.x; x = value.y; y = value.z; } }
    public float3 brb => new float3(z, x, z);
    public float3 bra { get => new float3(z, x, w); set { z = value.x; x = value.y; w = value.z; } }
    public float3 bgr { get => new float3(z, y, x); set { z = value.x; y = value.y; x = value.z; } }
    public float3 bgg => new float3(z, y, y);
    public float3 bgb => new float3(z, y, z);
    public float3 bga { get => new float3(z, y, w); set { z = value.x; y = value.y; w = value.z; } }
    public float3 bbr => new float3(z, z, x);
    public float3 bbg => new float3(z, z, y);
    public float3 bbb => new float3(z, z, z);
    public float3 bba => new float3(z, z, w);
    public float3 bar { get => new float3(z, w, x); set { z = value.x; w = value.y; x = value.z; } }
    public float3 bag { get => new float3(z, w, y); set { z = value.x; w = value.y; y = value.z; } }
    public float3 bab => new float3(z, w, z);
    public float3 baa => new float3(z, w, w);
    public float3 arr => new float3(w, x, x);
    public float3 arg { get => new float3(w, x, y); set { w = value.x; x = value.y; y = value.z; } }
    public float3 arb { get => new float3(w, x, z); set { w = value.x; x = value.y; z = value.z; } }
    public float3 ara => new float3(w, x, w);
    public float3 agr { get => new float3(w, y, x); set { w = value.x; y = value.y; x = value.z; } }
    public float3 agg => new float3(w, y, y);
    public float3 agb { get => new float3(w, y, z); set { w = value.x; y = value.y; z = value.z; } }
    public float3 aga => new float3(w, y, w);
    public float3 abr { get => new float3(w, z, x); set { w = value.x; z = value.y; x = value.z; } }
    public float3 abg { get => new float3(w, z, y); set { w = value.x; z = value.y; y = value.z; } }
    public float3 abb => new float3(w, z, z);
    public float3 aba => new float3(w, z, w);
    public float3 aar => new float3(w, w, x);
    public float3 aag => new float3(w, w, y);
    public float3 aab => new float3(w, w, z);
    public float3 aaa => new float3(w, w, w);
    public float4 rrrr => new float4(x, x, x, x);
    public float4 rrrg => new float4(x, x, x, y);
    public float4 rrrb => new float4(x, x, x, z);
    public float4 rrra => new float4(x, x, x, w);
    public float4 rrgr => new float4(x, x, y, x);
    public float4 rrgg => new float4(x, x, y, y);
    public float4 rrgb => new float4(x, x, y, z);
    public float4 rrga => new float4(x, x, y, w);
    public float4 rrbr => new float4(x, x, z, x);
    public float4 rrbg => new float4(x, x, z, y);
    public float4 rrbb => new float4(x, x, z, z);
    public float4 rrba => new float4(x, x, z, w);
    public float4 rrar => new float4(x, x, w, x);
    public float4 rrag => new float4(x, x, w, y);
    public float4 rrab => new float4(x, x, w, z);
    public float4 rraa => new float4(x, x, w, w);
    public float4 rgrr => new float4(x, y, x, x);
    public float4 rgrg => new float4(x, y, x, y);
    public float4 rgrb => new float4(x, y, x, z);
    public float4 rgra => new float4(x, y, x, w);
    public float4 rggr => new float4(x, y, y, x);
    public float4 rggg => new float4(x, y, y, y);
    public float4 rggb => new float4(x, y, y, z);
    public float4 rgga => new float4(x, y, y, w);
    public float4 rgbr => new float4(x, y, z, x);
    public float4 rgbg => new float4(x, y, z, y);
    public float4 rgbb => new float4(x, y, z, z);
    public float4 rgba { get => new float4(x, y, z, w); set { x = value.x; y = value.y; z = value.z; w = value.w; } }
    public float4 rgar => new float4(x, y, w, x);
    public float4 rgag => new float4(x, y, w, y);
    public float4 rgab { get => new float4(x, y, w, z); set { x = value.x; y = value.y; w = value.z; z = value.w; } }
    public float4 rgaa => new float4(x, y, w, w);
    public float4 rbrr => new float4(x, z, x, x);
    public float4 rbrg => new float4(x, z, x, y);
    public float4 rbrb => new float4(x, z, x, z);
    public float4 rbra => new float4(x, z, x, w);
    public float4 rbgr => new float4(x, z, y, x);
    public float4 rbgg => new float4(x, z, y, y);
    public float4 rbgb => new float4(x, z, y, z);
    public float4 rbga { get => new float4(x, z, y, w); set { x = value.x; z = value.y; y = value.z; w = value.w; } }
    public float4 rbbr => new float4(x, z, z, x);
    public float4 rbbg => new float4(x, z, z, y);
    public float4 rbbb => new float4(x, z, z, z);
    public float4 rbba => new float4(x, z, z, w);
    public float4 rbar => new float4(x, z, w, x);
    public float4 rbag { get => new float4(x, z, w, y); set { x = value.x; z = value.y; w = value.z; y = value.w; } }
    public float4 rbab => new float4(x, z, w, z);
    public float4 rbaa => new float4(x, z, w, w);
    public float4 rarr => new float4(x, w, x, x);
    public float4 rarg => new float4(x, w, x, y);
    public float4 rarb => new float4(x, w, x, z);
    public float4 rara => new float4(x, w, x, w);
    public float4 ragr => new float4(x, w, y, x);
    public float4 ragg => new float4(x, w, y, y);
    public float4 ragb { get => new float4(x, w, y, z); set { x = value.x; w = value.y; y = value.z; z = value.w; } }
    public float4 raga => new float4(x, w, y, w);
    public float4 rabr => new float4(x, w, z, x);
    public float4 rabg { get => new float4(x, w, z, y); set { x = value.x; w = value.y; z = value.z; y = value.w; } }
    public float4 rabb => new float4(x, w, z, z);
    public float4 raba => new float4(x, w, z, w);
    public float4 raar => new float4(x, w, w, x);
    public float4 raag => new float4(x, w, w, y);
    public float4 raab => new float4(x, w, w, z);
    public float4 raaa => new float4(x, w, w, w);
    public float4 grrr => new float4(y, x, x, x);
    public float4 grrg => new float4(y, x, x, y);
    public float4 grrb => new float4(y, x, x, z);
    public float4 grra => new float4(y, x, x, w);
    public float4 grgr => new float4(y, x, y, x);
    public float4 grgg => new float4(y, x, y, y);
    public float4 grgb => new float4(y, x, y, z);
    public float4 grga => new float4(y, x, y, w);
    public float4 grbr => new float4(y, x, z, x);
    public float4 grbg => new float4(y, x, z, y);
    public float4 grbb => new float4(y, x, z, z);
    public float4 grba { get => new float4(y, x, z, w); set { y = value.x; x = value.y; z = value.z; w = value.w; } }
    public float4 grar => new float4(y, x, w, x);
    public float4 grag => new float4(y, x, w, y);
    public float4 grab { get => new float4(y, x, w, z); set { y = value.x; x = value.y; w = value.z; z = value.w; } }
    public float4 graa => new float4(y, x, w, w);
    public float4 ggrr => new float4(y, y, x, x);
    public float4 ggrg => new float4(y, y, x, y);
    public float4 ggrb => new float4(y, y, x, z);
    public float4 ggra => new float4(y, y, x, w);
    public float4 gggr => new float4(y, y, y, x);
    public float4 gggg => new float4(y, y, y, y);
    public float4 gggb => new float4(y, y, y, z);
    public float4 ggga => new float4(y, y, y, w);
    public float4 ggbr => new float4(y, y, z, x);
    public float4 ggbg => new float4(y, y, z, y);
    public float4 ggbb => new float4(y, y, z, z);
    public float4 ggba => new float4(y, y, z, w);
    public float4 ggar => new float4(y, y, w, x);
    public float4 ggag => new float4(y, y, w, y);
    public float4 ggab => new float4(y, y, w, z);
    public float4 ggaa => new float4(y, y, w, w);
    public float4 gbrr => new float4(y, z, x, x);
    public float4 gbrg => new float4(y, z, x, y);
    public float4 gbrb => new float4(y, z, x, z);
    public float4 gbra { get => new float4(y, z, x, w); set { y = value.x; z = value.y; x = value.z; w = value.w; } }
    public float4 gbgr => new float4(y, z, y, x);
    public float4 gbgg => new float4(y, z, y, y);
    public float4 gbgb => new float4(y, z, y, z);
    public float4 gbga => new float4(y, z, y, w);
    public float4 gbbr => new float4(y, z, z, x);
    public float4 gbbg => new float4(y, z, z, y);
    public float4 gbbb => new float4(y, z, z, z);
    public float4 gbba => new float4(y, z, z, w);
    public float4 gbar { get => new float4(y, z, w, x); set { y = value.x; z = value.y; w = value.z; x = value.w; } }
    public float4 gbag => new float4(y, z, w, y);
    public float4 gbab => new float4(y, z, w, z);
    public float4 gbaa => new float4(y, z, w, w);
    public float4 garr => new float4(y, w, x, x);
    public float4 garg => new float4(y, w, x, y);
    public float4 garb { get => new float4(y, w, x, z); set { y = value.x; w = value.y; x = value.z; z = value.w; } }
    public float4 gara => new float4(y, w, x, w);
    public float4 gagr => new float4(y, w, y, x);
    public float4 gagg => new float4(y, w, y, y);
    public float4 gagb => new float4(y, w, y, z);
    public float4 gaga => new float4(y, w, y, w);
    public float4 gabr { get => new float4(y, w, z, x); set { y = value.x; w = value.y; z = value.z; x = value.w; } }
    public float4 gabg => new float4(y, w, z, y);
    public float4 gabb => new float4(y, w, z, z);
    public float4 gaba => new float4(y, w, z, w);
    public float4 gaar => new float4(y, w, w, x);
    public float4 gaag => new float4(y, w, w, y);
    public float4 gaab => new float4(y, w, w, z);
    public float4 gaaa => new float4(y, w, w, w);
    public float4 brrr => new float4(z, x, x, x);
    public float4 brrg => new float4(z, x, x, y);
    public float4 brrb => new float4(z, x, x, z);
    public float4 brra => new float4(z, x, x, w);
    public float4 brgr => new float4(z, x, y, x);
    public float4 brgg => new float4(z, x, y, y);
    public float4 brgb => new float4(z, x, y, z);
    public float4 brga { get => new float4(z, x, y, w); set { z = value.x; x = value.y; y = value.z; w = value.w; } }
    public float4 brbr => new float4(z, x, z, x);
    public float4 brbg => new float4(z, x, z, y);
    public float4 brbb => new float4(z, x, z, z);
    public float4 brba => new float4(z, x, z, w);
    public float4 brar => new float4(z, x, w, x);
    public float4 brag { get => new float4(z, x, w, y); set { z = value.x; x = value.y; w = value.z; y = value.w; } }
    public float4 brab => new float4(z, x, w, z);
    public float4 braa => new float4(z, x, w, w);
    public float4 bgrr => new float4(z, y, x, x);
    public float4 bgrg => new float4(z, y, x, y);
    public float4 bgrb => new float4(z, y, x, z);
    public float4 bgra { get => new float4(z, y, x, w); set { z = value.x; y = value.y; x = value.z; w = value.w; } }
    public float4 bggr => new float4(z, y, y, x);
    public float4 bggg => new float4(z, y, y, y);
    public float4 bggb => new float4(z, y, y, z);
    public float4 bgga => new float4(z, y, y, w);
    public float4 bgbr => new float4(z, y, z, x);
    public float4 bgbg => new float4(z, y, z, y);
    public float4 bgbb => new float4(z, y, z, z);
    public float4 bgba => new float4(z, y, z, w);
    public float4 bgar { get => new float4(z, y, w, x); set { z = value.x; y = value.y; w = value.z; x = value.w; } }
    public float4 bgag => new float4(z, y, w, y);
    public float4 bgab => new float4(z, y, w, z);
    public float4 bgaa => new float4(z, y, w, w);
    public float4 bbrr => new float4(z, z, x, x);
    public float4 bbrg => new float4(z, z, x, y);
    public float4 bbrb => new float4(z, z, x, z);
    public float4 bbra => new float4(z, z, x, w);
    public float4 bbgr => new float4(z, z, y, x);
    public float4 bbgg => new float4(z, z, y, y);
    public float4 bbgb => new float4(z, z, y, z);
    public float4 bbga => new float4(z, z, y, w);
    public float4 bbbr => new float4(z, z, z, x);
    public float4 bbbg => new float4(z, z, z, y);
    public float4 bbbb => new float4(z, z, z, z);
    public float4 bbba => new float4(z, z, z, w);
    public float4 bbar => new float4(z, z, w, x);
    public float4 bbag => new float4(z, z, w, y);
    public float4 bbab => new float4(z, z, w, z);
    public float4 bbaa => new float4(z, z, w, w);
    public float4 barr => new float4(z, w, x, x);
    public float4 barg { get => new float4(z, w, x, y); set { z = value.x; w = value.y; x = value.z; y = value.w; } }
    public float4 barb => new float4(z, w, x, z);
    public float4 bara => new float4(z, w, x, w);
    public float4 bagr { get => new float4(z, w, y, x); set { z = value.x; w = value.y; y = value.z; x = value.w; } }
    public float4 bagg => new float4(z, w, y, y);
    public float4 bagb => new float4(z, w, y, z);
    public float4 baga => new float4(z, w, y, w);
    public float4 babr => new float4(z, w, z, x);
    public float4 babg => new float4(z, w, z, y);
    public float4 babb => new float4(z, w, z, z);
    public float4 baba => new float4(z, w, z, w);
    public float4 baar => new float4(z, w, w, x);
    public float4 baag => new float4(z, w, w, y);
    public float4 baab => new float4(z, w, w, z);
    public float4 baaa => new float4(z, w, w, w);
    public float4 arrr => new float4(w, x, x, x);
    public float4 arrg => new float4(w, x, x, y);
    public float4 arrb => new float4(w, x, x, z);
    public float4 arra => new float4(w, x, x, w);
    public float4 argr => new float4(w, x, y, x);
    public float4 argg => new float4(w, x, y, y);
    public float4 argb { get => new float4(w, x, y, z); set { w = value.x; x = value.y; y = value.z; z = value.w; } }
    public float4 arga => new float4(w, x, y, w);
    public float4 arbr => new float4(w, x, z, x);
    public float4 arbg { get => new float4(w, x, z, y); set { w = value.x; x = value.y; z = value.z; y = value.w; } }
    public float4 arbb => new float4(w, x, z, z);
    public float4 arba => new float4(w, x, z, w);
    public float4 arar => new float4(w, x, w, x);
    public float4 arag => new float4(w, x, w, y);
    public float4 arab => new float4(w, x, w, z);
    public float4 araa => new float4(w, x, w, w);
    public float4 agrr => new float4(w, y, x, x);
    public float4 agrg => new float4(w, y, x, y);
    public float4 agrb { get => new float4(w, y, x, z); set { w = value.x; y = value.y; x = value.z; z = value.w; } }
    public float4 agra => new float4(w, y, x, w);
    public float4 aggr => new float4(w, y, y, x);
    public float4 aggg => new float4(w, y, y, y);
    public float4 aggb => new float4(w, y, y, z);
    public float4 agga => new float4(w, y, y, w);
    public float4 agbr { get => new float4(w, y, z, x); set { w = value.x; y = value.y; z = value.z; x = value.w; } }
    public float4 agbg => new float4(w, y, z, y);
    public float4 agbb => new float4(w, y, z, z);
    public float4 agba => new float4(w, y, z, w);
    public float4 agar => new float4(w, y, w, x);
    public float4 agag => new float4(w, y, w, y);
    public float4 agab => new float4(w, y, w, z);
    public float4 agaa => new float4(w, y, w, w);
    public float4 abrr => new float4(w, z, x, x);
    public float4 abrg { get => new float4(w, z, x, y); set { w = value.x; z = value.y; x = value.z; y = value.w; } }
    public float4 abrb => new float4(w, z, x, z);
    public float4 abra => new float4(w, z, x, w);
    public float4 abgr { get => new float4(w, z, y, x); set { w = value.x; z = value.y; y = value.z; x = value.w; } }
    public float4 abgg => new float4(w, z, y, y);
    public float4 abgb => new float4(w, z, y, z);
    public float4 abga => new float4(w, z, y, w);
    public float4 abbr => new float4(w, z, z, x);
    public float4 abbg => new float4(w, z, z, y);
    public float4 abbb => new float4(w, z, z, z);
    public float4 abba => new float4(w, z, z, w);
    public float4 abar => new float4(w, z, w, x);
    public float4 abag => new float4(w, z, w, y);
    public float4 abab => new float4(w, z, w, z);
    public float4 abaa => new float4(w, z, w, w);
    public float4 aarr => new float4(w, w, x, x);
    public float4 aarg => new float4(w, w, x, y);
    public float4 aarb => new float4(w, w, x, z);
    public float4 aara => new float4(w, w, x, w);
    public float4 aagr => new float4(w, w, y, x);
    public float4 aagg => new float4(w, w, y, y);
    public float4 aagb => new float4(w, w, y, z);
    public float4 aaga => new float4(w, w, y, w);
    public float4 aabr => new float4(w, w, z, x);
    public float4 aabg => new float4(w, w, z, y);
    public float4 aabb => new float4(w, w, z, z);
    public float4 aaba => new float4(w, w, z, w);
    public float4 aaar => new float4(w, w, w, x);
    public float4 aaag => new float4(w, w, w, y);
    public float4 aaab => new float4(w, w, w, z);
    public float4 aaaa => new float4(w, w, w, w);
}
