// <auto-generated>
// Written by tools/gen_hlsl_types.py. Do not edit; edit the script and run it again.
// </auto-generated>
#nullable enable
#pragma warning disable IDE1006, CS1591
using System;
using System.Runtime.InteropServices;

namespace Csl.Hlsl;

/// <summary>HLSL float2: 2 components of float. Runs on the GPU; the C# operations exist so shader code type-checks and can be unit tested.</summary>
[StructLayout(LayoutKind.Sequential)]
public struct float2 : IEquatable<float2>
{
    public float x, y;
    public float2(float x, float y) { this.x = x; this.y = y; }
    public float2(float v) { x = v; y = v; }
    public float2(int2 v) { x = (float)v.x; y = (float)v.y; }
    public static implicit operator float2(int2 v) => new float2(v);
    public float2(uint2 v) { x = (float)v.x; y = (float)v.y; }
    public static implicit operator float2(uint2 v) => new float2(v);
    public static implicit operator float2(float v) => new float2(v);
    public float this[int i]
    {
        get => i switch { 0 => x, 1 => y, _ => throw new IndexOutOfRangeException() };
        set { switch (i) { case 0: x = value; break; case 1: y = value; break; default: throw new IndexOutOfRangeException(); } }
    }
    public static float2 operator +(float2 a, float2 b) => new float2((float)(a.x + b.x), (float)(a.y + b.y));
    public static float2 operator +(float2 a, float b) => new float2((float)(a.x + b), (float)(a.y + b));
    public static float2 operator +(float a, float2 b) => new float2((float)(a + b.x), (float)(a + b.y));
    public static float2 operator -(float2 a, float2 b) => new float2((float)(a.x - b.x), (float)(a.y - b.y));
    public static float2 operator -(float2 a, float b) => new float2((float)(a.x - b), (float)(a.y - b));
    public static float2 operator -(float a, float2 b) => new float2((float)(a - b.x), (float)(a - b.y));
    public static float2 operator *(float2 a, float2 b) => new float2((float)(a.x * b.x), (float)(a.y * b.y));
    public static float2 operator *(float2 a, float b) => new float2((float)(a.x * b), (float)(a.y * b));
    public static float2 operator *(float a, float2 b) => new float2((float)(a * b.x), (float)(a * b.y));
    public static float2 operator /(float2 a, float2 b) => new float2((float)(a.x / b.x), (float)(a.y / b.y));
    public static float2 operator /(float2 a, float b) => new float2((float)(a.x / b), (float)(a.y / b));
    public static float2 operator /(float a, float2 b) => new float2((float)(a / b.x), (float)(a / b.y));
    public static float2 operator %(float2 a, float2 b) => new float2((float)(a.x % b.x), (float)(a.y % b.y));
    public static float2 operator %(float2 a, float b) => new float2((float)(a.x % b), (float)(a.y % b));
    public static float2 operator %(float a, float2 b) => new float2((float)(a % b.x), (float)(a % b.y));
    public static float2 operator -(float2 a) => new float2((float)(-a.x), (float)(-a.y));
    public static float2 operator +(float2 a) => a;
    public static float2 operator ++(float2 a) => new float2((float)(a.x + 1f), (float)(a.y + 1f));
    public static float2 operator --(float2 a) => new float2((float)(a.x - 1f), (float)(a.y - 1f));
    public static bool2 operator <(float2 a, float2 b) => new bool2(a.x < b.x, a.y < b.y);
    public static bool2 operator <(float2 a, float b) => new bool2(a.x < b, a.y < b);
    public static bool2 operator <(float a, float2 b) => new bool2(a < b.x, a < b.y);
    public static bool2 operator >(float2 a, float2 b) => new bool2(a.x > b.x, a.y > b.y);
    public static bool2 operator >(float2 a, float b) => new bool2(a.x > b, a.y > b);
    public static bool2 operator >(float a, float2 b) => new bool2(a > b.x, a > b.y);
    public static bool2 operator <=(float2 a, float2 b) => new bool2(a.x <= b.x, a.y <= b.y);
    public static bool2 operator <=(float2 a, float b) => new bool2(a.x <= b, a.y <= b);
    public static bool2 operator <=(float a, float2 b) => new bool2(a <= b.x, a <= b.y);
    public static bool2 operator >=(float2 a, float2 b) => new bool2(a.x >= b.x, a.y >= b.y);
    public static bool2 operator >=(float2 a, float b) => new bool2(a.x >= b, a.y >= b);
    public static bool2 operator >=(float a, float2 b) => new bool2(a >= b.x, a >= b.y);
    public static bool2 operator ==(float2 a, float2 b) => new bool2(a.x == b.x, a.y == b.y);
    public static bool2 operator !=(float2 a, float2 b) => new bool2(a.x != b.x, a.y != b.y);
    public static bool2 operator ==(float2 a, float b) => new bool2(a.x == b, a.y == b);
    public static bool2 operator !=(float2 a, float b) => new bool2(a.x != b, a.y != b);
    public bool Equals(float2 other) => x == other.x && y == other.y;
    public override bool Equals(object? obj) => obj is float2 other && Equals(other);
    public override int GetHashCode() => HashCode.Combine(x, y);
    public override string ToString() => $"float2({x}, {y})";

    // Swizzles, xyzw and rgba. Setters only where no component repeats.
    public float2 xx => new float2(x, x);
    public float2 xy { get => new float2(x, y); set { x = value.x; y = value.y; } }
    public float2 yx { get => new float2(y, x); set { y = value.x; x = value.y; } }
    public float2 yy => new float2(y, y);
    public float3 xxx => new float3(x, x, x);
    public float3 xxy => new float3(x, x, y);
    public float3 xyx => new float3(x, y, x);
    public float3 xyy => new float3(x, y, y);
    public float3 yxx => new float3(y, x, x);
    public float3 yxy => new float3(y, x, y);
    public float3 yyx => new float3(y, y, x);
    public float3 yyy => new float3(y, y, y);
    public float4 xxxx => new float4(x, x, x, x);
    public float4 xxxy => new float4(x, x, x, y);
    public float4 xxyx => new float4(x, x, y, x);
    public float4 xxyy => new float4(x, x, y, y);
    public float4 xyxx => new float4(x, y, x, x);
    public float4 xyxy => new float4(x, y, x, y);
    public float4 xyyx => new float4(x, y, y, x);
    public float4 xyyy => new float4(x, y, y, y);
    public float4 yxxx => new float4(y, x, x, x);
    public float4 yxxy => new float4(y, x, x, y);
    public float4 yxyx => new float4(y, x, y, x);
    public float4 yxyy => new float4(y, x, y, y);
    public float4 yyxx => new float4(y, y, x, x);
    public float4 yyxy => new float4(y, y, x, y);
    public float4 yyyx => new float4(y, y, y, x);
    public float4 yyyy => new float4(y, y, y, y);
    public float r { get => x; set => x = value; }
    public float g { get => y; set => y = value; }
    public float2 rr => new float2(x, x);
    public float2 rg { get => new float2(x, y); set { x = value.x; y = value.y; } }
    public float2 gr { get => new float2(y, x); set { y = value.x; x = value.y; } }
    public float2 gg => new float2(y, y);
    public float3 rrr => new float3(x, x, x);
    public float3 rrg => new float3(x, x, y);
    public float3 rgr => new float3(x, y, x);
    public float3 rgg => new float3(x, y, y);
    public float3 grr => new float3(y, x, x);
    public float3 grg => new float3(y, x, y);
    public float3 ggr => new float3(y, y, x);
    public float3 ggg => new float3(y, y, y);
    public float4 rrrr => new float4(x, x, x, x);
    public float4 rrrg => new float4(x, x, x, y);
    public float4 rrgr => new float4(x, x, y, x);
    public float4 rrgg => new float4(x, x, y, y);
    public float4 rgrr => new float4(x, y, x, x);
    public float4 rgrg => new float4(x, y, x, y);
    public float4 rggr => new float4(x, y, y, x);
    public float4 rggg => new float4(x, y, y, y);
    public float4 grrr => new float4(y, x, x, x);
    public float4 grrg => new float4(y, x, x, y);
    public float4 grgr => new float4(y, x, y, x);
    public float4 grgg => new float4(y, x, y, y);
    public float4 ggrr => new float4(y, y, x, x);
    public float4 ggrg => new float4(y, y, x, y);
    public float4 gggr => new float4(y, y, y, x);
    public float4 gggg => new float4(y, y, y, y);
}
