// <auto-generated>
// Written by tools/gen_hlsl_types.py. Do not edit; edit the script and run it again.
// </auto-generated>
#nullable enable
#pragma warning disable IDE1006, CS1591
using System;
using System.Runtime.InteropServices;

namespace Csl.Hlsl;

/// <summary>HLSL float3: 3 components of float. Runs on the GPU; the C# operations exist so shader code type-checks and can be unit tested.</summary>
[StructLayout(LayoutKind.Sequential)]
public struct float3 : IEquatable<float3>
{
    public float x, y, z;
    public float3(float x, float y, float z) { this.x = x; this.y = y; this.z = z; }
    public float3(float v) { x = v; y = v; z = v; }
    public float3(float2 xy, float z) { x = xy.x; y = xy.y; this.z = z; }
    public float3(float x, float2 yz) { this.x = x; y = yz.x; z = yz.y; }
    public float3(int3 v) { x = (float)v.x; y = (float)v.y; z = (float)v.z; }
    public static implicit operator float3(int3 v) => new float3(v);
    public float3(uint3 v) { x = (float)v.x; y = (float)v.y; z = (float)v.z; }
    public static implicit operator float3(uint3 v) => new float3(v);
    public static implicit operator float3(float v) => new float3(v);
    public float this[int i]
    {
        get => i switch { 0 => x, 1 => y, 2 => z, _ => throw new IndexOutOfRangeException() };
        set { switch (i) { case 0: x = value; break; case 1: y = value; break; case 2: z = value; break; default: throw new IndexOutOfRangeException(); } }
    }
    public static float3 operator +(float3 a, float3 b) => new float3((float)(a.x + b.x), (float)(a.y + b.y), (float)(a.z + b.z));
    public static float3 operator +(float3 a, float b) => new float3((float)(a.x + b), (float)(a.y + b), (float)(a.z + b));
    public static float3 operator +(float a, float3 b) => new float3((float)(a + b.x), (float)(a + b.y), (float)(a + b.z));
    public static float3 operator -(float3 a, float3 b) => new float3((float)(a.x - b.x), (float)(a.y - b.y), (float)(a.z - b.z));
    public static float3 operator -(float3 a, float b) => new float3((float)(a.x - b), (float)(a.y - b), (float)(a.z - b));
    public static float3 operator -(float a, float3 b) => new float3((float)(a - b.x), (float)(a - b.y), (float)(a - b.z));
    public static float3 operator *(float3 a, float3 b) => new float3((float)(a.x * b.x), (float)(a.y * b.y), (float)(a.z * b.z));
    public static float3 operator *(float3 a, float b) => new float3((float)(a.x * b), (float)(a.y * b), (float)(a.z * b));
    public static float3 operator *(float a, float3 b) => new float3((float)(a * b.x), (float)(a * b.y), (float)(a * b.z));
    public static float3 operator /(float3 a, float3 b) => new float3((float)(a.x / b.x), (float)(a.y / b.y), (float)(a.z / b.z));
    public static float3 operator /(float3 a, float b) => new float3((float)(a.x / b), (float)(a.y / b), (float)(a.z / b));
    public static float3 operator /(float a, float3 b) => new float3((float)(a / b.x), (float)(a / b.y), (float)(a / b.z));
    public static float3 operator %(float3 a, float3 b) => new float3((float)(a.x % b.x), (float)(a.y % b.y), (float)(a.z % b.z));
    public static float3 operator %(float3 a, float b) => new float3((float)(a.x % b), (float)(a.y % b), (float)(a.z % b));
    public static float3 operator %(float a, float3 b) => new float3((float)(a % b.x), (float)(a % b.y), (float)(a % b.z));
    public static float3 operator -(float3 a) => new float3((float)(-a.x), (float)(-a.y), (float)(-a.z));
    public static float3 operator +(float3 a) => a;
    public static float3 operator ++(float3 a) => new float3((float)(a.x + 1f), (float)(a.y + 1f), (float)(a.z + 1f));
    public static float3 operator --(float3 a) => new float3((float)(a.x - 1f), (float)(a.y - 1f), (float)(a.z - 1f));
    public static bool3 operator <(float3 a, float3 b) => new bool3(a.x < b.x, a.y < b.y, a.z < b.z);
    public static bool3 operator <(float3 a, float b) => new bool3(a.x < b, a.y < b, a.z < b);
    public static bool3 operator <(float a, float3 b) => new bool3(a < b.x, a < b.y, a < b.z);
    public static bool3 operator >(float3 a, float3 b) => new bool3(a.x > b.x, a.y > b.y, a.z > b.z);
    public static bool3 operator >(float3 a, float b) => new bool3(a.x > b, a.y > b, a.z > b);
    public static bool3 operator >(float a, float3 b) => new bool3(a > b.x, a > b.y, a > b.z);
    public static bool3 operator <=(float3 a, float3 b) => new bool3(a.x <= b.x, a.y <= b.y, a.z <= b.z);
    public static bool3 operator <=(float3 a, float b) => new bool3(a.x <= b, a.y <= b, a.z <= b);
    public static bool3 operator <=(float a, float3 b) => new bool3(a <= b.x, a <= b.y, a <= b.z);
    public static bool3 operator >=(float3 a, float3 b) => new bool3(a.x >= b.x, a.y >= b.y, a.z >= b.z);
    public static bool3 operator >=(float3 a, float b) => new bool3(a.x >= b, a.y >= b, a.z >= b);
    public static bool3 operator >=(float a, float3 b) => new bool3(a >= b.x, a >= b.y, a >= b.z);
    public static bool3 operator ==(float3 a, float3 b) => new bool3(a.x == b.x, a.y == b.y, a.z == b.z);
    public static bool3 operator !=(float3 a, float3 b) => new bool3(a.x != b.x, a.y != b.y, a.z != b.z);
    public static bool3 operator ==(float3 a, float b) => new bool3(a.x == b, a.y == b, a.z == b);
    public static bool3 operator !=(float3 a, float b) => new bool3(a.x != b, a.y != b, a.z != b);
    public bool Equals(float3 other) => x == other.x && y == other.y && z == other.z;
    public override bool Equals(object? obj) => obj is float3 other && Equals(other);
    public override int GetHashCode() => HashCode.Combine(x, y, z);
    public override string ToString() => $"float3({x}, {y}, {z})";

    // Swizzles, xyzw and rgba. Setters only where no component repeats.
    public float2 xx => new float2(x, x);
    public float2 xy { get => new float2(x, y); set { x = value.x; y = value.y; } }
    public float2 xz { get => new float2(x, z); set { x = value.x; z = value.y; } }
    public float2 yx { get => new float2(y, x); set { y = value.x; x = value.y; } }
    public float2 yy => new float2(y, y);
    public float2 yz { get => new float2(y, z); set { y = value.x; z = value.y; } }
    public float2 zx { get => new float2(z, x); set { z = value.x; x = value.y; } }
    public float2 zy { get => new float2(z, y); set { z = value.x; y = value.y; } }
    public float2 zz => new float2(z, z);
    public float3 xxx => new float3(x, x, x);
    public float3 xxy => new float3(x, x, y);
    public float3 xxz => new float3(x, x, z);
    public float3 xyx => new float3(x, y, x);
    public float3 xyy => new float3(x, y, y);
    public float3 xyz { get => new float3(x, y, z); set { x = value.x; y = value.y; z = value.z; } }
    public float3 xzx => new float3(x, z, x);
    public float3 xzy { get => new float3(x, z, y); set { x = value.x; z = value.y; y = value.z; } }
    public float3 xzz => new float3(x, z, z);
    public float3 yxx => new float3(y, x, x);
    public float3 yxy => new float3(y, x, y);
    public float3 yxz { get => new float3(y, x, z); set { y = value.x; x = value.y; z = value.z; } }
    public float3 yyx => new float3(y, y, x);
    public float3 yyy => new float3(y, y, y);
    public float3 yyz => new float3(y, y, z);
    public float3 yzx { get => new float3(y, z, x); set { y = value.x; z = value.y; x = value.z; } }
    public float3 yzy => new float3(y, z, y);
    public float3 yzz => new float3(y, z, z);
    public float3 zxx => new float3(z, x, x);
    public float3 zxy { get => new float3(z, x, y); set { z = value.x; x = value.y; y = value.z; } }
    public float3 zxz => new float3(z, x, z);
    public float3 zyx { get => new float3(z, y, x); set { z = value.x; y = value.y; x = value.z; } }
    public float3 zyy => new float3(z, y, y);
    public float3 zyz => new float3(z, y, z);
    public float3 zzx => new float3(z, z, x);
    public float3 zzy => new float3(z, z, y);
    public float3 zzz => new float3(z, z, z);
    public float4 xxxx => new float4(x, x, x, x);
    public float4 xxxy => new float4(x, x, x, y);
    public float4 xxxz => new float4(x, x, x, z);
    public float4 xxyx => new float4(x, x, y, x);
    public float4 xxyy => new float4(x, x, y, y);
    public float4 xxyz => new float4(x, x, y, z);
    public float4 xxzx => new float4(x, x, z, x);
    public float4 xxzy => new float4(x, x, z, y);
    public float4 xxzz => new float4(x, x, z, z);
    public float4 xyxx => new float4(x, y, x, x);
    public float4 xyxy => new float4(x, y, x, y);
    public float4 xyxz => new float4(x, y, x, z);
    public float4 xyyx => new float4(x, y, y, x);
    public float4 xyyy => new float4(x, y, y, y);
    public float4 xyyz => new float4(x, y, y, z);
    public float4 xyzx => new float4(x, y, z, x);
    public float4 xyzy => new float4(x, y, z, y);
    public float4 xyzz => new float4(x, y, z, z);
    public float4 xzxx => new float4(x, z, x, x);
    public float4 xzxy => new float4(x, z, x, y);
    public float4 xzxz => new float4(x, z, x, z);
    public float4 xzyx => new float4(x, z, y, x);
    public float4 xzyy => new float4(x, z, y, y);
    public float4 xzyz => new float4(x, z, y, z);
    public float4 xzzx => new float4(x, z, z, x);
    public float4 xzzy => new float4(x, z, z, y);
    public float4 xzzz => new float4(x, z, z, z);
    public float4 yxxx => new float4(y, x, x, x);
    public float4 yxxy => new float4(y, x, x, y);
    public float4 yxxz => new float4(y, x, x, z);
    public float4 yxyx => new float4(y, x, y, x);
    public float4 yxyy => new float4(y, x, y, y);
    public float4 yxyz => new float4(y, x, y, z);
    public float4 yxzx => new float4(y, x, z, x);
    public float4 yxzy => new float4(y, x, z, y);
    public float4 yxzz => new float4(y, x, z, z);
    public float4 yyxx => new float4(y, y, x, x);
    public float4 yyxy => new float4(y, y, x, y);
    public float4 yyxz => new float4(y, y, x, z);
    public float4 yyyx => new float4(y, y, y, x);
    public float4 yyyy => new float4(y, y, y, y);
    public float4 yyyz => new float4(y, y, y, z);
    public float4 yyzx => new float4(y, y, z, x);
    public float4 yyzy => new float4(y, y, z, y);
    public float4 yyzz => new float4(y, y, z, z);
    public float4 yzxx => new float4(y, z, x, x);
    public float4 yzxy => new float4(y, z, x, y);
    public float4 yzxz => new float4(y, z, x, z);
    public float4 yzyx => new float4(y, z, y, x);
    public float4 yzyy => new float4(y, z, y, y);
    public float4 yzyz => new float4(y, z, y, z);
    public float4 yzzx => new float4(y, z, z, x);
    public float4 yzzy => new float4(y, z, z, y);
    public float4 yzzz => new float4(y, z, z, z);
    public float4 zxxx => new float4(z, x, x, x);
    public float4 zxxy => new float4(z, x, x, y);
    public float4 zxxz => new float4(z, x, x, z);
    public float4 zxyx => new float4(z, x, y, x);
    public float4 zxyy => new float4(z, x, y, y);
    public float4 zxyz => new float4(z, x, y, z);
    public float4 zxzx => new float4(z, x, z, x);
    public float4 zxzy => new float4(z, x, z, y);
    public float4 zxzz => new float4(z, x, z, z);
    public float4 zyxx => new float4(z, y, x, x);
    public float4 zyxy => new float4(z, y, x, y);
    public float4 zyxz => new float4(z, y, x, z);
    public float4 zyyx => new float4(z, y, y, x);
    public float4 zyyy => new float4(z, y, y, y);
    public float4 zyyz => new float4(z, y, y, z);
    public float4 zyzx => new float4(z, y, z, x);
    public float4 zyzy => new float4(z, y, z, y);
    public float4 zyzz => new float4(z, y, z, z);
    public float4 zzxx => new float4(z, z, x, x);
    public float4 zzxy => new float4(z, z, x, y);
    public float4 zzxz => new float4(z, z, x, z);
    public float4 zzyx => new float4(z, z, y, x);
    public float4 zzyy => new float4(z, z, y, y);
    public float4 zzyz => new float4(z, z, y, z);
    public float4 zzzx => new float4(z, z, z, x);
    public float4 zzzy => new float4(z, z, z, y);
    public float4 zzzz => new float4(z, z, z, z);
    public float r { get => x; set => x = value; }
    public float g { get => y; set => y = value; }
    public float b { get => z; set => z = value; }
    public float2 rr => new float2(x, x);
    public float2 rg { get => new float2(x, y); set { x = value.x; y = value.y; } }
    public float2 rb { get => new float2(x, z); set { x = value.x; z = value.y; } }
    public float2 gr { get => new float2(y, x); set { y = value.x; x = value.y; } }
    public float2 gg => new float2(y, y);
    public float2 gb { get => new float2(y, z); set { y = value.x; z = value.y; } }
    public float2 br { get => new float2(z, x); set { z = value.x; x = value.y; } }
    public float2 bg { get => new float2(z, y); set { z = value.x; y = value.y; } }
    public float2 bb => new float2(z, z);
    public float3 rrr => new float3(x, x, x);
    public float3 rrg => new float3(x, x, y);
    public float3 rrb => new float3(x, x, z);
    public float3 rgr => new float3(x, y, x);
    public float3 rgg => new float3(x, y, y);
    public float3 rgb { get => new float3(x, y, z); set { x = value.x; y = value.y; z = value.z; } }
    public float3 rbr => new float3(x, z, x);
    public float3 rbg { get => new float3(x, z, y); set { x = value.x; z = value.y; y = value.z; } }
    public float3 rbb => new float3(x, z, z);
    public float3 grr => new float3(y, x, x);
    public float3 grg => new float3(y, x, y);
    public float3 grb { get => new float3(y, x, z); set { y = value.x; x = value.y; z = value.z; } }
    public float3 ggr => new float3(y, y, x);
    public float3 ggg => new float3(y, y, y);
    public float3 ggb => new float3(y, y, z);
    public float3 gbr { get => new float3(y, z, x); set { y = value.x; z = value.y; x = value.z; } }
    public float3 gbg => new float3(y, z, y);
    public float3 gbb => new float3(y, z, z);
    public float3 brr => new float3(z, x, x);
    public float3 brg { get => new float3(z, x, y); set { z = value.x; x = value.y; y = value.z; } }
    public float3 brb => new float3(z, x, z);
    public float3 bgr { get => new float3(z, y, x); set { z = value.x; y = value.y; x = value.z; } }
    public float3 bgg => new float3(z, y, y);
    public float3 bgb => new float3(z, y, z);
    public float3 bbr => new float3(z, z, x);
    public float3 bbg => new float3(z, z, y);
    public float3 bbb => new float3(z, z, z);
    public float4 rrrr => new float4(x, x, x, x);
    public float4 rrrg => new float4(x, x, x, y);
    public float4 rrrb => new float4(x, x, x, z);
    public float4 rrgr => new float4(x, x, y, x);
    public float4 rrgg => new float4(x, x, y, y);
    public float4 rrgb => new float4(x, x, y, z);
    public float4 rrbr => new float4(x, x, z, x);
    public float4 rrbg => new float4(x, x, z, y);
    public float4 rrbb => new float4(x, x, z, z);
    public float4 rgrr => new float4(x, y, x, x);
    public float4 rgrg => new float4(x, y, x, y);
    public float4 rgrb => new float4(x, y, x, z);
    public float4 rggr => new float4(x, y, y, x);
    public float4 rggg => new float4(x, y, y, y);
    public float4 rggb => new float4(x, y, y, z);
    public float4 rgbr => new float4(x, y, z, x);
    public float4 rgbg => new float4(x, y, z, y);
    public float4 rgbb => new float4(x, y, z, z);
    public float4 rbrr => new float4(x, z, x, x);
    public float4 rbrg => new float4(x, z, x, y);
    public float4 rbrb => new float4(x, z, x, z);
    public float4 rbgr => new float4(x, z, y, x);
    public float4 rbgg => new float4(x, z, y, y);
    public float4 rbgb => new float4(x, z, y, z);
    public float4 rbbr => new float4(x, z, z, x);
    public float4 rbbg => new float4(x, z, z, y);
    public float4 rbbb => new float4(x, z, z, z);
    public float4 grrr => new float4(y, x, x, x);
    public float4 grrg => new float4(y, x, x, y);
    public float4 grrb => new float4(y, x, x, z);
    public float4 grgr => new float4(y, x, y, x);
    public float4 grgg => new float4(y, x, y, y);
    public float4 grgb => new float4(y, x, y, z);
    public float4 grbr => new float4(y, x, z, x);
    public float4 grbg => new float4(y, x, z, y);
    public float4 grbb => new float4(y, x, z, z);
    public float4 ggrr => new float4(y, y, x, x);
    public float4 ggrg => new float4(y, y, x, y);
    public float4 ggrb => new float4(y, y, x, z);
    public float4 gggr => new float4(y, y, y, x);
    public float4 gggg => new float4(y, y, y, y);
    public float4 gggb => new float4(y, y, y, z);
    public float4 ggbr => new float4(y, y, z, x);
    public float4 ggbg => new float4(y, y, z, y);
    public float4 ggbb => new float4(y, y, z, z);
    public float4 gbrr => new float4(y, z, x, x);
    public float4 gbrg => new float4(y, z, x, y);
    public float4 gbrb => new float4(y, z, x, z);
    public float4 gbgr => new float4(y, z, y, x);
    public float4 gbgg => new float4(y, z, y, y);
    public float4 gbgb => new float4(y, z, y, z);
    public float4 gbbr => new float4(y, z, z, x);
    public float4 gbbg => new float4(y, z, z, y);
    public float4 gbbb => new float4(y, z, z, z);
    public float4 brrr => new float4(z, x, x, x);
    public float4 brrg => new float4(z, x, x, y);
    public float4 brrb => new float4(z, x, x, z);
    public float4 brgr => new float4(z, x, y, x);
    public float4 brgg => new float4(z, x, y, y);
    public float4 brgb => new float4(z, x, y, z);
    public float4 brbr => new float4(z, x, z, x);
    public float4 brbg => new float4(z, x, z, y);
    public float4 brbb => new float4(z, x, z, z);
    public float4 bgrr => new float4(z, y, x, x);
    public float4 bgrg => new float4(z, y, x, y);
    public float4 bgrb => new float4(z, y, x, z);
    public float4 bggr => new float4(z, y, y, x);
    public float4 bggg => new float4(z, y, y, y);
    public float4 bggb => new float4(z, y, y, z);
    public float4 bgbr => new float4(z, y, z, x);
    public float4 bgbg => new float4(z, y, z, y);
    public float4 bgbb => new float4(z, y, z, z);
    public float4 bbrr => new float4(z, z, x, x);
    public float4 bbrg => new float4(z, z, x, y);
    public float4 bbrb => new float4(z, z, x, z);
    public float4 bbgr => new float4(z, z, y, x);
    public float4 bbgg => new float4(z, z, y, y);
    public float4 bbgb => new float4(z, z, y, z);
    public float4 bbbr => new float4(z, z, z, x);
    public float4 bbbg => new float4(z, z, z, y);
    public float4 bbbb => new float4(z, z, z, z);
}
