// <auto-generated>
// Written by tools/gen_hlsl_types.py. Do not edit; edit the script and run it again.
// </auto-generated>
#nullable enable
#pragma warning disable IDE1006, CS1591
using System;
using System.Runtime.InteropServices;

namespace Csl.Hlsl;

/// <summary>HLSL int2: 2 components of int. Runs on the GPU; the C# operations exist so shader code type-checks and can be unit tested.</summary>
[StructLayout(LayoutKind.Sequential)]
public struct int2 : IEquatable<int2>
{
    public int x, y;
    public int2(int x, int y) { this.x = x; this.y = y; }
    public int2(int v) { x = v; y = v; }
    public int2(float2 v) { x = (int)v.x; y = (int)v.y; }
    public static explicit operator int2(float2 v) => new int2(v);
    public int2(uint2 v) { x = (int)v.x; y = (int)v.y; }
    public static explicit operator int2(uint2 v) => new int2(v);
    public static implicit operator int2(int v) => new int2(v);
    public int this[int i]
    {
        get => i switch { 0 => x, 1 => y, _ => throw new IndexOutOfRangeException() };
        set { switch (i) { case 0: x = value; break; case 1: y = value; break; default: throw new IndexOutOfRangeException(); } }
    }
    public static int2 operator +(int2 a, int2 b) => new int2((int)(a.x + b.x), (int)(a.y + b.y));
    public static int2 operator +(int2 a, int b) => new int2((int)(a.x + b), (int)(a.y + b));
    public static int2 operator +(int a, int2 b) => new int2((int)(a + b.x), (int)(a + b.y));
    public static int2 operator -(int2 a, int2 b) => new int2((int)(a.x - b.x), (int)(a.y - b.y));
    public static int2 operator -(int2 a, int b) => new int2((int)(a.x - b), (int)(a.y - b));
    public static int2 operator -(int a, int2 b) => new int2((int)(a - b.x), (int)(a - b.y));
    public static int2 operator *(int2 a, int2 b) => new int2((int)(a.x * b.x), (int)(a.y * b.y));
    public static int2 operator *(int2 a, int b) => new int2((int)(a.x * b), (int)(a.y * b));
    public static int2 operator *(int a, int2 b) => new int2((int)(a * b.x), (int)(a * b.y));
    public static int2 operator /(int2 a, int2 b) => new int2((int)(a.x / b.x), (int)(a.y / b.y));
    public static int2 operator /(int2 a, int b) => new int2((int)(a.x / b), (int)(a.y / b));
    public static int2 operator /(int a, int2 b) => new int2((int)(a / b.x), (int)(a / b.y));
    public static int2 operator %(int2 a, int2 b) => new int2((int)(a.x % b.x), (int)(a.y % b.y));
    public static int2 operator %(int2 a, int b) => new int2((int)(a.x % b), (int)(a.y % b));
    public static int2 operator %(int a, int2 b) => new int2((int)(a % b.x), (int)(a % b.y));
    public static int2 operator -(int2 a) => new int2((int)(-a.x), (int)(-a.y));
    public static int2 operator +(int2 a) => a;
    public static int2 operator ++(int2 a) => new int2((int)(a.x + 1), (int)(a.y + 1));
    public static int2 operator --(int2 a) => new int2((int)(a.x - 1), (int)(a.y - 1));
    public static bool2 operator <(int2 a, int2 b) => new bool2(a.x < b.x, a.y < b.y);
    public static bool2 operator <(int2 a, int b) => new bool2(a.x < b, a.y < b);
    public static bool2 operator <(int a, int2 b) => new bool2(a < b.x, a < b.y);
    public static bool2 operator >(int2 a, int2 b) => new bool2(a.x > b.x, a.y > b.y);
    public static bool2 operator >(int2 a, int b) => new bool2(a.x > b, a.y > b);
    public static bool2 operator >(int a, int2 b) => new bool2(a > b.x, a > b.y);
    public static bool2 operator <=(int2 a, int2 b) => new bool2(a.x <= b.x, a.y <= b.y);
    public static bool2 operator <=(int2 a, int b) => new bool2(a.x <= b, a.y <= b);
    public static bool2 operator <=(int a, int2 b) => new bool2(a <= b.x, a <= b.y);
    public static bool2 operator >=(int2 a, int2 b) => new bool2(a.x >= b.x, a.y >= b.y);
    public static bool2 operator >=(int2 a, int b) => new bool2(a.x >= b, a.y >= b);
    public static bool2 operator >=(int a, int2 b) => new bool2(a >= b.x, a >= b.y);
    public static int2 operator &(int2 a, int2 b) => new int2((int)(a.x & b.x), (int)(a.y & b.y));
    public static int2 operator &(int2 a, int b) => new int2((int)(a.x & b), (int)(a.y & b));
    public static int2 operator |(int2 a, int2 b) => new int2((int)(a.x | b.x), (int)(a.y | b.y));
    public static int2 operator |(int2 a, int b) => new int2((int)(a.x | b), (int)(a.y | b));
    public static int2 operator ^(int2 a, int2 b) => new int2((int)(a.x ^ b.x), (int)(a.y ^ b.y));
    public static int2 operator ^(int2 a, int b) => new int2((int)(a.x ^ b), (int)(a.y ^ b));
    public static int2 operator <<(int2 a, int b) => new int2((int)(a.x << b), (int)(a.y << b));
    public static int2 operator >>(int2 a, int b) => new int2((int)(a.x >> b), (int)(a.y >> b));
    public static int2 operator ~(int2 a) => new int2((int)(~a.x), (int)(~a.y));
    public static bool2 operator ==(int2 a, int2 b) => new bool2(a.x == b.x, a.y == b.y);
    public static bool2 operator !=(int2 a, int2 b) => new bool2(a.x != b.x, a.y != b.y);
    public static bool2 operator ==(int2 a, int b) => new bool2(a.x == b, a.y == b);
    public static bool2 operator !=(int2 a, int b) => new bool2(a.x != b, a.y != b);
    public bool Equals(int2 other) => x == other.x && y == other.y;
    public override bool Equals(object? obj) => obj is int2 other && Equals(other);
    public override int GetHashCode() => HashCode.Combine(x, y);
    public override string ToString() => $"int2({x}, {y})";

    // Swizzles, xyzw and rgba. Setters only where no component repeats.
    public int2 xx => new int2(x, x);
    public int2 xy { get => new int2(x, y); set { x = value.x; y = value.y; } }
    public int2 yx { get => new int2(y, x); set { y = value.x; x = value.y; } }
    public int2 yy => new int2(y, y);
    public int3 xxx => new int3(x, x, x);
    public int3 xxy => new int3(x, x, y);
    public int3 xyx => new int3(x, y, x);
    public int3 xyy => new int3(x, y, y);
    public int3 yxx => new int3(y, x, x);
    public int3 yxy => new int3(y, x, y);
    public int3 yyx => new int3(y, y, x);
    public int3 yyy => new int3(y, y, y);
    public int4 xxxx => new int4(x, x, x, x);
    public int4 xxxy => new int4(x, x, x, y);
    public int4 xxyx => new int4(x, x, y, x);
    public int4 xxyy => new int4(x, x, y, y);
    public int4 xyxx => new int4(x, y, x, x);
    public int4 xyxy => new int4(x, y, x, y);
    public int4 xyyx => new int4(x, y, y, x);
    public int4 xyyy => new int4(x, y, y, y);
    public int4 yxxx => new int4(y, x, x, x);
    public int4 yxxy => new int4(y, x, x, y);
    public int4 yxyx => new int4(y, x, y, x);
    public int4 yxyy => new int4(y, x, y, y);
    public int4 yyxx => new int4(y, y, x, x);
    public int4 yyxy => new int4(y, y, x, y);
    public int4 yyyx => new int4(y, y, y, x);
    public int4 yyyy => new int4(y, y, y, y);
    public int r { get => x; set => x = value; }
    public int g { get => y; set => y = value; }
    public int2 rr => new int2(x, x);
    public int2 rg { get => new int2(x, y); set { x = value.x; y = value.y; } }
    public int2 gr { get => new int2(y, x); set { y = value.x; x = value.y; } }
    public int2 gg => new int2(y, y);
    public int3 rrr => new int3(x, x, x);
    public int3 rrg => new int3(x, x, y);
    public int3 rgr => new int3(x, y, x);
    public int3 rgg => new int3(x, y, y);
    public int3 grr => new int3(y, x, x);
    public int3 grg => new int3(y, x, y);
    public int3 ggr => new int3(y, y, x);
    public int3 ggg => new int3(y, y, y);
    public int4 rrrr => new int4(x, x, x, x);
    public int4 rrrg => new int4(x, x, x, y);
    public int4 rrgr => new int4(x, x, y, x);
    public int4 rrgg => new int4(x, x, y, y);
    public int4 rgrr => new int4(x, y, x, x);
    public int4 rgrg => new int4(x, y, x, y);
    public int4 rggr => new int4(x, y, y, x);
    public int4 rggg => new int4(x, y, y, y);
    public int4 grrr => new int4(y, x, x, x);
    public int4 grrg => new int4(y, x, x, y);
    public int4 grgr => new int4(y, x, y, x);
    public int4 grgg => new int4(y, x, y, y);
    public int4 ggrr => new int4(y, y, x, x);
    public int4 ggrg => new int4(y, y, x, y);
    public int4 gggr => new int4(y, y, y, x);
    public int4 gggg => new int4(y, y, y, y);
}
