// <auto-generated>
// Written by tools/gen_hlsl_types.py. Do not edit; edit the script and run it again.
// </auto-generated>
#nullable enable
#pragma warning disable IDE1006, CS1591
using System;
using System.Runtime.InteropServices;

namespace Csl.Hlsl;

/// <summary>HLSL int3: 3 components of int. Runs on the GPU; the C# operations exist so shader code type-checks and can be unit tested.</summary>
[StructLayout(LayoutKind.Sequential)]
public struct int3 : IEquatable<int3>
{
    public int x, y, z;
    public int3(int x, int y, int z) { this.x = x; this.y = y; this.z = z; }
    public int3(int v) { x = v; y = v; z = v; }
    public int3(int2 xy, int z) { x = xy.x; y = xy.y; this.z = z; }
    public int3(int x, int2 yz) { this.x = x; y = yz.x; z = yz.y; }
    public int3(float3 v) { x = (int)v.x; y = (int)v.y; z = (int)v.z; }
    public static explicit operator int3(float3 v) => new int3(v);
    public int3(uint3 v) { x = (int)v.x; y = (int)v.y; z = (int)v.z; }
    public static explicit operator int3(uint3 v) => new int3(v);
    public static implicit operator int3(int v) => new int3(v);
    public int this[int i]
    {
        get => i switch { 0 => x, 1 => y, 2 => z, _ => throw new IndexOutOfRangeException() };
        set { switch (i) { case 0: x = value; break; case 1: y = value; break; case 2: z = value; break; default: throw new IndexOutOfRangeException(); } }
    }
    public static int3 operator +(int3 a, int3 b) => new int3((int)(a.x + b.x), (int)(a.y + b.y), (int)(a.z + b.z));
    public static int3 operator +(int3 a, int b) => new int3((int)(a.x + b), (int)(a.y + b), (int)(a.z + b));
    public static int3 operator +(int a, int3 b) => new int3((int)(a + b.x), (int)(a + b.y), (int)(a + b.z));
    public static int3 operator -(int3 a, int3 b) => new int3((int)(a.x - b.x), (int)(a.y - b.y), (int)(a.z - b.z));
    public static int3 operator -(int3 a, int b) => new int3((int)(a.x - b), (int)(a.y - b), (int)(a.z - b));
    public static int3 operator -(int a, int3 b) => new int3((int)(a - b.x), (int)(a - b.y), (int)(a - b.z));
    public static int3 operator *(int3 a, int3 b) => new int3((int)(a.x * b.x), (int)(a.y * b.y), (int)(a.z * b.z));
    public static int3 operator *(int3 a, int b) => new int3((int)(a.x * b), (int)(a.y * b), (int)(a.z * b));
    public static int3 operator *(int a, int3 b) => new int3((int)(a * b.x), (int)(a * b.y), (int)(a * b.z));
    public static int3 operator /(int3 a, int3 b) => new int3((int)(a.x / b.x), (int)(a.y / b.y), (int)(a.z / b.z));
    public static int3 operator /(int3 a, int b) => new int3((int)(a.x / b), (int)(a.y / b), (int)(a.z / b));
    public static int3 operator /(int a, int3 b) => new int3((int)(a / b.x), (int)(a / b.y), (int)(a / b.z));
    public static int3 operator %(int3 a, int3 b) => new int3((int)(a.x % b.x), (int)(a.y % b.y), (int)(a.z % b.z));
    public static int3 operator %(int3 a, int b) => new int3((int)(a.x % b), (int)(a.y % b), (int)(a.z % b));
    public static int3 operator %(int a, int3 b) => new int3((int)(a % b.x), (int)(a % b.y), (int)(a % b.z));
    public static int3 operator -(int3 a) => new int3((int)(-a.x), (int)(-a.y), (int)(-a.z));
    public static int3 operator +(int3 a) => a;
    public static int3 operator ++(int3 a) => new int3((int)(a.x + 1), (int)(a.y + 1), (int)(a.z + 1));
    public static int3 operator --(int3 a) => new int3((int)(a.x - 1), (int)(a.y - 1), (int)(a.z - 1));
    public static bool3 operator <(int3 a, int3 b) => new bool3(a.x < b.x, a.y < b.y, a.z < b.z);
    public static bool3 operator <(int3 a, int b) => new bool3(a.x < b, a.y < b, a.z < b);
    public static bool3 operator <(int a, int3 b) => new bool3(a < b.x, a < b.y, a < b.z);
    public static bool3 operator >(int3 a, int3 b) => new bool3(a.x > b.x, a.y > b.y, a.z > b.z);
    public static bool3 operator >(int3 a, int b) => new bool3(a.x > b, a.y > b, a.z > b);
    public static bool3 operator >(int a, int3 b) => new bool3(a > b.x, a > b.y, a > b.z);
    public static bool3 operator <=(int3 a, int3 b) => new bool3(a.x <= b.x, a.y <= b.y, a.z <= b.z);
    public static bool3 operator <=(int3 a, int b) => new bool3(a.x <= b, a.y <= b, a.z <= b);
    public static bool3 operator <=(int a, int3 b) => new bool3(a <= b.x, a <= b.y, a <= b.z);
    public static bool3 operator >=(int3 a, int3 b) => new bool3(a.x >= b.x, a.y >= b.y, a.z >= b.z);
    public static bool3 operator >=(int3 a, int b) => new bool3(a.x >= b, a.y >= b, a.z >= b);
    public static bool3 operator >=(int a, int3 b) => new bool3(a >= b.x, a >= b.y, a >= b.z);
    public static int3 operator &(int3 a, int3 b) => new int3((int)(a.x & b.x), (int)(a.y & b.y), (int)(a.z & b.z));
    public static int3 operator &(int3 a, int b) => new int3((int)(a.x & b), (int)(a.y & b), (int)(a.z & b));
    public static int3 operator |(int3 a, int3 b) => new int3((int)(a.x | b.x), (int)(a.y | b.y), (int)(a.z | b.z));
    public static int3 operator |(int3 a, int b) => new int3((int)(a.x | b), (int)(a.y | b), (int)(a.z | b));
    public static int3 operator ^(int3 a, int3 b) => new int3((int)(a.x ^ b.x), (int)(a.y ^ b.y), (int)(a.z ^ b.z));
    public static int3 operator ^(int3 a, int b) => new int3((int)(a.x ^ b), (int)(a.y ^ b), (int)(a.z ^ b));
    public static int3 operator <<(int3 a, int b) => new int3((int)(a.x << b), (int)(a.y << b), (int)(a.z << b));
    public static int3 operator >>(int3 a, int b) => new int3((int)(a.x >> b), (int)(a.y >> b), (int)(a.z >> b));
    public static int3 operator ~(int3 a) => new int3((int)(~a.x), (int)(~a.y), (int)(~a.z));
    public static bool3 operator ==(int3 a, int3 b) => new bool3(a.x == b.x, a.y == b.y, a.z == b.z);
    public static bool3 operator !=(int3 a, int3 b) => new bool3(a.x != b.x, a.y != b.y, a.z != b.z);
    public static bool3 operator ==(int3 a, int b) => new bool3(a.x == b, a.y == b, a.z == b);
    public static bool3 operator !=(int3 a, int b) => new bool3(a.x != b, a.y != b, a.z != b);
    public bool Equals(int3 other) => x == other.x && y == other.y && z == other.z;
    public override bool Equals(object? obj) => obj is int3 other && Equals(other);
    public override int GetHashCode() => HashCode.Combine(x, y, z);
    public override string ToString() => $"int3({x}, {y}, {z})";

    // Swizzles, xyzw and rgba. Setters only where no component repeats.
    public int2 xx => new int2(x, x);
    public int2 xy { get => new int2(x, y); set { x = value.x; y = value.y; } }
    public int2 xz { get => new int2(x, z); set { x = value.x; z = value.y; } }
    public int2 yx { get => new int2(y, x); set { y = value.x; x = value.y; } }
    public int2 yy => new int2(y, y);
    public int2 yz { get => new int2(y, z); set { y = value.x; z = value.y; } }
    public int2 zx { get => new int2(z, x); set { z = value.x; x = value.y; } }
    public int2 zy { get => new int2(z, y); set { z = value.x; y = value.y; } }
    public int2 zz => new int2(z, z);
    public int3 xxx => new int3(x, x, x);
    public int3 xxy => new int3(x, x, y);
    public int3 xxz => new int3(x, x, z);
    public int3 xyx => new int3(x, y, x);
    public int3 xyy => new int3(x, y, y);
    public int3 xyz { get => new int3(x, y, z); set { x = value.x; y = value.y; z = value.z; } }
    public int3 xzx => new int3(x, z, x);
    public int3 xzy { get => new int3(x, z, y); set { x = value.x; z = value.y; y = value.z; } }
    public int3 xzz => new int3(x, z, z);
    public int3 yxx => new int3(y, x, x);
    public int3 yxy => new int3(y, x, y);
    public int3 yxz { get => new int3(y, x, z); set { y = value.x; x = value.y; z = value.z; } }
    public int3 yyx => new int3(y, y, x);
    public int3 yyy => new int3(y, y, y);
    public int3 yyz => new int3(y, y, z);
    public int3 yzx { get => new int3(y, z, x); set { y = value.x; z = value.y; x = value.z; } }
    public int3 yzy => new int3(y, z, y);
    public int3 yzz => new int3(y, z, z);
    public int3 zxx => new int3(z, x, x);
    public int3 zxy { get => new int3(z, x, y); set { z = value.x; x = value.y; y = value.z; } }
    public int3 zxz => new int3(z, x, z);
    public int3 zyx { get => new int3(z, y, x); set { z = value.x; y = value.y; x = value.z; } }
    public int3 zyy => new int3(z, y, y);
    public int3 zyz => new int3(z, y, z);
    public int3 zzx => new int3(z, z, x);
    public int3 zzy => new int3(z, z, y);
    public int3 zzz => new int3(z, z, z);
    public int4 xxxx => new int4(x, x, x, x);
    public int4 xxxy => new int4(x, x, x, y);
    public int4 xxxz => new int4(x, x, x, z);
    public int4 xxyx => new int4(x, x, y, x);
    public int4 xxyy => new int4(x, x, y, y);
    public int4 xxyz => new int4(x, x, y, z);
    public int4 xxzx => new int4(x, x, z, x);
    public int4 xxzy => new int4(x, x, z, y);
    public int4 xxzz => new int4(x, x, z, z);
    public int4 xyxx => new int4(x, y, x, x);
    public int4 xyxy => new int4(x, y, x, y);
    public int4 xyxz => new int4(x, y, x, z);
    public int4 xyyx => new int4(x, y, y, x);
    public int4 xyyy => new int4(x, y, y, y);
    public int4 xyyz => new int4(x, y, y, z);
    public int4 xyzx => new int4(x, y, z, x);
    public int4 xyzy => new int4(x, y, z, y);
    public int4 xyzz => new int4(x, y, z, z);
    public int4 xzxx => new int4(x, z, x, x);
    public int4 xzxy => new int4(x, z, x, y);
    public int4 xzxz => new int4(x, z, x, z);
    public int4 xzyx => new int4(x, z, y, x);
    public int4 xzyy => new int4(x, z, y, y);
    public int4 xzyz => new int4(x, z, y, z);
    public int4 xzzx => new int4(x, z, z, x);
    public int4 xzzy => new int4(x, z, z, y);
    public int4 xzzz => new int4(x, z, z, z);
    public int4 yxxx => new int4(y, x, x, x);
    public int4 yxxy => new int4(y, x, x, y);
    public int4 yxxz => new int4(y, x, x, z);
    public int4 yxyx => new int4(y, x, y, x);
    public int4 yxyy => new int4(y, x, y, y);
    public int4 yxyz => new int4(y, x, y, z);
    public int4 yxzx => new int4(y, x, z, x);
    public int4 yxzy => new int4(y, x, z, y);
    public int4 yxzz => new int4(y, x, z, z);
    public int4 yyxx => new int4(y, y, x, x);
    public int4 yyxy => new int4(y, y, x, y);
    public int4 yyxz => new int4(y, y, x, z);
    public int4 yyyx => new int4(y, y, y, x);
    public int4 yyyy => new int4(y, y, y, y);
    public int4 yyyz => new int4(y, y, y, z);
    public int4 yyzx => new int4(y, y, z, x);
    public int4 yyzy => new int4(y, y, z, y);
    public int4 yyzz => new int4(y, y, z, z);
    public int4 yzxx => new int4(y, z, x, x);
    public int4 yzxy => new int4(y, z, x, y);
    public int4 yzxz => new int4(y, z, x, z);
    public int4 yzyx => new int4(y, z, y, x);
    public int4 yzyy => new int4(y, z, y, y);
    public int4 yzyz => new int4(y, z, y, z);
    public int4 yzzx => new int4(y, z, z, x);
    public int4 yzzy => new int4(y, z, z, y);
    public int4 yzzz => new int4(y, z, z, z);
    public int4 zxxx => new int4(z, x, x, x);
    public int4 zxxy => new int4(z, x, x, y);
    public int4 zxxz => new int4(z, x, x, z);
    public int4 zxyx => new int4(z, x, y, x);
    public int4 zxyy => new int4(z, x, y, y);
    public int4 zxyz => new int4(z, x, y, z);
    public int4 zxzx => new int4(z, x, z, x);
    public int4 zxzy => new int4(z, x, z, y);
    public int4 zxzz => new int4(z, x, z, z);
    public int4 zyxx => new int4(z, y, x, x);
    public int4 zyxy => new int4(z, y, x, y);
    public int4 zyxz => new int4(z, y, x, z);
    public int4 zyyx => new int4(z, y, y, x);
    public int4 zyyy => new int4(z, y, y, y);
    public int4 zyyz => new int4(z, y, y, z);
    public int4 zyzx => new int4(z, y, z, x);
    public int4 zyzy => new int4(z, y, z, y);
    public int4 zyzz => new int4(z, y, z, z);
    public int4 zzxx => new int4(z, z, x, x);
    public int4 zzxy => new int4(z, z, x, y);
    public int4 zzxz => new int4(z, z, x, z);
    public int4 zzyx => new int4(z, z, y, x);
    public int4 zzyy => new int4(z, z, y, y);
    public int4 zzyz => new int4(z, z, y, z);
    public int4 zzzx => new int4(z, z, z, x);
    public int4 zzzy => new int4(z, z, z, y);
    public int4 zzzz => new int4(z, z, z, z);
    public int r { get => x; set => x = value; }
    public int g { get => y; set => y = value; }
    public int b { get => z; set => z = value; }
    public int2 rr => new int2(x, x);
    public int2 rg { get => new int2(x, y); set { x = value.x; y = value.y; } }
    public int2 rb { get => new int2(x, z); set { x = value.x; z = value.y; } }
    public int2 gr { get => new int2(y, x); set { y = value.x; x = value.y; } }
    public int2 gg => new int2(y, y);
    public int2 gb { get => new int2(y, z); set { y = value.x; z = value.y; } }
    public int2 br { get => new int2(z, x); set { z = value.x; x = value.y; } }
    public int2 bg { get => new int2(z, y); set { z = value.x; y = value.y; } }
    public int2 bb => new int2(z, z);
    public int3 rrr => new int3(x, x, x);
    public int3 rrg => new int3(x, x, y);
    public int3 rrb => new int3(x, x, z);
    public int3 rgr => new int3(x, y, x);
    public int3 rgg => new int3(x, y, y);
    public int3 rgb { get => new int3(x, y, z); set { x = value.x; y = value.y; z = value.z; } }
    public int3 rbr => new int3(x, z, x);
    public int3 rbg { get => new int3(x, z, y); set { x = value.x; z = value.y; y = value.z; } }
    public int3 rbb => new int3(x, z, z);
    public int3 grr => new int3(y, x, x);
    public int3 grg => new int3(y, x, y);
    public int3 grb { get => new int3(y, x, z); set { y = value.x; x = value.y; z = value.z; } }
    public int3 ggr => new int3(y, y, x);
    public int3 ggg => new int3(y, y, y);
    public int3 ggb => new int3(y, y, z);
    public int3 gbr { get => new int3(y, z, x); set { y = value.x; z = value.y; x = value.z; } }
    public int3 gbg => new int3(y, z, y);
    public int3 gbb => new int3(y, z, z);
    public int3 brr => new int3(z, x, x);
    public int3 brg { get => new int3(z, x, y); set { z = value.x; x = value.y; y = value.z; } }
    public int3 brb => new int3(z, x, z);
    public int3 bgr { get => new int3(z, y, x); set { z = value.x; y = value.y; x = value.z; } }
    public int3 bgg => new int3(z, y, y);
    public int3 bgb => new int3(z, y, z);
    public int3 bbr => new int3(z, z, x);
    public int3 bbg => new int3(z, z, y);
    public int3 bbb => new int3(z, z, z);
    public int4 rrrr => new int4(x, x, x, x);
    public int4 rrrg => new int4(x, x, x, y);
    public int4 rrrb => new int4(x, x, x, z);
    public int4 rrgr => new int4(x, x, y, x);
    public int4 rrgg => new int4(x, x, y, y);
    public int4 rrgb => new int4(x, x, y, z);
    public int4 rrbr => new int4(x, x, z, x);
    public int4 rrbg => new int4(x, x, z, y);
    public int4 rrbb => new int4(x, x, z, z);
    public int4 rgrr => new int4(x, y, x, x);
    public int4 rgrg => new int4(x, y, x, y);
    public int4 rgrb => new int4(x, y, x, z);
    public int4 rggr => new int4(x, y, y, x);
    public int4 rggg => new int4(x, y, y, y);
    public int4 rggb => new int4(x, y, y, z);
    public int4 rgbr => new int4(x, y, z, x);
    public int4 rgbg => new int4(x, y, z, y);
    public int4 rgbb => new int4(x, y, z, z);
    public int4 rbrr => new int4(x, z, x, x);
    public int4 rbrg => new int4(x, z, x, y);
    public int4 rbrb => new int4(x, z, x, z);
    public int4 rbgr => new int4(x, z, y, x);
    public int4 rbgg => new int4(x, z, y, y);
    public int4 rbgb => new int4(x, z, y, z);
    public int4 rbbr => new int4(x, z, z, x);
    public int4 rbbg => new int4(x, z, z, y);
    public int4 rbbb => new int4(x, z, z, z);
    public int4 grrr => new int4(y, x, x, x);
    public int4 grrg => new int4(y, x, x, y);
    public int4 grrb => new int4(y, x, x, z);
    public int4 grgr => new int4(y, x, y, x);
    public int4 grgg => new int4(y, x, y, y);
    public int4 grgb => new int4(y, x, y, z);
    public int4 grbr => new int4(y, x, z, x);
    public int4 grbg => new int4(y, x, z, y);
    public int4 grbb => new int4(y, x, z, z);
    public int4 ggrr => new int4(y, y, x, x);
    public int4 ggrg => new int4(y, y, x, y);
    public int4 ggrb => new int4(y, y, x, z);
    public int4 gggr => new int4(y, y, y, x);
    public int4 gggg => new int4(y, y, y, y);
    public int4 gggb => new int4(y, y, y, z);
    public int4 ggbr => new int4(y, y, z, x);
    public int4 ggbg => new int4(y, y, z, y);
    public int4 ggbb => new int4(y, y, z, z);
    public int4 gbrr => new int4(y, z, x, x);
    public int4 gbrg => new int4(y, z, x, y);
    public int4 gbrb => new int4(y, z, x, z);
    public int4 gbgr => new int4(y, z, y, x);
    public int4 gbgg => new int4(y, z, y, y);
    public int4 gbgb => new int4(y, z, y, z);
    public int4 gbbr => new int4(y, z, z, x);
    public int4 gbbg => new int4(y, z, z, y);
    public int4 gbbb => new int4(y, z, z, z);
    public int4 brrr => new int4(z, x, x, x);
    public int4 brrg => new int4(z, x, x, y);
    public int4 brrb => new int4(z, x, x, z);
    public int4 brgr => new int4(z, x, y, x);
    public int4 brgg => new int4(z, x, y, y);
    public int4 brgb => new int4(z, x, y, z);
    public int4 brbr => new int4(z, x, z, x);
    public int4 brbg => new int4(z, x, z, y);
    public int4 brbb => new int4(z, x, z, z);
    public int4 bgrr => new int4(z, y, x, x);
    public int4 bgrg => new int4(z, y, x, y);
    public int4 bgrb => new int4(z, y, x, z);
    public int4 bggr => new int4(z, y, y, x);
    public int4 bggg => new int4(z, y, y, y);
    public int4 bggb => new int4(z, y, y, z);
    public int4 bgbr => new int4(z, y, z, x);
    public int4 bgbg => new int4(z, y, z, y);
    public int4 bgbb => new int4(z, y, z, z);
    public int4 bbrr => new int4(z, z, x, x);
    public int4 bbrg => new int4(z, z, x, y);
    public int4 bbrb => new int4(z, z, x, z);
    public int4 bbgr => new int4(z, z, y, x);
    public int4 bbgg => new int4(z, z, y, y);
    public int4 bbgb => new int4(z, z, y, z);
    public int4 bbbr => new int4(z, z, z, x);
    public int4 bbbg => new int4(z, z, z, y);
    public int4 bbbb => new int4(z, z, z, z);
}
