// <auto-generated>
// Written by tools/gen_hlsl_types.py. Do not edit; edit the script and run it again.
// </auto-generated>
#nullable enable
#pragma warning disable IDE1006, CS1591
using System;
using System.Runtime.InteropServices;

namespace Csl.Hlsl;

/// <summary>HLSL int4: 4 components of int. Runs on the GPU; the C# operations exist so shader code type-checks and can be unit tested.</summary>
[StructLayout(LayoutKind.Sequential)]
public struct int4 : IEquatable<int4>
{
    public int x, y, z, w;
    public int4(int x, int y, int z, int w) { this.x = x; this.y = y; this.z = z; this.w = w; }
    public int4(int v) { x = v; y = v; z = v; w = v; }
    public int4(int3 xyz, int w) { x = xyz.x; y = xyz.y; z = xyz.z; this.w = w; }
    public int4(int x, int3 yzw) { this.x = x; y = yzw.x; z = yzw.y; w = yzw.z; }
    public int4(int2 xy, int2 zw) { x = xy.x; y = xy.y; z = zw.x; w = zw.y; }
    public int4(int2 xy, int z, int w) { x = xy.x; y = xy.y; this.z = z; this.w = w; }
    public int4(float4 v) { x = (int)v.x; y = (int)v.y; z = (int)v.z; w = (int)v.w; }
    public static explicit operator int4(float4 v) => new int4(v);
    public int4(uint4 v) { x = (int)v.x; y = (int)v.y; z = (int)v.z; w = (int)v.w; }
    public static explicit operator int4(uint4 v) => new int4(v);
    public static implicit operator int4(int v) => new int4(v);
    public int this[int i]
    {
        get => i switch { 0 => x, 1 => y, 2 => z, 3 => w, _ => throw new IndexOutOfRangeException() };
        set { switch (i) { case 0: x = value; break; case 1: y = value; break; case 2: z = value; break; case 3: w = value; break; default: throw new IndexOutOfRangeException(); } }
    }
    public static int4 operator +(int4 a, int4 b) => new int4((int)(a.x + b.x), (int)(a.y + b.y), (int)(a.z + b.z), (int)(a.w + b.w));
    public static int4 operator +(int4 a, int b) => new int4((int)(a.x + b), (int)(a.y + b), (int)(a.z + b), (int)(a.w + b));
    public static int4 operator +(int a, int4 b) => new int4((int)(a + b.x), (int)(a + b.y), (int)(a + b.z), (int)(a + b.w));
    public static int4 operator -(int4 a, int4 b) => new int4((int)(a.x - b.x), (int)(a.y - b.y), (int)(a.z - b.z), (int)(a.w - b.w));
    public static int4 operator -(int4 a, int b) => new int4((int)(a.x - b), (int)(a.y - b), (int)(a.z - b), (int)(a.w - b));
    public static int4 operator -(int a, int4 b) => new int4((int)(a - b.x), (int)(a - b.y), (int)(a - b.z), (int)(a - b.w));
    public static int4 operator *(int4 a, int4 b) => new int4((int)(a.x * b.x), (int)(a.y * b.y), (int)(a.z * b.z), (int)(a.w * b.w));
    public static int4 operator *(int4 a, int b) => new int4((int)(a.x * b), (int)(a.y * b), (int)(a.z * b), (int)(a.w * b));
    public static int4 operator *(int a, int4 b) => new int4((int)(a * b.x), (int)(a * b.y), (int)(a * b.z), (int)(a * b.w));
    public static int4 operator /(int4 a, int4 b) => new int4((int)(a.x / b.x), (int)(a.y / b.y), (int)(a.z / b.z), (int)(a.w / b.w));
    public static int4 operator /(int4 a, int b) => new int4((int)(a.x / b), (int)(a.y / b), (int)(a.z / b), (int)(a.w / b));
    public static int4 operator /(int a, int4 b) => new int4((int)(a / b.x), (int)(a / b.y), (int)(a / b.z), (int)(a / b.w));
    public static int4 operator %(int4 a, int4 b) => new int4((int)(a.x % b.x), (int)(a.y % b.y), (int)(a.z % b.z), (int)(a.w % b.w));
    public static int4 operator %(int4 a, int b) => new int4((int)(a.x % b), (int)(a.y % b), (int)(a.z % b), (int)(a.w % b));
    public static int4 operator %(int a, int4 b) => new int4((int)(a % b.x), (int)(a % b.y), (int)(a % b.z), (int)(a % b.w));
    public static int4 operator -(int4 a) => new int4((int)(-a.x), (int)(-a.y), (int)(-a.z), (int)(-a.w));
    public static int4 operator +(int4 a) => a;
    public static int4 operator ++(int4 a) => new int4((int)(a.x + 1), (int)(a.y + 1), (int)(a.z + 1), (int)(a.w + 1));
    public static int4 operator --(int4 a) => new int4((int)(a.x - 1), (int)(a.y - 1), (int)(a.z - 1), (int)(a.w - 1));
    public static bool4 operator <(int4 a, int4 b) => new bool4(a.x < b.x, a.y < b.y, a.z < b.z, a.w < b.w);
    public static bool4 operator <(int4 a, int b) => new bool4(a.x < b, a.y < b, a.z < b, a.w < b);
    public static bool4 operator <(int a, int4 b) => new bool4(a < b.x, a < b.y, a < b.z, a < b.w);
    public static bool4 operator >(int4 a, int4 b) => new bool4(a.x > b.x, a.y > b.y, a.z > b.z, a.w > b.w);
    public static bool4 operator >(int4 a, int b) => new bool4(a.x > b, a.y > b, a.z > b, a.w > b);
    public static bool4 operator >(int a, int4 b) => new bool4(a > b.x, a > b.y, a > b.z, a > b.w);
    public static bool4 operator <=(int4 a, int4 b) => new bool4(a.x <= b.x, a.y <= b.y, a.z <= b.z, a.w <= b.w);
    public static bool4 operator <=(int4 a, int b) => new bool4(a.x <= b, a.y <= b, a.z <= b, a.w <= b);
    public static bool4 operator <=(int a, int4 b) => new bool4(a <= b.x, a <= b.y, a <= b.z, a <= b.w);
    public static bool4 operator >=(int4 a, int4 b) => new bool4(a.x >= b.x, a.y >= b.y, a.z >= b.z, a.w >= b.w);
    public static bool4 operator >=(int4 a, int b) => new bool4(a.x >= b, a.y >= b, a.z >= b, a.w >= b);
    public static bool4 operator >=(int a, int4 b) => new bool4(a >= b.x, a >= b.y, a >= b.z, a >= b.w);
    public static int4 operator &(int4 a, int4 b) => new int4((int)(a.x & b.x), (int)(a.y & b.y), (int)(a.z & b.z), (int)(a.w & b.w));
    public static int4 operator &(int4 a, int b) => new int4((int)(a.x & b), (int)(a.y & b), (int)(a.z & b), (int)(a.w & b));
    public static int4 operator |(int4 a, int4 b) => new int4((int)(a.x | b.x), (int)(a.y | b.y), (int)(a.z | b.z), (int)(a.w | b.w));
    public static int4 operator |(int4 a, int b) => new int4((int)(a.x | b), (int)(a.y | b), (int)(a.z | b), (int)(a.w | b));
    public static int4 operator ^(int4 a, int4 b) => new int4((int)(a.x ^ b.x), (int)(a.y ^ b.y), (int)(a.z ^ b.z), (int)(a.w ^ b.w));
    public static int4 operator ^(int4 a, int b) => new int4((int)(a.x ^ b), (int)(a.y ^ b), (int)(a.z ^ b), (int)(a.w ^ b));
    public static int4 operator <<(int4 a, int b) => new int4((int)(a.x << b), (int)(a.y << b), (int)(a.z << b), (int)(a.w << b));
    public static int4 operator >>(int4 a, int b) => new int4((int)(a.x >> b), (int)(a.y >> b), (int)(a.z >> b), (int)(a.w >> b));
    public static int4 operator ~(int4 a) => new int4((int)(~a.x), (int)(~a.y), (int)(~a.z), (int)(~a.w));
    public static bool4 operator ==(int4 a, int4 b) => new bool4(a.x == b.x, a.y == b.y, a.z == b.z, a.w == b.w);
    public static bool4 operator !=(int4 a, int4 b) => new bool4(a.x != b.x, a.y != b.y, a.z != b.z, a.w != b.w);
    public static bool4 operator ==(int4 a, int b) => new bool4(a.x == b, a.y == b, a.z == b, a.w == b);
    public static bool4 operator !=(int4 a, int b) => new bool4(a.x != b, a.y != b, a.z != b, a.w != b);
    public bool Equals(int4 other) => x == other.x && y == other.y && z == other.z && w == other.w;
    public override bool Equals(object? obj) => obj is int4 other && Equals(other);
    public override int GetHashCode() => HashCode.Combine(x, y, z, w);
    public override string ToString() => $"int4({x}, {y}, {z}, {w})";

    // Swizzles, xyzw and rgba. Setters only where no component repeats.
    public int2 xx => new int2(x, x);
    public int2 xy { get => new int2(x, y); set { x = value.x; y = value.y; } }
    public int2 xz { get => new int2(x, z); set { x = value.x; z = value.y; } }
    public int2 xw { get => new int2(x, w); set { x = value.x; w = value.y; } }
    public int2 yx { get => new int2(y, x); set { y = value.x; x = value.y; } }
    public int2 yy => new int2(y, y);
    public int2 yz { get => new int2(y, z); set { y = value.x; z = value.y; } }
    public int2 yw { get => new int2(y, w); set { y = value.x; w = value.y; } }
    public int2 zx { get => new int2(z, x); set { z = value.x; x = value.y; } }
    public int2 zy { get => new int2(z, y); set { z = value.x; y = value.y; } }
    public int2 zz => new int2(z, z);
    public int2 zw { get => new int2(z, w); set { z = value.x; w = value.y; } }
    public int2 wx { get => new int2(w, x); set { w = value.x; x = value.y; } }
    public int2 wy { get => new int2(w, y); set { w = value.x; y = value.y; } }
    public int2 wz { get => new int2(w, z); set { w = value.x; z = value.y; } }
    public int2 ww => new int2(w, w);
    public int3 xxx => new int3(x, x, x);
    public int3 xxy => new int3(x, x, y);
    public int3 xxz => new int3(x, x, z);
    public int3 xxw => new int3(x, x, w);
    public int3 xyx => new int3(x, y, x);
    public int3 xyy => new int3(x, y, y);
    public int3 xyz { get => new int3(x, y, z); set { x = value.x; y = value.y; z = value.z; } }
    public int3 xyw { get => new int3(x, y, w); set { x = value.x; y = value.y; w = value.z; } }
    public int3 xzx => new int3(x, z, x);
    public int3 xzy { get => new int3(x, z, y); set { x = value.x; z = value.y; y = value.z; } }
    public int3 xzz => new int3(x, z, z);
    public int3 xzw { get => new int3(x, z, w); set { x = value.x; z = value.y; w = value.z; } }
    public int3 xwx => new int3(x, w, x);
    public int3 xwy { get => new int3(x, w, y); set { x = value.x; w = value.y; y = value.z; } }
    public int3 xwz { get => new int3(x, w, z); set { x = value.x; w = value.y; z = value.z; } }
    public int3 xww => new int3(x, w, w);
    public int3 yxx => new int3(y, x, x);
    public int3 yxy => new int3(y, x, y);
    public int3 yxz { get => new int3(y, x, z); set { y = value.x; x = value.y; z = value.z; } }
    public int3 yxw { get => new int3(y, x, w); set { y = value.x; x = value.y; w = value.z; } }
    public int3 yyx => new int3(y, y, x);
    public int3 yyy => new int3(y, y, y);
    public int3 yyz => new int3(y, y, z);
    public int3 yyw => new int3(y, y, w);
    public int3 yzx { get => new int3(y, z, x); set { y = value.x; z = value.y; x = value.z; } }
    public int3 yzy => new int3(y, z, y);
    public int3 yzz => new int3(y, z, z);
    public int3 yzw { get => new int3(y, z, w); set { y = value.x; z = value.y; w = value.z; } }
    public int3 ywx { get => new int3(y, w, x); set { y = value.x; w = value.y; x = value.z; } }
    public int3 ywy => new int3(y, w, y);
    public int3 ywz { get => new int3(y, w, z); set { y = value.x; w = value.y; z = value.z; } }
    public int3 yww => new int3(y, w, w);
    public int3 zxx => new int3(z, x, x);
    public int3 zxy { get => new int3(z, x, y); set { z = value.x; x = value.y; y = value.z; } }
    public int3 zxz => new int3(z, x, z);
    public int3 zxw { get => new int3(z, x, w); set { z = value.x; x = value.y; w = value.z; } }
    public int3 zyx { get => new int3(z, y, x); set { z = value.x; y = value.y; x = value.z; } }
    public int3 zyy => new int3(z, y, y);
    public int3 zyz => new int3(z, y, z);
    public int3 zyw { get => new int3(z, y, w); set { z = value.x; y = value.y; w = value.z; } }
    public int3 zzx => new int3(z, z, x);
    public int3 zzy => new int3(z, z, y);
    public int3 zzz => new int3(z, z, z);
    public int3 zzw => new int3(z, z, w);
    public int3 zwx { get => new int3(z, w, x); set { z = value.x; w = value.y; x = value.z; } }
    public int3 zwy { get => new int3(z, w, y); set { z = value.x; w = value.y; y = value.z; } }
    public int3 zwz => new int3(z, w, z);
    public int3 zww => new int3(z, w, w);
    public int3 wxx => new int3(w, x, x);
    public int3 wxy { get => new int3(w, x, y); set { w = value.x; x = value.y; y = value.z; } }
    public int3 wxz { get => new int3(w, x, z); set { w = value.x; x = value.y; z = value.z; } }
    public int3 wxw => new int3(w, x, w);
    public int3 wyx { get => new int3(w, y, x); set { w = value.x; y = value.y; x = value.z; } }
    public int3 wyy => new int3(w, y, y);
    public int3 wyz { get => new int3(w, y, z); set { w = value.x; y = value.y; z = value.z; } }
    public int3 wyw => new int3(w, y, w);
    public int3 wzx { get => new int3(w, z, x); set { w = value.x; z = value.y; x = value.z; } }
    public int3 wzy { get => new int3(w, z, y); set { w = value.x; z = value.y; y = value.z; } }
    public int3 wzz => new int3(w, z, z);
    public int3 wzw => new int3(w, z, w);
    public int3 wwx => new int3(w, w, x);
    public int3 wwy => new int3(w, w, y);
    public int3 wwz => new int3(w, w, z);
    public int3 www => new int3(w, w, w);
    public int4 xxxx => new int4(x, x, x, x);
    public int4 xxxy => new int4(x, x, x, y);
    public int4 xxxz => new int4(x, x, x, z);
    public int4 xxxw => new int4(x, x, x, w);
    public int4 xxyx => new int4(x, x, y, x);
    public int4 xxyy => new int4(x, x, y, y);
    public int4 xxyz => new int4(x, x, y, z);
    public int4 xxyw => new int4(x, x, y, w);
    public int4 xxzx => new int4(x, x, z, x);
    public int4 xxzy => new int4(x, x, z, y);
    public int4 xxzz => new int4(x, x, z, z);
    public int4 xxzw => new int4(x, x, z, w);
    public int4 xxwx => new int4(x, x, w, x);
    public int4 xxwy => new int4(x, x, w, y);
    public int4 xxwz => new int4(x, x, w, z);
    public int4 xxww => new int4(x, x, w, w);
    public int4 xyxx => new int4(x, y, x, x);
    public int4 xyxy => new int4(x, y, x, y);
    public int4 xyxz => new int4(x, y, x, z);
    public int4 xyxw => new int4(x, y, x, w);
    public int4 xyyx => new int4(x, y, y, x);
    public int4 xyyy => new int4(x, y, y, y);
    public int4 xyyz => new int4(x, y, y, z);
    public int4 xyyw => new int4(x, y, y, w);
    public int4 xyzx => new int4(x, y, z, x);
    public int4 xyzy => new int4(x, y, z, y);
    public int4 xyzz => new int4(x, y, z, z);
    public int4 xyzw { get => new int4(x, y, z, w); set { x = value.x; y = value.y; z = value.z; w = value.w; } }
    public int4 xywx => new int4(x, y, w, x);
    public int4 xywy => new int4(x, y, w, y);
    public int4 xywz { get => new int4(x, y, w, z); set { x = value.x; y = value.y; w = value.z; z = value.w; } }
    public int4 xyww => new int4(x, y, w, w);
    public int4 xzxx => new int4(x, z, x, x);
    public int4 xzxy => new int4(x, z, x, y);
    public int4 xzxz => new int4(x, z, x, z);
    public int4 xzxw => new int4(x, z, x, w);
    public int4 xzyx => new int4(x, z, y, x);
    public int4 xzyy => new int4(x, z, y, y);
    public int4 xzyz => new int4(x, z, y, z);
    public int4 xzyw { get => new int4(x, z, y, w); set { x = value.x; z = value.y; y = value.z; w = value.w; } }
    public int4 xzzx => new int4(x, z, z, x);
    public int4 xzzy => new int4(x, z, z, y);
    public int4 xzzz => new int4(x, z, z, z);
    public int4 xzzw => new int4(x, z, z, w);
    public int4 xzwx => new int4(x, z, w, x);
    public int4 xzwy { get => new int4(x, z, w, y); set { x = value.x; z = value.y; w = value.z; y = value.w; } }
    public int4 xzwz => new int4(x, z, w, z);
    public int4 xzww => new int4(x, z, w, w);
    public int4 xwxx => new int4(x, w, x, x);
    public int4 xwxy => new int4(x, w, x, y);
    public int4 xwxz => new int4(x, w, x, z);
    public int4 xwxw => new int4(x, w, x, w);
    public int4 xwyx => new int4(x, w, y, x);
    public int4 xwyy => new int4(x, w, y, y);
    public int4 xwyz { get => new int4(x, w, y, z); set { x = value.x; w = value.y; y = value.z; z = value.w; } }
    public int4 xwyw => new int4(x, w, y, w);
    public int4 xwzx => new int4(x, w, z, x);
    public int4 xwzy { get => new int4(x, w, z, y); set { x = value.x; w = value.y; z = value.z; y = value.w; } }
    public int4 xwzz => new int4(x, w, z, z);
    public int4 xwzw => new int4(x, w, z, w);
    public int4 xwwx => new int4(x, w, w, x);
    public int4 xwwy => new int4(x, w, w, y);
    public int4 xwwz => new int4(x, w, w, z);
    public int4 xwww => new int4(x, w, w, w);
    public int4 yxxx => new int4(y, x, x, x);
    public int4 yxxy => new int4(y, x, x, y);
    public int4 yxxz => new int4(y, x, x, z);
    public int4 yxxw => new int4(y, x, x, w);
    public int4 yxyx => new int4(y, x, y, x);
    public int4 yxyy => new int4(y, x, y, y);
    public int4 yxyz => new int4(y, x, y, z);
    public int4 yxyw => new int4(y, x, y, w);
    public int4 yxzx => new int4(y, x, z, x);
    public int4 yxzy => new int4(y, x, z, y);
    public int4 yxzz => new int4(y, x, z, z);
    public int4 yxzw { get => new int4(y, x, z, w); set { y = value.x; x = value.y; z = value.z; w = value.w; } }
    public int4 yxwx => new int4(y, x, w, x);
    public int4 yxwy => new int4(y, x, w, y);
    public int4 yxwz { get => new int4(y, x, w, z); set { y = value.x; x = value.y; w = value.z; z = value.w; } }
    public int4 yxww => new int4(y, x, w, w);
    public int4 yyxx => new int4(y, y, x, x);
    public int4 yyxy => new int4(y, y, x, y);
    public int4 yyxz => new int4(y, y, x, z);
    public int4 yyxw => new int4(y, y, x, w);
    public int4 yyyx => new int4(y, y, y, x);
    public int4 yyyy => new int4(y, y, y, y);
    public int4 yyyz => new int4(y, y, y, z);
    public int4 yyyw => new int4(y, y, y, w);
    public int4 yyzx => new int4(y, y, z, x);
    public int4 yyzy => new int4(y, y, z, y);
    public int4 yyzz => new int4(y, y, z, z);
    public int4 yyzw => new int4(y, y, z, w);
    public int4 yywx => new int4(y, y, w, x);
    public int4 yywy => new int4(y, y, w, y);
    public int4 yywz => new int4(y, y, w, z);
    public int4 yyww => new int4(y, y, w, w);
    public int4 yzxx => new int4(y, z, x, x);
    public int4 yzxy => new int4(y, z, x, y);
    public int4 yzxz => new int4(y, z, x, z);
    public int4 yzxw { get => new int4(y, z, x, w); set { y = value.x; z = value.y; x = value.z; w = value.w; } }
    public int4 yzyx => new int4(y, z, y, x);
    public int4 yzyy => new int4(y, z, y, y);
    public int4 yzyz => new int4(y, z, y, z);
    public int4 yzyw => new int4(y, z, y, w);
    public int4 yzzx => new int4(y, z, z, x);
    public int4 yzzy => new int4(y, z, z, y);
    public int4 yzzz => new int4(y, z, z, z);
    public int4 yzzw => new int4(y, z, z, w);
    public int4 yzwx { get => new int4(y, z, w, x); set { y = value.x; z = value.y; w = value.z; x = value.w; } }
    public int4 yzwy => new int4(y, z, w, y);
    public int4 yzwz => new int4(y, z, w, z);
    public int4 yzww => new int4(y, z, w, w);
    public int4 ywxx => new int4(y, w, x, x);
    public int4 ywxy => new int4(y, w, x, y);
    public int4 ywxz { get => new int4(y, w, x, z); set { y = value.x; w = value.y; x = value.z; z = value.w; } }
    public int4 ywxw => new int4(y, w, x, w);
    public int4 ywyx => new int4(y, w, y, x);
    public int4 ywyy => new int4(y, w, y, y);
    public int4 ywyz => new int4(y, w, y, z);
    public int4 ywyw => new int4(y, w, y, w);
    public int4 ywzx { get => new int4(y, w, z, x); set { y = value.x; w = value.y; z = value.z; x = value.w; } }
    public int4 ywzy => new int4(y, w, z, y);
    public int4 ywzz => new int4(y, w, z, z);
    public int4 ywzw => new int4(y, w, z, w);
    public int4 ywwx => new int4(y, w, w, x);
    public int4 ywwy => new int4(y, w, w, y);
    public int4 ywwz => new int4(y, w, w, z);
    public int4 ywww => new int4(y, w, w, w);
    public int4 zxxx => new int4(z, x, x, x);
    public int4 zxxy => new int4(z, x, x, y);
    public int4 zxxz => new int4(z, x, x, z);
    public int4 zxxw => new int4(z, x, x, w);
    public int4 zxyx => new int4(z, x, y, x);
    public int4 zxyy => new int4(z, x, y, y);
    public int4 zxyz => new int4(z, x, y, z);
    public int4 zxyw { get => new int4(z, x, y, w); set { z = value.x; x = value.y; y = value.z; w = value.w; } }
    public int4 zxzx => new int4(z, x, z, x);
    public int4 zxzy => new int4(z, x, z, y);
    public int4 zxzz => new int4(z, x, z, z);
    public int4 zxzw => new int4(z, x, z, w);
    public int4 zxwx => new int4(z, x, w, x);
    public int4 zxwy { get => new int4(z, x, w, y); set { z = value.x; x = value.y; w = value.z; y = value.w; } }
    public int4 zxwz => new int4(z, x, w, z);
    public int4 zxww => new int4(z, x, w, w);
    public int4 zyxx => new int4(z, y, x, x);
    public int4 zyxy => new int4(z, y, x, y);
    public int4 zyxz => new int4(z, y, x, z);
    public int4 zyxw { get => new int4(z, y, x, w); set { z = value.x; y = value.y; x = value.z; w = value.w; } }
    public int4 zyyx => new int4(z, y, y, x);
    public int4 zyyy => new int4(z, y, y, y);
    public int4 zyyz => new int4(z, y, y, z);
    public int4 zyyw => new int4(z, y, y, w);
    public int4 zyzx => new int4(z, y, z, x);
    public int4 zyzy => new int4(z, y, z, y);
    public int4 zyzz => new int4(z, y, z, z);
    public int4 zyzw => new int4(z, y, z, w);
    public int4 zywx { get => new int4(z, y, w, x); set { z = value.x; y = value.y; w = value.z; x = value.w; } }
    public int4 zywy => new int4(z, y, w, y);
    public int4 zywz => new int4(z, y, w, z);
    public int4 zyww => new int4(z, y, w, w);
    public int4 zzxx => new int4(z, z, x, x);
    public int4 zzxy => new int4(z, z, x, y);
    public int4 zzxz => new int4(z, z, x, z);
    public int4 zzxw => new int4(z, z, x, w);
    public int4 zzyx => new int4(z, z, y, x);
    public int4 zzyy => new int4(z, z, y, y);
    public int4 zzyz => new int4(z, z, y, z);
    public int4 zzyw => new int4(z, z, y, w);
    public int4 zzzx => new int4(z, z, z, x);
    public int4 zzzy => new int4(z, z, z, y);
    public int4 zzzz => new int4(z, z, z, z);
    public int4 zzzw => new int4(z, z, z, w);
    public int4 zzwx => new int4(z, z, w, x);
    public int4 zzwy => new int4(z, z, w, y);
    public int4 zzwz => new int4(z, z, w, z);
    public int4 zzww => new int4(z, z, w, w);
    public int4 zwxx => new int4(z, w, x, x);
    public int4 zwxy { get => new int4(z, w, x, y); set { z = value.x; w = value.y; x = value.z; y = value.w; } }
    public int4 zwxz => new int4(z, w, x, z);
    public int4 zwxw => new int4(z, w, x, w);
    public int4 zwyx { get => new int4(z, w, y, x); set { z = value.x; w = value.y; y = value.z; x = value.w; } }
    public int4 zwyy => new int4(z, w, y, y);
    public int4 zwyz => new int4(z, w, y, z);
    public int4 zwyw => new int4(z, w, y, w);
    public int4 zwzx => new int4(z, w, z, x);
    public int4 zwzy => new int4(z, w, z, y);
    public int4 zwzz => new int4(z, w, z, z);
    public int4 zwzw => new int4(z, w, z, w);
    public int4 zwwx => new int4(z, w, w, x);
    public int4 zwwy => new int4(z, w, w, y);
    public int4 zwwz => new int4(z, w, w, z);
    public int4 zwww => new int4(z, w, w, w);
    public int4 wxxx => new int4(w, x, x, x);
    public int4 wxxy => new int4(w, x, x, y);
    public int4 wxxz => new int4(w, x, x, z);
    public int4 wxxw => new int4(w, x, x, w);
    public int4 wxyx => new int4(w, x, y, x);
    public int4 wxyy => new int4(w, x, y, y);
    public int4 wxyz { get => new int4(w, x, y, z); set { w = value.x; x = value.y; y = value.z; z = value.w; } }
    public int4 wxyw => new int4(w, x, y, w);
    public int4 wxzx => new int4(w, x, z, x);
    public int4 wxzy { get => new int4(w, x, z, y); set { w = value.x; x = value.y; z = value.z; y = value.w; } }
    public int4 wxzz => new int4(w, x, z, z);
    public int4 wxzw => new int4(w, x, z, w);
    public int4 wxwx => new int4(w, x, w, x);
    public int4 wxwy => new int4(w, x, w, y);
    public int4 wxwz => new int4(w, x, w, z);
    public int4 wxww => new int4(w, x, w, w);
    public int4 wyxx => new int4(w, y, x, x);
    public int4 wyxy => new int4(w, y, x, y);
    public int4 wyxz { get => new int4(w, y, x, z); set { w = value.x; y = value.y; x = value.z; z = value.w; } }
    public int4 wyxw => new int4(w, y, x, w);
    public int4 wyyx => new int4(w, y, y, x);
    public int4 wyyy => new int4(w, y, y, y);
    public int4 wyyz => new int4(w, y, y, z);
    public int4 wyyw => new int4(w, y, y, w);
    public int4 wyzx { get => new int4(w, y, z, x); set { w = value.x; y = value.y; z = value.z; x = value.w; } }
    public int4 wyzy => new int4(w, y, z, y);
    public int4 wyzz => new int4(w, y, z, z);
    public int4 wyzw => new int4(w, y, z, w);
    public int4 wywx => new int4(w, y, w, x);
    public int4 wywy => new int4(w, y, w, y);
    public int4 wywz => new int4(w, y, w, z);
    public int4 wyww => new int4(w, y, w, w);
    public int4 wzxx => new int4(w, z, x, x);
    public int4 wzxy { get => new int4(w, z, x, y); set { w = value.x; z = value.y; x = value.z; y = value.w; } }
    public int4 wzxz => new int4(w, z, x, z);
    public int4 wzxw => new int4(w, z, x, w);
    public int4 wzyx { get => new int4(w, z, y, x); set { w = value.x; z = value.y; y = value.z; x = value.w; } }
    public int4 wzyy => new int4(w, z, y, y);
    public int4 wzyz => new int4(w, z, y, z);
    public int4 wzyw => new int4(w, z, y, w);
    public int4 wzzx => new int4(w, z, z, x);
    public int4 wzzy => new int4(w, z, z, y);
    public int4 wzzz => new int4(w, z, z, z);
    public int4 wzzw => new int4(w, z, z, w);
    public int4 wzwx => new int4(w, z, w, x);
    public int4 wzwy => new int4(w, z, w, y);
    public int4 wzwz => new int4(w, z, w, z);
    public int4 wzww => new int4(w, z, w, w);
    public int4 wwxx => new int4(w, w, x, x);
    public int4 wwxy => new int4(w, w, x, y);
    public int4 wwxz => new int4(w, w, x, z);
    public int4 wwxw => new int4(w, w, x, w);
    public int4 wwyx => new int4(w, w, y, x);
    public int4 wwyy => new int4(w, w, y, y);
    public int4 wwyz => new int4(w, w, y, z);
    public int4 wwyw => new int4(w, w, y, w);
    public int4 wwzx => new int4(w, w, z, x);
    public int4 wwzy => new int4(w, w, z, y);
    public int4 wwzz => new int4(w, w, z, z);
    public int4 wwzw => new int4(w, w, z, w);
    public int4 wwwx => new int4(w, w, w, x);
    public int4 wwwy => new int4(w, w, w, y);
    public int4 wwwz => new int4(w, w, w, z);
    public int4 wwww => new int4(w, w, w, w);
    public int r { get => x; set => x = value; }
    public int g { get => y; set => y = value; }
    public int b { get => z; set => z = value; }
    public int a { get => w; set => w = value; }
    public int2 rr => new int2(x, x);
    public int2 rg { get => new int2(x, y); set { x = value.x; y = value.y; } }
    public int2 rb { get => new int2(x, z); set { x = value.x; z = value.y; } }
    public int2 ra { get => new int2(x, w); set { x = value.x; w = value.y; } }
    public int2 gr { get => new int2(y, x); set { y = value.x; x = value.y; } }
    public int2 gg => new int2(y, y);
    public int2 gb { get => new int2(y, z); set { y = value.x; z = value.y; } }
    public int2 ga { get => new int2(y, w); set { y = value.x; w = value.y; } }
    public int2 br { get => new int2(z, x); set { z = value.x; x = value.y; } }
    public int2 bg { get => new int2(z, y); set { z = value.x; y = value.y; } }
    public int2 bb => new int2(z, z);
    public int2 ba { get => new int2(z, w); set { z = value.x; w = value.y; } }
    public int2 ar { get => new int2(w, x); set { w = value.x; x = value.y; } }
    public int2 ag { get => new int2(w, y); set { w = value.x; y = value.y; } }
    public int2 ab { get => new int2(w, z); set { w = value.x; z = value.y; } }
    public int2 aa => new int2(w, w);
    public int3 rrr => new int3(x, x, x);
    public int3 rrg => new int3(x, x, y);
    public int3 rrb => new int3(x, x, z);
    public int3 rra => new int3(x, x, w);
    public int3 rgr => new int3(x, y, x);
    public int3 rgg => new int3(x, y, y);
    public int3 rgb { get => new int3(x, y, z); set { x = value.x; y = value.y; z = value.z; } }
    public int3 rga { get => new int3(x, y, w); set { x = value.x; y = value.y; w = value.z; } }
    public int3 rbr => new int3(x, z, x);
    public int3 rbg { get => new int3(x, z, y); set { x = value.x; z = value.y; y = value.z; } }
    public int3 rbb => new int3(x, z, z);
    public int3 rba { get => new int3(x, z, w); set { x = value.x; z = value.y; w = value.z; } }
    public int3 rar => new int3(x, w, x);
    public int3 rag { get => new int3(x, w, y); set { x = value.x; w = value.y; y = value.z; } }
    public int3 rab { get => new int3(x, w, z); set { x = value.x; w = value.y; z = value.z; } }
    public int3 raa => new int3(x, w, w);
    public int3 grr => new int3(y, x, x);
    public int3 grg => new int3(y, x, y);
    public int3 grb { get => new int3(y, x, z); set { y = value.x; x = value.y; z = value.z; } }
    public int3 gra { get => new int3(y, x, w); set { y = value.x; x = value.y; w = value.z; } }
    public int3 ggr => new int3(y, y, x);
    public int3 ggg => new int3(y, y, y);
    public int3 ggb => new int3(y, y, z);
    public int3 gga => new int3(y, y, w);
    public int3 gbr { get => new int3(y, z, x); set { y = value.x; z = value.y; x = value.z; } }
    public int3 gbg => new int3(y, z, y);
    public int3 gbb => new int3(y, z, z);
    public int3 gba { get => new int3(y, z, w); set { y = value.x; z = value.y; w = value.z; } }
    public int3 gar { get => new int3(y, w, x); set { y = value.x; w = value.y; x = value.z; } }
    public int3 gag => new int3(y, w, y);
    public int3 gab { get => new int3(y, w, z); set { y = value.x; w = value.y; z = value.z; } }
    public int3 gaa => new int3(y, w, w);
    public int3 brr => new int3(z, x, x);
    public int3 brg { get => new int3(z, x, y); set { z = value.x; x = value.y; y = value.z; } }
    public int3 brb => new int3(z, x, z);
    public int3 bra { get => new int3(z, x, w); set { z = value.x; x = value.y; w = value.z; } }
    public int3 bgr { get => new int3(z, y, x); set { z = value.x; y = value.y; x = value.z; } }
    public int3 bgg => new int3(z, y, y);
    public int3 bgb => new int3(z, y, z);
    public int3 bga { get => new int3(z, y, w); set { z = value.x; y = value.y; w = value.z; } }
    public int3 bbr => new int3(z, z, x);
    public int3 bbg => new int3(z, z, y);
    public int3 bbb => new int3(z, z, z);
    public int3 bba => new int3(z, z, w);
    public int3 bar { get => new int3(z, w, x); set { z = value.x; w = value.y; x = value.z; } }
    public int3 bag { get => new int3(z, w, y); set { z = value.x; w = value.y; y = value.z; } }
    public int3 bab => new int3(z, w, z);
    public int3 baa => new int3(z, w, w);
    public int3 arr => new int3(w, x, x);
    public int3 arg { get => new int3(w, x, y); set { w = value.x; x = value.y; y = value.z; } }
    public int3 arb { get => new int3(w, x, z); set { w = value.x; x = value.y; z = value.z; } }
    public int3 ara => new int3(w, x, w);
    public int3 agr { get => new int3(w, y, x); set { w = value.x; y = value.y; x = value.z; } }
    public int3 agg => new int3(w, y, y);
    public int3 agb { get => new int3(w, y, z); set { w = value.x; y = value.y; z = value.z; } }
    public int3 aga => new int3(w, y, w);
    public int3 abr { get => new int3(w, z, x); set { w = value.x; z = value.y; x = value.z; } }
    public int3 abg { get => new int3(w, z, y); set { w = value.x; z = value.y; y = value.z; } }
    public int3 abb => new int3(w, z, z);
    public int3 aba => new int3(w, z, w);
    public int3 aar => new int3(w, w, x);
    public int3 aag => new int3(w, w, y);
    public int3 aab => new int3(w, w, z);
    public int3 aaa => new int3(w, w, w);
    public int4 rrrr => new int4(x, x, x, x);
    public int4 rrrg => new int4(x, x, x, y);
    public int4 rrrb => new int4(x, x, x, z);
    public int4 rrra => new int4(x, x, x, w);
    public int4 rrgr => new int4(x, x, y, x);
    public int4 rrgg => new int4(x, x, y, y);
    public int4 rrgb => new int4(x, x, y, z);
    public int4 rrga => new int4(x, x, y, w);
    public int4 rrbr => new int4(x, x, z, x);
    public int4 rrbg => new int4(x, x, z, y);
    public int4 rrbb => new int4(x, x, z, z);
    public int4 rrba => new int4(x, x, z, w);
    public int4 rrar => new int4(x, x, w, x);
    public int4 rrag => new int4(x, x, w, y);
    public int4 rrab => new int4(x, x, w, z);
    public int4 rraa => new int4(x, x, w, w);
    public int4 rgrr => new int4(x, y, x, x);
    public int4 rgrg => new int4(x, y, x, y);
    public int4 rgrb => new int4(x, y, x, z);
    public int4 rgra => new int4(x, y, x, w);
    public int4 rggr => new int4(x, y, y, x);
    public int4 rggg => new int4(x, y, y, y);
    public int4 rggb => new int4(x, y, y, z);
    public int4 rgga => new int4(x, y, y, w);
    public int4 rgbr => new int4(x, y, z, x);
    public int4 rgbg => new int4(x, y, z, y);
    public int4 rgbb => new int4(x, y, z, z);
    public int4 rgba { get => new int4(x, y, z, w); set { x = value.x; y = value.y; z = value.z; w = value.w; } }
    public int4 rgar => new int4(x, y, w, x);
    public int4 rgag => new int4(x, y, w, y);
    public int4 rgab { get => new int4(x, y, w, z); set { x = value.x; y = value.y; w = value.z; z = value.w; } }
    public int4 rgaa => new int4(x, y, w, w);
    public int4 rbrr => new int4(x, z, x, x);
    public int4 rbrg => new int4(x, z, x, y);
    public int4 rbrb => new int4(x, z, x, z);
    public int4 rbra => new int4(x, z, x, w);
    public int4 rbgr => new int4(x, z, y, x);
    public int4 rbgg => new int4(x, z, y, y);
    public int4 rbgb => new int4(x, z, y, z);
    public int4 rbga { get => new int4(x, z, y, w); set { x = value.x; z = value.y; y = value.z; w = value.w; } }
    public int4 rbbr => new int4(x, z, z, x);
    public int4 rbbg => new int4(x, z, z, y);
    public int4 rbbb => new int4(x, z, z, z);
    public int4 rbba => new int4(x, z, z, w);
    public int4 rbar => new int4(x, z, w, x);
    public int4 rbag { get => new int4(x, z, w, y); set { x = value.x; z = value.y; w = value.z; y = value.w; } }
    public int4 rbab => new int4(x, z, w, z);
    public int4 rbaa => new int4(x, z, w, w);
    public int4 rarr => new int4(x, w, x, x);
    public int4 rarg => new int4(x, w, x, y);
    public int4 rarb => new int4(x, w, x, z);
    public int4 rara => new int4(x, w, x, w);
    public int4 ragr => new int4(x, w, y, x);
    public int4 ragg => new int4(x, w, y, y);
    public int4 ragb { get => new int4(x, w, y, z); set { x = value.x; w = value.y; y = value.z; z = value.w; } }
    public int4 raga => new int4(x, w, y, w);
    public int4 rabr => new int4(x, w, z, x);
    public int4 rabg { get => new int4(x, w, z, y); set { x = value.x; w = value.y; z = value.z; y = value.w; } }
    public int4 rabb => new int4(x, w, z, z);
    public int4 raba => new int4(x, w, z, w);
    public int4 raar => new int4(x, w, w, x);
    public int4 raag => new int4(x, w, w, y);
    public int4 raab => new int4(x, w, w, z);
    public int4 raaa => new int4(x, w, w, w);
    public int4 grrr => new int4(y, x, x, x);
    public int4 grrg => new int4(y, x, x, y);
    public int4 grrb => new int4(y, x, x, z);
    public int4 grra => new int4(y, x, x, w);
    public int4 grgr => new int4(y, x, y, x);
    public int4 grgg => new int4(y, x, y, y);
    public int4 grgb => new int4(y, x, y, z);
    public int4 grga => new int4(y, x, y, w);
    public int4 grbr => new int4(y, x, z, x);
    public int4 grbg => new int4(y, x, z, y);
    public int4 grbb => new int4(y, x, z, z);
    public int4 grba { get => new int4(y, x, z, w); set { y = value.x; x = value.y; z = value.z; w = value.w; } }
    public int4 grar => new int4(y, x, w, x);
    public int4 grag => new int4(y, x, w, y);
    public int4 grab { get => new int4(y, x, w, z); set { y = value.x; x = value.y; w = value.z; z = value.w; } }
    public int4 graa => new int4(y, x, w, w);
    public int4 ggrr => new int4(y, y, x, x);
    public int4 ggrg => new int4(y, y, x, y);
    public int4 ggrb => new int4(y, y, x, z);
    public int4 ggra => new int4(y, y, x, w);
    public int4 gggr => new int4(y, y, y, x);
    public int4 gggg => new int4(y, y, y, y);
    public int4 gggb => new int4(y, y, y, z);
    public int4 ggga => new int4(y, y, y, w);
    public int4 ggbr => new int4(y, y, z, x);
    public int4 ggbg => new int4(y, y, z, y);
    public int4 ggbb => new int4(y, y, z, z);
    public int4 ggba => new int4(y, y, z, w);
    public int4 ggar => new int4(y, y, w, x);
    public int4 ggag => new int4(y, y, w, y);
    public int4 ggab => new int4(y, y, w, z);
    public int4 ggaa => new int4(y, y, w, w);
    public int4 gbrr => new int4(y, z, x, x);
    public int4 gbrg => new int4(y, z, x, y);
    public int4 gbrb => new int4(y, z, x, z);
    public int4 gbra { get => new int4(y, z, x, w); set { y = value.x; z = value.y; x = value.z; w = value.w; } }
    public int4 gbgr => new int4(y, z, y, x);
    public int4 gbgg => new int4(y, z, y, y);
    public int4 gbgb => new int4(y, z, y, z);
    public int4 gbga => new int4(y, z, y, w);
    public int4 gbbr => new int4(y, z, z, x);
    public int4 gbbg => new int4(y, z, z, y);
    public int4 gbbb => new int4(y, z, z, z);
    public int4 gbba => new int4(y, z, z, w);
    public int4 gbar { get => new int4(y, z, w, x); set { y = value.x; z = value.y; w = value.z; x = value.w; } }
    public int4 gbag => new int4(y, z, w, y);
    public int4 gbab => new int4(y, z, w, z);
    public int4 gbaa => new int4(y, z, w, w);
    public int4 garr => new int4(y, w, x, x);
    public int4 garg => new int4(y, w, x, y);
    public int4 garb { get => new int4(y, w, x, z); set { y = value.x; w = value.y; x = value.z; z = value.w; } }
    public int4 gara => new int4(y, w, x, w);
    public int4 gagr => new int4(y, w, y, x);
    public int4 gagg => new int4(y, w, y, y);
    public int4 gagb => new int4(y, w, y, z);
    public int4 gaga => new int4(y, w, y, w);
    public int4 gabr { get => new int4(y, w, z, x); set { y = value.x; w = value.y; z = value.z; x = value.w; } }
    public int4 gabg => new int4(y, w, z, y);
    public int4 gabb => new int4(y, w, z, z);
    public int4 gaba => new int4(y, w, z, w);
    public int4 gaar => new int4(y, w, w, x);
    public int4 gaag => new int4(y, w, w, y);
    public int4 gaab => new int4(y, w, w, z);
    public int4 gaaa => new int4(y, w, w, w);
    public int4 brrr => new int4(z, x, x, x);
    public int4 brrg => new int4(z, x, x, y);
    public int4 brrb => new int4(z, x, x, z);
    public int4 brra => new int4(z, x, x, w);
    public int4 brgr => new int4(z, x, y, x);
    public int4 brgg => new int4(z, x, y, y);
    public int4 brgb => new int4(z, x, y, z);
    public int4 brga { get => new int4(z, x, y, w); set { z = value.x; x = value.y; y = value.z; w = value.w; } }
    public int4 brbr => new int4(z, x, z, x);
    public int4 brbg => new int4(z, x, z, y);
    public int4 brbb => new int4(z, x, z, z);
    public int4 brba => new int4(z, x, z, w);
    public int4 brar => new int4(z, x, w, x);
    public int4 brag { get => new int4(z, x, w, y); set { z = value.x; x = value.y; w = value.z; y = value.w; } }
    public int4 brab => new int4(z, x, w, z);
    public int4 braa => new int4(z, x, w, w);
    public int4 bgrr => new int4(z, y, x, x);
    public int4 bgrg => new int4(z, y, x, y);
    public int4 bgrb => new int4(z, y, x, z);
    public int4 bgra { get => new int4(z, y, x, w); set { z = value.x; y = value.y; x = value.z; w = value.w; } }
    public int4 bggr => new int4(z, y, y, x);
    public int4 bggg => new int4(z, y, y, y);
    public int4 bggb => new int4(z, y, y, z);
    public int4 bgga => new int4(z, y, y, w);
    public int4 bgbr => new int4(z, y, z, x);
    public int4 bgbg => new int4(z, y, z, y);
    public int4 bgbb => new int4(z, y, z, z);
    public int4 bgba => new int4(z, y, z, w);
    public int4 bgar { get => new int4(z, y, w, x); set { z = value.x; y = value.y; w = value.z; x = value.w; } }
    public int4 bgag => new int4(z, y, w, y);
    public int4 bgab => new int4(z, y, w, z);
    public int4 bgaa => new int4(z, y, w, w);
    public int4 bbrr => new int4(z, z, x, x);
    public int4 bbrg => new int4(z, z, x, y);
    public int4 bbrb => new int4(z, z, x, z);
    public int4 bbra => new int4(z, z, x, w);
    public int4 bbgr => new int4(z, z, y, x);
    public int4 bbgg => new int4(z, z, y, y);
    public int4 bbgb => new int4(z, z, y, z);
    public int4 bbga => new int4(z, z, y, w);
    public int4 bbbr => new int4(z, z, z, x);
    public int4 bbbg => new int4(z, z, z, y);
    public int4 bbbb => new int4(z, z, z, z);
    public int4 bbba => new int4(z, z, z, w);
    public int4 bbar => new int4(z, z, w, x);
    public int4 bbag => new int4(z, z, w, y);
    public int4 bbab => new int4(z, z, w, z);
    public int4 bbaa => new int4(z, z, w, w);
    public int4 barr => new int4(z, w, x, x);
    public int4 barg { get => new int4(z, w, x, y); set { z = value.x; w = value.y; x = value.z; y = value.w; } }
    public int4 barb => new int4(z, w, x, z);
    public int4 bara => new int4(z, w, x, w);
    public int4 bagr { get => new int4(z, w, y, x); set { z = value.x; w = value.y; y = value.z; x = value.w; } }
    public int4 bagg => new int4(z, w, y, y);
    public int4 bagb => new int4(z, w, y, z);
    public int4 baga => new int4(z, w, y, w);
    public int4 babr => new int4(z, w, z, x);
    public int4 babg => new int4(z, w, z, y);
    public int4 babb => new int4(z, w, z, z);
    public int4 baba => new int4(z, w, z, w);
    public int4 baar => new int4(z, w, w, x);
    public int4 baag => new int4(z, w, w, y);
    public int4 baab => new int4(z, w, w, z);
    public int4 baaa => new int4(z, w, w, w);
    public int4 arrr => new int4(w, x, x, x);
    public int4 arrg => new int4(w, x, x, y);
    public int4 arrb => new int4(w, x, x, z);
    public int4 arra => new int4(w, x, x, w);
    public int4 argr => new int4(w, x, y, x);
    public int4 argg => new int4(w, x, y, y);
    public int4 argb { get => new int4(w, x, y, z); set { w = value.x; x = value.y; y = value.z; z = value.w; } }
    public int4 arga => new int4(w, x, y, w);
    public int4 arbr => new int4(w, x, z, x);
    public int4 arbg { get => new int4(w, x, z, y); set { w = value.x; x = value.y; z = value.z; y = value.w; } }
    public int4 arbb => new int4(w, x, z, z);
    public int4 arba => new int4(w, x, z, w);
    public int4 arar => new int4(w, x, w, x);
    public int4 arag => new int4(w, x, w, y);
    public int4 arab => new int4(w, x, w, z);
    public int4 araa => new int4(w, x, w, w);
    public int4 agrr => new int4(w, y, x, x);
    public int4 agrg => new int4(w, y, x, y);
    public int4 agrb { get => new int4(w, y, x, z); set { w = value.x; y = value.y; x = value.z; z = value.w; } }
    public int4 agra => new int4(w, y, x, w);
    public int4 aggr => new int4(w, y, y, x);
    public int4 aggg => new int4(w, y, y, y);
    public int4 aggb => new int4(w, y, y, z);
    public int4 agga => new int4(w, y, y, w);
    public int4 agbr { get => new int4(w, y, z, x); set { w = value.x; y = value.y; z = value.z; x = value.w; } }
    public int4 agbg => new int4(w, y, z, y);
    public int4 agbb => new int4(w, y, z, z);
    public int4 agba => new int4(w, y, z, w);
    public int4 agar => new int4(w, y, w, x);
    public int4 agag => new int4(w, y, w, y);
    public int4 agab => new int4(w, y, w, z);
    public int4 agaa => new int4(w, y, w, w);
    public int4 abrr => new int4(w, z, x, x);
    public int4 abrg { get => new int4(w, z, x, y); set { w = value.x; z = value.y; x = value.z; y = value.w; } }
    public int4 abrb => new int4(w, z, x, z);
    public int4 abra => new int4(w, z, x, w);
    public int4 abgr { get => new int4(w, z, y, x); set { w = value.x; z = value.y; y = value.z; x = value.w; } }
    public int4 abgg => new int4(w, z, y, y);
    public int4 abgb => new int4(w, z, y, z);
    public int4 abga => new int4(w, z, y, w);
    public int4 abbr => new int4(w, z, z, x);
    public int4 abbg => new int4(w, z, z, y);
    public int4 abbb => new int4(w, z, z, z);
    public int4 abba => new int4(w, z, z, w);
    public int4 abar => new int4(w, z, w, x);
    public int4 abag => new int4(w, z, w, y);
    public int4 abab => new int4(w, z, w, z);
    public int4 abaa => new int4(w, z, w, w);
    public int4 aarr => new int4(w, w, x, x);
    public int4 aarg => new int4(w, w, x, y);
    public int4 aarb => new int4(w, w, x, z);
    public int4 aara => new int4(w, w, x, w);
    public int4 aagr => new int4(w, w, y, x);
    public int4 aagg => new int4(w, w, y, y);
    public int4 aagb => new int4(w, w, y, z);
    public int4 aaga => new int4(w, w, y, w);
    public int4 aabr => new int4(w, w, z, x);
    public int4 aabg => new int4(w, w, z, y);
    public int4 aabb => new int4(w, w, z, z);
    public int4 aaba => new int4(w, w, z, w);
    public int4 aaar => new int4(w, w, w, x);
    public int4 aaag => new int4(w, w, w, y);
    public int4 aaab => new int4(w, w, w, z);
    public int4 aaaa => new int4(w, w, w, w);
}
