// <auto-generated>
// Written by tools/gen_hlsl_types.py. Do not edit; edit the script and run it again.
// </auto-generated>
#nullable enable
#pragma warning disable IDE1006, CS1591
using System;
using System.Runtime.InteropServices;

namespace Csl.Hlsl;

/// <summary>HLSL uint4: 4 components of uint. Runs on the GPU; the C# operations exist so shader code type-checks and can be unit tested.</summary>
[StructLayout(LayoutKind.Sequential)]
public struct uint4 : IEquatable<uint4>
{
    public uint x, y, z, w;
    public uint4(uint x, uint y, uint z, uint w) { this.x = x; this.y = y; this.z = z; this.w = w; }
    public uint4(uint v) { x = v; y = v; z = v; w = v; }
    public uint4(uint3 xyz, uint w) { x = xyz.x; y = xyz.y; z = xyz.z; this.w = w; }
    public uint4(uint x, uint3 yzw) { this.x = x; y = yzw.x; z = yzw.y; w = yzw.z; }
    public uint4(uint2 xy, uint2 zw) { x = xy.x; y = xy.y; z = zw.x; w = zw.y; }
    public uint4(uint2 xy, uint z, uint w) { x = xy.x; y = xy.y; this.z = z; this.w = w; }
    public uint4(float4 v) { x = (uint)v.x; y = (uint)v.y; z = (uint)v.z; w = (uint)v.w; }
    public static explicit operator uint4(float4 v) => new uint4(v);
    public uint4(int4 v) { x = (uint)v.x; y = (uint)v.y; z = (uint)v.z; w = (uint)v.w; }
    public static explicit operator uint4(int4 v) => new uint4(v);
    public static implicit operator uint4(uint v) => new uint4(v);
    public uint this[int i]
    {
        get => i switch { 0 => x, 1 => y, 2 => z, 3 => w, _ => throw new IndexOutOfRangeException() };
        set { switch (i) { case 0: x = value; break; case 1: y = value; break; case 2: z = value; break; case 3: w = value; break; default: throw new IndexOutOfRangeException(); } }
    }
    public static uint4 operator +(uint4 a, uint4 b) => new uint4((uint)(a.x + b.x), (uint)(a.y + b.y), (uint)(a.z + b.z), (uint)(a.w + b.w));
    public static uint4 operator +(uint4 a, uint b) => new uint4((uint)(a.x + b), (uint)(a.y + b), (uint)(a.z + b), (uint)(a.w + b));
    public static uint4 operator +(uint a, uint4 b) => new uint4((uint)(a + b.x), (uint)(a + b.y), (uint)(a + b.z), (uint)(a + b.w));
    public static uint4 operator -(uint4 a, uint4 b) => new uint4((uint)(a.x - b.x), (uint)(a.y - b.y), (uint)(a.z - b.z), (uint)(a.w - b.w));
    public static uint4 operator -(uint4 a, uint b) => new uint4((uint)(a.x - b), (uint)(a.y - b), (uint)(a.z - b), (uint)(a.w - b));
    public static uint4 operator -(uint a, uint4 b) => new uint4((uint)(a - b.x), (uint)(a - b.y), (uint)(a - b.z), (uint)(a - b.w));
    public static uint4 operator *(uint4 a, uint4 b) => new uint4((uint)(a.x * b.x), (uint)(a.y * b.y), (uint)(a.z * b.z), (uint)(a.w * b.w));
    public static uint4 operator *(uint4 a, uint b) => new uint4((uint)(a.x * b), (uint)(a.y * b), (uint)(a.z * b), (uint)(a.w * b));
    public static uint4 operator *(uint a, uint4 b) => new uint4((uint)(a * b.x), (uint)(a * b.y), (uint)(a * b.z), (uint)(a * b.w));
    public static uint4 operator /(uint4 a, uint4 b) => new uint4((uint)(a.x / b.x), (uint)(a.y / b.y), (uint)(a.z / b.z), (uint)(a.w / b.w));
    public static uint4 operator /(uint4 a, uint b) => new uint4((uint)(a.x / b), (uint)(a.y / b), (uint)(a.z / b), (uint)(a.w / b));
    public static uint4 operator /(uint a, uint4 b) => new uint4((uint)(a / b.x), (uint)(a / b.y), (uint)(a / b.z), (uint)(a / b.w));
    public static uint4 operator %(uint4 a, uint4 b) => new uint4((uint)(a.x % b.x), (uint)(a.y % b.y), (uint)(a.z % b.z), (uint)(a.w % b.w));
    public static uint4 operator %(uint4 a, uint b) => new uint4((uint)(a.x % b), (uint)(a.y % b), (uint)(a.z % b), (uint)(a.w % b));
    public static uint4 operator %(uint a, uint4 b) => new uint4((uint)(a % b.x), (uint)(a % b.y), (uint)(a % b.z), (uint)(a % b.w));
    public static uint4 operator +(uint4 a) => a;
    public static uint4 operator ++(uint4 a) => new uint4((uint)(a.x + 1u), (uint)(a.y + 1u), (uint)(a.z + 1u), (uint)(a.w + 1u));
    public static uint4 operator --(uint4 a) => new uint4((uint)(a.x - 1u), (uint)(a.y - 1u), (uint)(a.z - 1u), (uint)(a.w - 1u));
    public static bool4 operator <(uint4 a, uint4 b) => new bool4(a.x < b.x, a.y < b.y, a.z < b.z, a.w < b.w);
    public static bool4 operator <(uint4 a, uint b) => new bool4(a.x < b, a.y < b, a.z < b, a.w < b);
    public static bool4 operator <(uint a, uint4 b) => new bool4(a < b.x, a < b.y, a < b.z, a < b.w);
    public static bool4 operator >(uint4 a, uint4 b) => new bool4(a.x > b.x, a.y > b.y, a.z > b.z, a.w > b.w);
    public static bool4 operator >(uint4 a, uint b) => new bool4(a.x > b, a.y > b, a.z > b, a.w > b);
    public static bool4 operator >(uint a, uint4 b) => new bool4(a > b.x, a > b.y, a > b.z, a > b.w);
    public static bool4 operator <=(uint4 a, uint4 b) => new bool4(a.x <= b.x, a.y <= b.y, a.z <= b.z, a.w <= b.w);
    public static bool4 operator <=(uint4 a, uint b) => new bool4(a.x <= b, a.y <= b, a.z <= b, a.w <= b);
    public static bool4 operator <=(uint a, uint4 b) => new bool4(a <= b.x, a <= b.y, a <= b.z, a <= b.w);
    public static bool4 operator >=(uint4 a, uint4 b) => new bool4(a.x >= b.x, a.y >= b.y, a.z >= b.z, a.w >= b.w);
    public static bool4 operator >=(uint4 a, uint b) => new bool4(a.x >= b, a.y >= b, a.z >= b, a.w >= b);
    public static bool4 operator >=(uint a, uint4 b) => new bool4(a >= b.x, a >= b.y, a >= b.z, a >= b.w);
    public static uint4 operator &(uint4 a, uint4 b) => new uint4((uint)(a.x & b.x), (uint)(a.y & b.y), (uint)(a.z & b.z), (uint)(a.w & b.w));
    public static uint4 operator &(uint4 a, uint b) => new uint4((uint)(a.x & b), (uint)(a.y & b), (uint)(a.z & b), (uint)(a.w & b));
    public static uint4 operator |(uint4 a, uint4 b) => new uint4((uint)(a.x | b.x), (uint)(a.y | b.y), (uint)(a.z | b.z), (uint)(a.w | b.w));
    public static uint4 operator |(uint4 a, uint b) => new uint4((uint)(a.x | b), (uint)(a.y | b), (uint)(a.z | b), (uint)(a.w | b));
    public static uint4 operator ^(uint4 a, uint4 b) => new uint4((uint)(a.x ^ b.x), (uint)(a.y ^ b.y), (uint)(a.z ^ b.z), (uint)(a.w ^ b.w));
    public static uint4 operator ^(uint4 a, uint b) => new uint4((uint)(a.x ^ b), (uint)(a.y ^ b), (uint)(a.z ^ b), (uint)(a.w ^ b));
    public static uint4 operator <<(uint4 a, int b) => new uint4((uint)(a.x << b), (uint)(a.y << b), (uint)(a.z << b), (uint)(a.w << b));
    public static uint4 operator >>(uint4 a, int b) => new uint4((uint)(a.x >> b), (uint)(a.y >> b), (uint)(a.z >> b), (uint)(a.w >> b));
    public static uint4 operator ~(uint4 a) => new uint4((uint)(~a.x), (uint)(~a.y), (uint)(~a.z), (uint)(~a.w));
    public static bool4 operator ==(uint4 a, uint4 b) => new bool4(a.x == b.x, a.y == b.y, a.z == b.z, a.w == b.w);
    public static bool4 operator !=(uint4 a, uint4 b) => new bool4(a.x != b.x, a.y != b.y, a.z != b.z, a.w != b.w);
    public static bool4 operator ==(uint4 a, uint b) => new bool4(a.x == b, a.y == b, a.z == b, a.w == b);
    public static bool4 operator !=(uint4 a, uint b) => new bool4(a.x != b, a.y != b, a.z != b, a.w != b);
    public bool Equals(uint4 other) => x == other.x && y == other.y && z == other.z && w == other.w;
    public override bool Equals(object? obj) => obj is uint4 other && Equals(other);
    public override int GetHashCode() => HashCode.Combine(x, y, z, w);
    public override string ToString() => $"uint4({x}, {y}, {z}, {w})";

    // Swizzles, xyzw and rgba. Setters only where no component repeats.
    public uint2 xx => new uint2(x, x);
    public uint2 xy { get => new uint2(x, y); set { x = value.x; y = value.y; } }
    public uint2 xz { get => new uint2(x, z); set { x = value.x; z = value.y; } }
    public uint2 xw { get => new uint2(x, w); set { x = value.x; w = value.y; } }
    public uint2 yx { get => new uint2(y, x); set { y = value.x; x = value.y; } }
    public uint2 yy => new uint2(y, y);
    public uint2 yz { get => new uint2(y, z); set { y = value.x; z = value.y; } }
    public uint2 yw { get => new uint2(y, w); set { y = value.x; w = value.y; } }
    public uint2 zx { get => new uint2(z, x); set { z = value.x; x = value.y; } }
    public uint2 zy { get => new uint2(z, y); set { z = value.x; y = value.y; } }
    public uint2 zz => new uint2(z, z);
    public uint2 zw { get => new uint2(z, w); set { z = value.x; w = value.y; } }
    public uint2 wx { get => new uint2(w, x); set { w = value.x; x = value.y; } }
    public uint2 wy { get => new uint2(w, y); set { w = value.x; y = value.y; } }
    public uint2 wz { get => new uint2(w, z); set { w = value.x; z = value.y; } }
    public uint2 ww => new uint2(w, w);
    public uint3 xxx => new uint3(x, x, x);
    public uint3 xxy => new uint3(x, x, y);
    public uint3 xxz => new uint3(x, x, z);
    public uint3 xxw => new uint3(x, x, w);
    public uint3 xyx => new uint3(x, y, x);
    public uint3 xyy => new uint3(x, y, y);
    public uint3 xyz { get => new uint3(x, y, z); set { x = value.x; y = value.y; z = value.z; } }
    public uint3 xyw { get => new uint3(x, y, w); set { x = value.x; y = value.y; w = value.z; } }
    public uint3 xzx => new uint3(x, z, x);
    public uint3 xzy { get => new uint3(x, z, y); set { x = value.x; z = value.y; y = value.z; } }
    public uint3 xzz => new uint3(x, z, z);
    public uint3 xzw { get => new uint3(x, z, w); set { x = value.x; z = value.y; w = value.z; } }
    public uint3 xwx => new uint3(x, w, x);
    public uint3 xwy { get => new uint3(x, w, y); set { x = value.x; w = value.y; y = value.z; } }
    public uint3 xwz { get => new uint3(x, w, z); set { x = value.x; w = value.y; z = value.z; } }
    public uint3 xww => new uint3(x, w, w);
    public uint3 yxx => new uint3(y, x, x);
    public uint3 yxy => new uint3(y, x, y);
    public uint3 yxz { get => new uint3(y, x, z); set { y = value.x; x = value.y; z = value.z; } }
    public uint3 yxw { get => new uint3(y, x, w); set { y = value.x; x = value.y; w = value.z; } }
    public uint3 yyx => new uint3(y, y, x);
    public uint3 yyy => new uint3(y, y, y);
    public uint3 yyz => new uint3(y, y, z);
    public uint3 yyw => new uint3(y, y, w);
    public uint3 yzx { get => new uint3(y, z, x); set { y = value.x; z = value.y; x = value.z; } }
    public uint3 yzy => new uint3(y, z, y);
    public uint3 yzz => new uint3(y, z, z);
    public uint3 yzw { get => new uint3(y, z, w); set { y = value.x; z = value.y; w = value.z; } }
    public uint3 ywx { get => new uint3(y, w, x); set { y = value.x; w = value.y; x = value.z; } }
    public uint3 ywy => new uint3(y, w, y);
    public uint3 ywz { get => new uint3(y, w, z); set { y = value.x; w = value.y; z = value.z; } }
    public uint3 yww => new uint3(y, w, w);
    public uint3 zxx => new uint3(z, x, x);
    public uint3 zxy { get => new uint3(z, x, y); set { z = value.x; x = value.y; y = value.z; } }
    public uint3 zxz => new uint3(z, x, z);
    public uint3 zxw { get => new uint3(z, x, w); set { z = value.x; x = value.y; w = value.z; } }
    public uint3 zyx { get => new uint3(z, y, x); set { z = value.x; y = value.y; x = value.z; } }
    public uint3 zyy => new uint3(z, y, y);
    public uint3 zyz => new uint3(z, y, z);
    public uint3 zyw { get => new uint3(z, y, w); set { z = value.x; y = value.y; w = value.z; } }
    public uint3 zzx => new uint3(z, z, x);
    public uint3 zzy => new uint3(z, z, y);
    public uint3 zzz => new uint3(z, z, z);
    public uint3 zzw => new uint3(z, z, w);
    public uint3 zwx { get => new uint3(z, w, x); set { z = value.x; w = value.y; x = value.z; } }
    public uint3 zwy { get => new uint3(z, w, y); set { z = value.x; w = value.y; y = value.z; } }
    public uint3 zwz => new uint3(z, w, z);
    public uint3 zww => new uint3(z, w, w);
    public uint3 wxx => new uint3(w, x, x);
    public uint3 wxy { get => new uint3(w, x, y); set { w = value.x; x = value.y; y = value.z; } }
    public uint3 wxz { get => new uint3(w, x, z); set { w = value.x; x = value.y; z = value.z; } }
    public uint3 wxw => new uint3(w, x, w);
    public uint3 wyx { get => new uint3(w, y, x); set { w = value.x; y = value.y; x = value.z; } }
    public uint3 wyy => new uint3(w, y, y);
    public uint3 wyz { get => new uint3(w, y, z); set { w = value.x; y = value.y; z = value.z; } }
    public uint3 wyw => new uint3(w, y, w);
    public uint3 wzx { get => new uint3(w, z, x); set { w = value.x; z = value.y; x = value.z; } }
    public uint3 wzy { get => new uint3(w, z, y); set { w = value.x; z = value.y; y = value.z; } }
    public uint3 wzz => new uint3(w, z, z);
    public uint3 wzw => new uint3(w, z, w);
    public uint3 wwx => new uint3(w, w, x);
    public uint3 wwy => new uint3(w, w, y);
    public uint3 wwz => new uint3(w, w, z);
    public uint3 www => new uint3(w, w, w);
    public uint4 xxxx => new uint4(x, x, x, x);
    public uint4 xxxy => new uint4(x, x, x, y);
    public uint4 xxxz => new uint4(x, x, x, z);
    public uint4 xxxw => new uint4(x, x, x, w);
    public uint4 xxyx => new uint4(x, x, y, x);
    public uint4 xxyy => new uint4(x, x, y, y);
    public uint4 xxyz => new uint4(x, x, y, z);
    public uint4 xxyw => new uint4(x, x, y, w);
    public uint4 xxzx => new uint4(x, x, z, x);
    public uint4 xxzy => new uint4(x, x, z, y);
    public uint4 xxzz => new uint4(x, x, z, z);
    public uint4 xxzw => new uint4(x, x, z, w);
    public uint4 xxwx => new uint4(x, x, w, x);
    public uint4 xxwy => new uint4(x, x, w, y);
    public uint4 xxwz => new uint4(x, x, w, z);
    public uint4 xxww => new uint4(x, x, w, w);
    public uint4 xyxx => new uint4(x, y, x, x);
    public uint4 xyxy => new uint4(x, y, x, y);
    public uint4 xyxz => new uint4(x, y, x, z);
    public uint4 xyxw => new uint4(x, y, x, w);
    public uint4 xyyx => new uint4(x, y, y, x);
    public uint4 xyyy => new uint4(x, y, y, y);
    public uint4 xyyz => new uint4(x, y, y, z);
    public uint4 xyyw => new uint4(x, y, y, w);
    public uint4 xyzx => new uint4(x, y, z, x);
    public uint4 xyzy => new uint4(x, y, z, y);
    public uint4 xyzz => new uint4(x, y, z, z);
    public uint4 xyzw { get => new uint4(x, y, z, w); set { x = value.x; y = value.y; z = value.z; w = value.w; } }
    public uint4 xywx => new uint4(x, y, w, x);
    public uint4 xywy => new uint4(x, y, w, y);
    public uint4 xywz { get => new uint4(x, y, w, z); set { x = value.x; y = value.y; w = value.z; z = value.w; } }
    public uint4 xyww => new uint4(x, y, w, w);
    public uint4 xzxx => new uint4(x, z, x, x);
    public uint4 xzxy => new uint4(x, z, x, y);
    public uint4 xzxz => new uint4(x, z, x, z);
    public uint4 xzxw => new uint4(x, z, x, w);
    public uint4 xzyx => new uint4(x, z, y, x);
    public uint4 xzyy => new uint4(x, z, y, y);
    public uint4 xzyz => new uint4(x, z, y, z);
    public uint4 xzyw { get => new uint4(x, z, y, w); set { x = value.x; z = value.y; y = value.z; w = value.w; } }
    public uint4 xzzx => new uint4(x, z, z, x);
    public uint4 xzzy => new uint4(x, z, z, y);
    public uint4 xzzz => new uint4(x, z, z, z);
    public uint4 xzzw => new uint4(x, z, z, w);
    public uint4 xzwx => new uint4(x, z, w, x);
    public uint4 xzwy { get => new uint4(x, z, w, y); set { x = value.x; z = value.y; w = value.z; y = value.w; } }
    public uint4 xzwz => new uint4(x, z, w, z);
    public uint4 xzww => new uint4(x, z, w, w);
    public uint4 xwxx => new uint4(x, w, x, x);
    public uint4 xwxy => new uint4(x, w, x, y);
    public uint4 xwxz => new uint4(x, w, x, z);
    public uint4 xwxw => new uint4(x, w, x, w);
    public uint4 xwyx => new uint4(x, w, y, x);
    public uint4 xwyy => new uint4(x, w, y, y);
    public uint4 xwyz { get => new uint4(x, w, y, z); set { x = value.x; w = value.y; y = value.z; z = value.w; } }
    public uint4 xwyw => new uint4(x, w, y, w);
    public uint4 xwzx => new uint4(x, w, z, x);
    public uint4 xwzy { get => new uint4(x, w, z, y); set { x = value.x; w = value.y; z = value.z; y = value.w; } }
    public uint4 xwzz => new uint4(x, w, z, z);
    public uint4 xwzw => new uint4(x, w, z, w);
    public uint4 xwwx => new uint4(x, w, w, x);
    public uint4 xwwy => new uint4(x, w, w, y);
    public uint4 xwwz => new uint4(x, w, w, z);
    public uint4 xwww => new uint4(x, w, w, w);
    public uint4 yxxx => new uint4(y, x, x, x);
    public uint4 yxxy => new uint4(y, x, x, y);
    public uint4 yxxz => new uint4(y, x, x, z);
    public uint4 yxxw => new uint4(y, x, x, w);
    public uint4 yxyx => new uint4(y, x, y, x);
    public uint4 yxyy => new uint4(y, x, y, y);
    public uint4 yxyz => new uint4(y, x, y, z);
    public uint4 yxyw => new uint4(y, x, y, w);
    public uint4 yxzx => new uint4(y, x, z, x);
    public uint4 yxzy => new uint4(y, x, z, y);
    public uint4 yxzz => new uint4(y, x, z, z);
    public uint4 yxzw { get => new uint4(y, x, z, w); set { y = value.x; x = value.y; z = value.z; w = value.w; } }
    public uint4 yxwx => new uint4(y, x, w, x);
    public uint4 yxwy => new uint4(y, x, w, y);
    public uint4 yxwz { get => new uint4(y, x, w, z); set { y = value.x; x = value.y; w = value.z; z = value.w; } }
    public uint4 yxww => new uint4(y, x, w, w);
    public uint4 yyxx => new uint4(y, y, x, x);
    public uint4 yyxy => new uint4(y, y, x, y);
    public uint4 yyxz => new uint4(y, y, x, z);
    public uint4 yyxw => new uint4(y, y, x, w);
    public uint4 yyyx => new uint4(y, y, y, x);
    public uint4 yyyy => new uint4(y, y, y, y);
    public uint4 yyyz => new uint4(y, y, y, z);
    public uint4 yyyw => new uint4(y, y, y, w);
    public uint4 yyzx => new uint4(y, y, z, x);
    public uint4 yyzy => new uint4(y, y, z, y);
    public uint4 yyzz => new uint4(y, y, z, z);
    public uint4 yyzw => new uint4(y, y, z, w);
    public uint4 yywx => new uint4(y, y, w, x);
    public uint4 yywy => new uint4(y, y, w, y);
    public uint4 yywz => new uint4(y, y, w, z);
    public uint4 yyww => new uint4(y, y, w, w);
    public uint4 yzxx => new uint4(y, z, x, x);
    public uint4 yzxy => new uint4(y, z, x, y);
    public uint4 yzxz => new uint4(y, z, x, z);
    public uint4 yzxw { get => new uint4(y, z, x, w); set { y = value.x; z = value.y; x = value.z; w = value.w; } }
    public uint4 yzyx => new uint4(y, z, y, x);
    public uint4 yzyy => new uint4(y, z, y, y);
    public uint4 yzyz => new uint4(y, z, y, z);
    public uint4 yzyw => new uint4(y, z, y, w);
    public uint4 yzzx => new uint4(y, z, z, x);
    public uint4 yzzy => new uint4(y, z, z, y);
    public uint4 yzzz => new uint4(y, z, z, z);
    public uint4 yzzw => new uint4(y, z, z, w);
    public uint4 yzwx { get => new uint4(y, z, w, x); set { y = value.x; z = value.y; w = value.z; x = value.w; } }
    public uint4 yzwy => new uint4(y, z, w, y);
    public uint4 yzwz => new uint4(y, z, w, z);
    public uint4 yzww => new uint4(y, z, w, w);
    public uint4 ywxx => new uint4(y, w, x, x);
    public uint4 ywxy => new uint4(y, w, x, y);
    public uint4 ywxz { get => new uint4(y, w, x, z); set { y = value.x; w = value.y; x = value.z; z = value.w; } }
    public uint4 ywxw => new uint4(y, w, x, w);
    public uint4 ywyx => new uint4(y, w, y, x);
    public uint4 ywyy => new uint4(y, w, y, y);
    public uint4 ywyz => new uint4(y, w, y, z);
    public uint4 ywyw => new uint4(y, w, y, w);
    public uint4 ywzx { get => new uint4(y, w, z, x); set { y = value.x; w = value.y; z = value.z; x = value.w; } }
    public uint4 ywzy => new uint4(y, w, z, y);
    public uint4 ywzz => new uint4(y, w, z, z);
    public uint4 ywzw => new uint4(y, w, z, w);
    public uint4 ywwx => new uint4(y, w, w, x);
    public uint4 ywwy => new uint4(y, w, w, y);
    public uint4 ywwz => new uint4(y, w, w, z);
    public uint4 ywww => new uint4(y, w, w, w);
    public uint4 zxxx => new uint4(z, x, x, x);
    public uint4 zxxy => new uint4(z, x, x, y);
    public uint4 zxxz => new uint4(z, x, x, z);
    public uint4 zxxw => new uint4(z, x, x, w);
    public uint4 zxyx => new uint4(z, x, y, x);
    public uint4 zxyy => new uint4(z, x, y, y);
    public uint4 zxyz => new uint4(z, x, y, z);
    public uint4 zxyw { get => new uint4(z, x, y, w); set { z = value.x; x = value.y; y = value.z; w = value.w; } }
    public uint4 zxzx => new uint4(z, x, z, x);
    public uint4 zxzy => new uint4(z, x, z, y);
    public uint4 zxzz => new uint4(z, x, z, z);
    public uint4 zxzw => new uint4(z, x, z, w);
    public uint4 zxwx => new uint4(z, x, w, x);
    public uint4 zxwy { get => new uint4(z, x, w, y); set { z = value.x; x = value.y; w = value.z; y = value.w; } }
    public uint4 zxwz => new uint4(z, x, w, z);
    public uint4 zxww => new uint4(z, x, w, w);
    public uint4 zyxx => new uint4(z, y, x, x);
    public uint4 zyxy => new uint4(z, y, x, y);
    public uint4 zyxz => new uint4(z, y, x, z);
    public uint4 zyxw { get => new uint4(z, y, x, w); set { z = value.x; y = value.y; x = value.z; w = value.w; } }
    public uint4 zyyx => new uint4(z, y, y, x);
    public uint4 zyyy => new uint4(z, y, y, y);
    public uint4 zyyz => new uint4(z, y, y, z);
    public uint4 zyyw => new uint4(z, y, y, w);
    public uint4 zyzx => new uint4(z, y, z, x);
    public uint4 zyzy => new uint4(z, y, z, y);
    public uint4 zyzz => new uint4(z, y, z, z);
    public uint4 zyzw => new uint4(z, y, z, w);
    public uint4 zywx { get => new uint4(z, y, w, x); set { z = value.x; y = value.y; w = value.z; x = value.w; } }
    public uint4 zywy => new uint4(z, y, w, y);
    public uint4 zywz => new uint4(z, y, w, z);
    public uint4 zyww => new uint4(z, y, w, w);
    public uint4 zzxx => new uint4(z, z, x, x);
    public uint4 zzxy => new uint4(z, z, x, y);
    public uint4 zzxz => new uint4(z, z, x, z);
    public uint4 zzxw => new uint4(z, z, x, w);
    public uint4 zzyx => new uint4(z, z, y, x);
    public uint4 zzyy => new uint4(z, z, y, y);
    public uint4 zzyz => new uint4(z, z, y, z);
    public uint4 zzyw => new uint4(z, z, y, w);
    public uint4 zzzx => new uint4(z, z, z, x);
    public uint4 zzzy => new uint4(z, z, z, y);
    public uint4 zzzz => new uint4(z, z, z, z);
    public uint4 zzzw => new uint4(z, z, z, w);
    public uint4 zzwx => new uint4(z, z, w, x);
    public uint4 zzwy => new uint4(z, z, w, y);
    public uint4 zzwz => new uint4(z, z, w, z);
    public uint4 zzww => new uint4(z, z, w, w);
    public uint4 zwxx => new uint4(z, w, x, x);
    public uint4 zwxy { get => new uint4(z, w, x, y); set { z = value.x; w = value.y; x = value.z; y = value.w; } }
    public uint4 zwxz => new uint4(z, w, x, z);
    public uint4 zwxw => new uint4(z, w, x, w);
    public uint4 zwyx { get => new uint4(z, w, y, x); set { z = value.x; w = value.y; y = value.z; x = value.w; } }
    public uint4 zwyy => new uint4(z, w, y, y);
    public uint4 zwyz => new uint4(z, w, y, z);
    public uint4 zwyw => new uint4(z, w, y, w);
    public uint4 zwzx => new uint4(z, w, z, x);
    public uint4 zwzy => new uint4(z, w, z, y);
    public uint4 zwzz => new uint4(z, w, z, z);
    public uint4 zwzw => new uint4(z, w, z, w);
    public uint4 zwwx => new uint4(z, w, w, x);
    public uint4 zwwy => new uint4(z, w, w, y);
    public uint4 zwwz => new uint4(z, w, w, z);
    public uint4 zwww => new uint4(z, w, w, w);
    public uint4 wxxx => new uint4(w, x, x, x);
    public uint4 wxxy => new uint4(w, x, x, y);
    public uint4 wxxz => new uint4(w, x, x, z);
    public uint4 wxxw => new uint4(w, x, x, w);
    public uint4 wxyx => new uint4(w, x, y, x);
    public uint4 wxyy => new uint4(w, x, y, y);
    public uint4 wxyz { get => new uint4(w, x, y, z); set { w = value.x; x = value.y; y = value.z; z = value.w; } }
    public uint4 wxyw => new uint4(w, x, y, w);
    public uint4 wxzx => new uint4(w, x, z, x);
    public uint4 wxzy { get => new uint4(w, x, z, y); set { w = value.x; x = value.y; z = value.z; y = value.w; } }
    public uint4 wxzz => new uint4(w, x, z, z);
    public uint4 wxzw => new uint4(w, x, z, w);
    public uint4 wxwx => new uint4(w, x, w, x);
    public uint4 wxwy => new uint4(w, x, w, y);
    public uint4 wxwz => new uint4(w, x, w, z);
    public uint4 wxww => new uint4(w, x, w, w);
    public uint4 wyxx => new uint4(w, y, x, x);
    public uint4 wyxy => new uint4(w, y, x, y);
    public uint4 wyxz { get => new uint4(w, y, x, z); set { w = value.x; y = value.y; x = value.z; z = value.w; } }
    public uint4 wyxw => new uint4(w, y, x, w);
    public uint4 wyyx => new uint4(w, y, y, x);
    public uint4 wyyy => new uint4(w, y, y, y);
    public uint4 wyyz => new uint4(w, y, y, z);
    public uint4 wyyw => new uint4(w, y, y, w);
    public uint4 wyzx { get => new uint4(w, y, z, x); set { w = value.x; y = value.y; z = value.z; x = value.w; } }
    public uint4 wyzy => new uint4(w, y, z, y);
    public uint4 wyzz => new uint4(w, y, z, z);
    public uint4 wyzw => new uint4(w, y, z, w);
    public uint4 wywx => new uint4(w, y, w, x);
    public uint4 wywy => new uint4(w, y, w, y);
    public uint4 wywz => new uint4(w, y, w, z);
    public uint4 wyww => new uint4(w, y, w, w);
    public uint4 wzxx => new uint4(w, z, x, x);
    public uint4 wzxy { get => new uint4(w, z, x, y); set { w = value.x; z = value.y; x = value.z; y = value.w; } }
    public uint4 wzxz => new uint4(w, z, x, z);
    public uint4 wzxw => new uint4(w, z, x, w);
    public uint4 wzyx { get => new uint4(w, z, y, x); set { w = value.x; z = value.y; y = value.z; x = value.w; } }
    public uint4 wzyy => new uint4(w, z, y, y);
    public uint4 wzyz => new uint4(w, z, y, z);
    public uint4 wzyw => new uint4(w, z, y, w);
    public uint4 wzzx => new uint4(w, z, z, x);
    public uint4 wzzy => new uint4(w, z, z, y);
    public uint4 wzzz => new uint4(w, z, z, z);
    public uint4 wzzw => new uint4(w, z, z, w);
    public uint4 wzwx => new uint4(w, z, w, x);
    public uint4 wzwy => new uint4(w, z, w, y);
    public uint4 wzwz => new uint4(w, z, w, z);
    public uint4 wzww => new uint4(w, z, w, w);
    public uint4 wwxx => new uint4(w, w, x, x);
    public uint4 wwxy => new uint4(w, w, x, y);
    public uint4 wwxz => new uint4(w, w, x, z);
    public uint4 wwxw => new uint4(w, w, x, w);
    public uint4 wwyx => new uint4(w, w, y, x);
    public uint4 wwyy => new uint4(w, w, y, y);
    public uint4 wwyz => new uint4(w, w, y, z);
    public uint4 wwyw => new uint4(w, w, y, w);
    public uint4 wwzx => new uint4(w, w, z, x);
    public uint4 wwzy => new uint4(w, w, z, y);
    public uint4 wwzz => new uint4(w, w, z, z);
    public uint4 wwzw => new uint4(w, w, z, w);
    public uint4 wwwx => new uint4(w, w, w, x);
    public uint4 wwwy => new uint4(w, w, w, y);
    public uint4 wwwz => new uint4(w, w, w, z);
    public uint4 wwww => new uint4(w, w, w, w);
    public uint r { get => x; set => x = value; }
    public uint g { get => y; set => y = value; }
    public uint b { get => z; set => z = value; }
    public uint a { get => w; set => w = value; }
    public uint2 rr => new uint2(x, x);
    public uint2 rg { get => new uint2(x, y); set { x = value.x; y = value.y; } }
    public uint2 rb { get => new uint2(x, z); set { x = value.x; z = value.y; } }
    public uint2 ra { get => new uint2(x, w); set { x = value.x; w = value.y; } }
    public uint2 gr { get => new uint2(y, x); set { y = value.x; x = value.y; } }
    public uint2 gg => new uint2(y, y);
    public uint2 gb { get => new uint2(y, z); set { y = value.x; z = value.y; } }
    public uint2 ga { get => new uint2(y, w); set { y = value.x; w = value.y; } }
    public uint2 br { get => new uint2(z, x); set { z = value.x; x = value.y; } }
    public uint2 bg { get => new uint2(z, y); set { z = value.x; y = value.y; } }
    public uint2 bb => new uint2(z, z);
    public uint2 ba { get => new uint2(z, w); set { z = value.x; w = value.y; } }
    public uint2 ar { get => new uint2(w, x); set { w = value.x; x = value.y; } }
    public uint2 ag { get => new uint2(w, y); set { w = value.x; y = value.y; } }
    public uint2 ab { get => new uint2(w, z); set { w = value.x; z = value.y; } }
    public uint2 aa => new uint2(w, w);
    public uint3 rrr => new uint3(x, x, x);
    public uint3 rrg => new uint3(x, x, y);
    public uint3 rrb => new uint3(x, x, z);
    public uint3 rra => new uint3(x, x, w);
    public uint3 rgr => new uint3(x, y, x);
    public uint3 rgg => new uint3(x, y, y);
    public uint3 rgb { get => new uint3(x, y, z); set { x = value.x; y = value.y; z = value.z; } }
    public uint3 rga { get => new uint3(x, y, w); set { x = value.x; y = value.y; w = value.z; } }
    public uint3 rbr => new uint3(x, z, x);
    public uint3 rbg { get => new uint3(x, z, y); set { x = value.x; z = value.y; y = value.z; } }
    public uint3 rbb => new uint3(x, z, z);
    public uint3 rba { get => new uint3(x, z, w); set { x = value.x; z = value.y; w = value.z; } }
    public uint3 rar => new uint3(x, w, x);
    public uint3 rag { get => new uint3(x, w, y); set { x = value.x; w = value.y; y = value.z; } }
    public uint3 rab { get => new uint3(x, w, z); set { x = value.x; w = value.y; z = value.z; } }
    public uint3 raa => new uint3(x, w, w);
    public uint3 grr => new uint3(y, x, x);
    public uint3 grg => new uint3(y, x, y);
    public uint3 grb { get => new uint3(y, x, z); set { y = value.x; x = value.y; z = value.z; } }
    public uint3 gra { get => new uint3(y, x, w); set { y = value.x; x = value.y; w = value.z; } }
    public uint3 ggr => new uint3(y, y, x);
    public uint3 ggg => new uint3(y, y, y);
    public uint3 ggb => new uint3(y, y, z);
    public uint3 gga => new uint3(y, y, w);
    public uint3 gbr { get => new uint3(y, z, x); set { y = value.x; z = value.y; x = value.z; } }
    public uint3 gbg => new uint3(y, z, y);
    public uint3 gbb => new uint3(y, z, z);
    public uint3 gba { get => new uint3(y, z, w); set { y = value.x; z = value.y; w = value.z; } }
    public uint3 gar { get => new uint3(y, w, x); set { y = value.x; w = value.y; x = value.z; } }
    public uint3 gag => new uint3(y, w, y);
    public uint3 gab { get => new uint3(y, w, z); set { y = value.x; w = value.y; z = value.z; } }
    public uint3 gaa => new uint3(y, w, w);
    public uint3 brr => new uint3(z, x, x);
    public uint3 brg { get => new uint3(z, x, y); set { z = value.x; x = value.y; y = value.z; } }
    public uint3 brb => new uint3(z, x, z);
    public uint3 bra { get => new uint3(z, x, w); set { z = value.x; x = value.y; w = value.z; } }
    public uint3 bgr { get => new uint3(z, y, x); set { z = value.x; y = value.y; x = value.z; } }
    public uint3 bgg => new uint3(z, y, y);
    public uint3 bgb => new uint3(z, y, z);
    public uint3 bga { get => new uint3(z, y, w); set { z = value.x; y = value.y; w = value.z; } }
    public uint3 bbr => new uint3(z, z, x);
    public uint3 bbg => new uint3(z, z, y);
    public uint3 bbb => new uint3(z, z, z);
    public uint3 bba => new uint3(z, z, w);
    public uint3 bar { get => new uint3(z, w, x); set { z = value.x; w = value.y; x = value.z; } }
    public uint3 bag { get => new uint3(z, w, y); set { z = value.x; w = value.y; y = value.z; } }
    public uint3 bab => new uint3(z, w, z);
    public uint3 baa => new uint3(z, w, w);
    public uint3 arr => new uint3(w, x, x);
    public uint3 arg { get => new uint3(w, x, y); set { w = value.x; x = value.y; y = value.z; } }
    public uint3 arb { get => new uint3(w, x, z); set { w = value.x; x = value.y; z = value.z; } }
    public uint3 ara => new uint3(w, x, w);
    public uint3 agr { get => new uint3(w, y, x); set { w = value.x; y = value.y; x = value.z; } }
    public uint3 agg => new uint3(w, y, y);
    public uint3 agb { get => new uint3(w, y, z); set { w = value.x; y = value.y; z = value.z; } }
    public uint3 aga => new uint3(w, y, w);
    public uint3 abr { get => new uint3(w, z, x); set { w = value.x; z = value.y; x = value.z; } }
    public uint3 abg { get => new uint3(w, z, y); set { w = value.x; z = value.y; y = value.z; } }
    public uint3 abb => new uint3(w, z, z);
    public uint3 aba => new uint3(w, z, w);
    public uint3 aar => new uint3(w, w, x);
    public uint3 aag => new uint3(w, w, y);
    public uint3 aab => new uint3(w, w, z);
    public uint3 aaa => new uint3(w, w, w);
    public uint4 rrrr => new uint4(x, x, x, x);
    public uint4 rrrg => new uint4(x, x, x, y);
    public uint4 rrrb => new uint4(x, x, x, z);
    public uint4 rrra => new uint4(x, x, x, w);
    public uint4 rrgr => new uint4(x, x, y, x);
    public uint4 rrgg => new uint4(x, x, y, y);
    public uint4 rrgb => new uint4(x, x, y, z);
    public uint4 rrga => new uint4(x, x, y, w);
    public uint4 rrbr => new uint4(x, x, z, x);
    public uint4 rrbg => new uint4(x, x, z, y);
    public uint4 rrbb => new uint4(x, x, z, z);
    public uint4 rrba => new uint4(x, x, z, w);
    public uint4 rrar => new uint4(x, x, w, x);
    public uint4 rrag => new uint4(x, x, w, y);
    public uint4 rrab => new uint4(x, x, w, z);
    public uint4 rraa => new uint4(x, x, w, w);
    public uint4 rgrr => new uint4(x, y, x, x);
    public uint4 rgrg => new uint4(x, y, x, y);
    public uint4 rgrb => new uint4(x, y, x, z);
    public uint4 rgra => new uint4(x, y, x, w);
    public uint4 rggr => new uint4(x, y, y, x);
    public uint4 rggg => new uint4(x, y, y, y);
    public uint4 rggb => new uint4(x, y, y, z);
    public uint4 rgga => new uint4(x, y, y, w);
    public uint4 rgbr => new uint4(x, y, z, x);
    public uint4 rgbg => new uint4(x, y, z, y);
    public uint4 rgbb => new uint4(x, y, z, z);
    public uint4 rgba { get => new uint4(x, y, z, w); set { x = value.x; y = value.y; z = value.z; w = value.w; } }
    public uint4 rgar => new uint4(x, y, w, x);
    public uint4 rgag => new uint4(x, y, w, y);
    public uint4 rgab { get => new uint4(x, y, w, z); set { x = value.x; y = value.y; w = value.z; z = value.w; } }
    public uint4 rgaa => new uint4(x, y, w, w);
    public uint4 rbrr => new uint4(x, z, x, x);
    public uint4 rbrg => new uint4(x, z, x, y);
    public uint4 rbrb => new uint4(x, z, x, z);
    public uint4 rbra => new uint4(x, z, x, w);
    public uint4 rbgr => new uint4(x, z, y, x);
    public uint4 rbgg => new uint4(x, z, y, y);
    public uint4 rbgb => new uint4(x, z, y, z);
    public uint4 rbga { get => new uint4(x, z, y, w); set { x = value.x; z = value.y; y = value.z; w = value.w; } }
    public uint4 rbbr => new uint4(x, z, z, x);
    public uint4 rbbg => new uint4(x, z, z, y);
    public uint4 rbbb => new uint4(x, z, z, z);
    public uint4 rbba => new uint4(x, z, z, w);
    public uint4 rbar => new uint4(x, z, w, x);
    public uint4 rbag { get => new uint4(x, z, w, y); set { x = value.x; z = value.y; w = value.z; y = value.w; } }
    public uint4 rbab => new uint4(x, z, w, z);
    public uint4 rbaa => new uint4(x, z, w, w);
    public uint4 rarr => new uint4(x, w, x, x);
    public uint4 rarg => new uint4(x, w, x, y);
    public uint4 rarb => new uint4(x, w, x, z);
    public uint4 rara => new uint4(x, w, x, w);
    public uint4 ragr => new uint4(x, w, y, x);
    public uint4 ragg => new uint4(x, w, y, y);
    public uint4 ragb { get => new uint4(x, w, y, z); set { x = value.x; w = value.y; y = value.z; z = value.w; } }
    public uint4 raga => new uint4(x, w, y, w);
    public uint4 rabr => new uint4(x, w, z, x);
    public uint4 rabg { get => new uint4(x, w, z, y); set { x = value.x; w = value.y; z = value.z; y = value.w; } }
    public uint4 rabb => new uint4(x, w, z, z);
    public uint4 raba => new uint4(x, w, z, w);
    public uint4 raar => new uint4(x, w, w, x);
    public uint4 raag => new uint4(x, w, w, y);
    public uint4 raab => new uint4(x, w, w, z);
    public uint4 raaa => new uint4(x, w, w, w);
    public uint4 grrr => new uint4(y, x, x, x);
    public uint4 grrg => new uint4(y, x, x, y);
    public uint4 grrb => new uint4(y, x, x, z);
    public uint4 grra => new uint4(y, x, x, w);
    public uint4 grgr => new uint4(y, x, y, x);
    public uint4 grgg => new uint4(y, x, y, y);
    public uint4 grgb => new uint4(y, x, y, z);
    public uint4 grga => new uint4(y, x, y, w);
    public uint4 grbr => new uint4(y, x, z, x);
    public uint4 grbg => new uint4(y, x, z, y);
    public uint4 grbb => new uint4(y, x, z, z);
    public uint4 grba { get => new uint4(y, x, z, w); set { y = value.x; x = value.y; z = value.z; w = value.w; } }
    public uint4 grar => new uint4(y, x, w, x);
    public uint4 grag => new uint4(y, x, w, y);
    public uint4 grab { get => new uint4(y, x, w, z); set { y = value.x; x = value.y; w = value.z; z = value.w; } }
    public uint4 graa => new uint4(y, x, w, w);
    public uint4 ggrr => new uint4(y, y, x, x);
    public uint4 ggrg => new uint4(y, y, x, y);
    public uint4 ggrb => new uint4(y, y, x, z);
    public uint4 ggra => new uint4(y, y, x, w);
    public uint4 gggr => new uint4(y, y, y, x);
    public uint4 gggg => new uint4(y, y, y, y);
    public uint4 gggb => new uint4(y, y, y, z);
    public uint4 ggga => new uint4(y, y, y, w);
    public uint4 ggbr => new uint4(y, y, z, x);
    public uint4 ggbg => new uint4(y, y, z, y);
    public uint4 ggbb => new uint4(y, y, z, z);
    public uint4 ggba => new uint4(y, y, z, w);
    public uint4 ggar => new uint4(y, y, w, x);
    public uint4 ggag => new uint4(y, y, w, y);
    public uint4 ggab => new uint4(y, y, w, z);
    public uint4 ggaa => new uint4(y, y, w, w);
    public uint4 gbrr => new uint4(y, z, x, x);
    public uint4 gbrg => new uint4(y, z, x, y);
    public uint4 gbrb => new uint4(y, z, x, z);
    public uint4 gbra { get => new uint4(y, z, x, w); set { y = value.x; z = value.y; x = value.z; w = value.w; } }
    public uint4 gbgr => new uint4(y, z, y, x);
    public uint4 gbgg => new uint4(y, z, y, y);
    public uint4 gbgb => new uint4(y, z, y, z);
    public uint4 gbga => new uint4(y, z, y, w);
    public uint4 gbbr => new uint4(y, z, z, x);
    public uint4 gbbg => new uint4(y, z, z, y);
    public uint4 gbbb => new uint4(y, z, z, z);
    public uint4 gbba => new uint4(y, z, z, w);
    public uint4 gbar { get => new uint4(y, z, w, x); set { y = value.x; z = value.y; w = value.z; x = value.w; } }
    public uint4 gbag => new uint4(y, z, w, y);
    public uint4 gbab => new uint4(y, z, w, z);
    public uint4 gbaa => new uint4(y, z, w, w);
    public uint4 garr => new uint4(y, w, x, x);
    public uint4 garg => new uint4(y, w, x, y);
    public uint4 garb { get => new uint4(y, w, x, z); set { y = value.x; w = value.y; x = value.z; z = value.w; } }
    public uint4 gara => new uint4(y, w, x, w);
    public uint4 gagr => new uint4(y, w, y, x);
    public uint4 gagg => new uint4(y, w, y, y);
    public uint4 gagb => new uint4(y, w, y, z);
    public uint4 gaga => new uint4(y, w, y, w);
    public uint4 gabr { get => new uint4(y, w, z, x); set { y = value.x; w = value.y; z = value.z; x = value.w; } }
    public uint4 gabg => new uint4(y, w, z, y);
    public uint4 gabb => new uint4(y, w, z, z);
    public uint4 gaba => new uint4(y, w, z, w);
    public uint4 gaar => new uint4(y, w, w, x);
    public uint4 gaag => new uint4(y, w, w, y);
    public uint4 gaab => new uint4(y, w, w, z);
    public uint4 gaaa => new uint4(y, w, w, w);
    public uint4 brrr => new uint4(z, x, x, x);
    public uint4 brrg => new uint4(z, x, x, y);
    public uint4 brrb => new uint4(z, x, x, z);
    public uint4 brra => new uint4(z, x, x, w);
    public uint4 brgr => new uint4(z, x, y, x);
    public uint4 brgg => new uint4(z, x, y, y);
    public uint4 brgb => new uint4(z, x, y, z);
    public uint4 brga { get => new uint4(z, x, y, w); set { z = value.x; x = value.y; y = value.z; w = value.w; } }
    public uint4 brbr => new uint4(z, x, z, x);
    public uint4 brbg => new uint4(z, x, z, y);
    public uint4 brbb => new uint4(z, x, z, z);
    public uint4 brba => new uint4(z, x, z, w);
    public uint4 brar => new uint4(z, x, w, x);
    public uint4 brag { get => new uint4(z, x, w, y); set { z = value.x; x = value.y; w = value.z; y = value.w; } }
    public uint4 brab => new uint4(z, x, w, z);
    public uint4 braa => new uint4(z, x, w, w);
    public uint4 bgrr => new uint4(z, y, x, x);
    public uint4 bgrg => new uint4(z, y, x, y);
    public uint4 bgrb => new uint4(z, y, x, z);
    public uint4 bgra { get => new uint4(z, y, x, w); set { z = value.x; y = value.y; x = value.z; w = value.w; } }
    public uint4 bggr => new uint4(z, y, y, x);
    public uint4 bggg => new uint4(z, y, y, y);
    public uint4 bggb => new uint4(z, y, y, z);
    public uint4 bgga => new uint4(z, y, y, w);
    public uint4 bgbr => new uint4(z, y, z, x);
    public uint4 bgbg => new uint4(z, y, z, y);
    public uint4 bgbb => new uint4(z, y, z, z);
    public uint4 bgba => new uint4(z, y, z, w);
    public uint4 bgar { get => new uint4(z, y, w, x); set { z = value.x; y = value.y; w = value.z; x = value.w; } }
    public uint4 bgag => new uint4(z, y, w, y);
    public uint4 bgab => new uint4(z, y, w, z);
    public uint4 bgaa => new uint4(z, y, w, w);
    public uint4 bbrr => new uint4(z, z, x, x);
    public uint4 bbrg => new uint4(z, z, x, y);
    public uint4 bbrb => new uint4(z, z, x, z);
    public uint4 bbra => new uint4(z, z, x, w);
    public uint4 bbgr => new uint4(z, z, y, x);
    public uint4 bbgg => new uint4(z, z, y, y);
    public uint4 bbgb => new uint4(z, z, y, z);
    public uint4 bbga => new uint4(z, z, y, w);
    public uint4 bbbr => new uint4(z, z, z, x);
    public uint4 bbbg => new uint4(z, z, z, y);
    public uint4 bbbb => new uint4(z, z, z, z);
    public uint4 bbba => new uint4(z, z, z, w);
    public uint4 bbar => new uint4(z, z, w, x);
    public uint4 bbag => new uint4(z, z, w, y);
    public uint4 bbab => new uint4(z, z, w, z);
    public uint4 bbaa => new uint4(z, z, w, w);
    public uint4 barr => new uint4(z, w, x, x);
    public uint4 barg { get => new uint4(z, w, x, y); set { z = value.x; w = value.y; x = value.z; y = value.w; } }
    public uint4 barb => new uint4(z, w, x, z);
    public uint4 bara => new uint4(z, w, x, w);
    public uint4 bagr { get => new uint4(z, w, y, x); set { z = value.x; w = value.y; y = value.z; x = value.w; } }
    public uint4 bagg => new uint4(z, w, y, y);
    public uint4 bagb => new uint4(z, w, y, z);
    public uint4 baga => new uint4(z, w, y, w);
    public uint4 babr => new uint4(z, w, z, x);
    public uint4 babg => new uint4(z, w, z, y);
    public uint4 babb => new uint4(z, w, z, z);
    public uint4 baba => new uint4(z, w, z, w);
    public uint4 baar => new uint4(z, w, w, x);
    public uint4 baag => new uint4(z, w, w, y);
    public uint4 baab => new uint4(z, w, w, z);
    public uint4 baaa => new uint4(z, w, w, w);
    public uint4 arrr => new uint4(w, x, x, x);
    public uint4 arrg => new uint4(w, x, x, y);
    public uint4 arrb => new uint4(w, x, x, z);
    public uint4 arra => new uint4(w, x, x, w);
    public uint4 argr => new uint4(w, x, y, x);
    public uint4 argg => new uint4(w, x, y, y);
    public uint4 argb { get => new uint4(w, x, y, z); set { w = value.x; x = value.y; y = value.z; z = value.w; } }
    public uint4 arga => new uint4(w, x, y, w);
    public uint4 arbr => new uint4(w, x, z, x);
    public uint4 arbg { get => new uint4(w, x, z, y); set { w = value.x; x = value.y; z = value.z; y = value.w; } }
    public uint4 arbb => new uint4(w, x, z, z);
    public uint4 arba => new uint4(w, x, z, w);
    public uint4 arar => new uint4(w, x, w, x);
    public uint4 arag => new uint4(w, x, w, y);
    public uint4 arab => new uint4(w, x, w, z);
    public uint4 araa => new uint4(w, x, w, w);
    public uint4 agrr => new uint4(w, y, x, x);
    public uint4 agrg => new uint4(w, y, x, y);
    public uint4 agrb { get => new uint4(w, y, x, z); set { w = value.x; y = value.y; x = value.z; z = value.w; } }
    public uint4 agra => new uint4(w, y, x, w);
    public uint4 aggr => new uint4(w, y, y, x);
    public uint4 aggg => new uint4(w, y, y, y);
    public uint4 aggb => new uint4(w, y, y, z);
    public uint4 agga => new uint4(w, y, y, w);
    public uint4 agbr { get => new uint4(w, y, z, x); set { w = value.x; y = value.y; z = value.z; x = value.w; } }
    public uint4 agbg => new uint4(w, y, z, y);
    public uint4 agbb => new uint4(w, y, z, z);
    public uint4 agba => new uint4(w, y, z, w);
    public uint4 agar => new uint4(w, y, w, x);
    public uint4 agag => new uint4(w, y, w, y);
    public uint4 agab => new uint4(w, y, w, z);
    public uint4 agaa => new uint4(w, y, w, w);
    public uint4 abrr => new uint4(w, z, x, x);
    public uint4 abrg { get => new uint4(w, z, x, y); set { w = value.x; z = value.y; x = value.z; y = value.w; } }
    public uint4 abrb => new uint4(w, z, x, z);
    public uint4 abra => new uint4(w, z, x, w);
    public uint4 abgr { get => new uint4(w, z, y, x); set { w = value.x; z = value.y; y = value.z; x = value.w; } }
    public uint4 abgg => new uint4(w, z, y, y);
    public uint4 abgb => new uint4(w, z, y, z);
    public uint4 abga => new uint4(w, z, y, w);
    public uint4 abbr => new uint4(w, z, z, x);
    public uint4 abbg => new uint4(w, z, z, y);
    public uint4 abbb => new uint4(w, z, z, z);
    public uint4 abba => new uint4(w, z, z, w);
    public uint4 abar => new uint4(w, z, w, x);
    public uint4 abag => new uint4(w, z, w, y);
    public uint4 abab => new uint4(w, z, w, z);
    public uint4 abaa => new uint4(w, z, w, w);
    public uint4 aarr => new uint4(w, w, x, x);
    public uint4 aarg => new uint4(w, w, x, y);
    public uint4 aarb => new uint4(w, w, x, z);
    public uint4 aara => new uint4(w, w, x, w);
    public uint4 aagr => new uint4(w, w, y, x);
    public uint4 aagg => new uint4(w, w, y, y);
    public uint4 aagb => new uint4(w, w, y, z);
    public uint4 aaga => new uint4(w, w, y, w);
    public uint4 aabr => new uint4(w, w, z, x);
    public uint4 aabg => new uint4(w, w, z, y);
    public uint4 aabb => new uint4(w, w, z, z);
    public uint4 aaba => new uint4(w, w, z, w);
    public uint4 aaar => new uint4(w, w, w, x);
    public uint4 aaag => new uint4(w, w, w, y);
    public uint4 aaab => new uint4(w, w, w, z);
    public uint4 aaaa => new uint4(w, w, w, w);
}
