// <auto-generated>
// Written by tools/gen_hlsl_types.py. Do not edit; edit the script and run it again.
// </auto-generated>
#nullable enable
#pragma warning disable IDE1006, CS1591
using System;
using System.Runtime.InteropServices;

namespace Csl.Hlsl;

/// <summary>HLSL uint3: 3 components of uint. Runs on the GPU; the C# operations exist so shader code type-checks and can be unit tested.</summary>
[StructLayout(LayoutKind.Sequential)]
public struct uint3 : IEquatable<uint3>
{
    public uint x, y, z;
    public uint3(uint x, uint y, uint z) { this.x = x; this.y = y; this.z = z; }
    public uint3(uint v) { x = v; y = v; z = v; }
    public uint3(uint2 xy, uint z) { x = xy.x; y = xy.y; this.z = z; }
    public uint3(uint x, uint2 yz) { this.x = x; y = yz.x; z = yz.y; }
    public uint3(float3 v) { x = (uint)v.x; y = (uint)v.y; z = (uint)v.z; }
    public static explicit operator uint3(float3 v) => new uint3(v);
    public uint3(int3 v) { x = (uint)v.x; y = (uint)v.y; z = (uint)v.z; }
    public static explicit operator uint3(int3 v) => new uint3(v);
    public static implicit operator uint3(uint v) => new uint3(v);
    public uint this[int i]
    {
        get => i switch { 0 => x, 1 => y, 2 => z, _ => throw new IndexOutOfRangeException() };
        set { switch (i) { case 0: x = value; break; case 1: y = value; break; case 2: z = value; break; default: throw new IndexOutOfRangeException(); } }
    }
    public static uint3 operator +(uint3 a, uint3 b) => new uint3((uint)(a.x + b.x), (uint)(a.y + b.y), (uint)(a.z + b.z));
    public static uint3 operator +(uint3 a, uint b) => new uint3((uint)(a.x + b), (uint)(a.y + b), (uint)(a.z + b));
    public static uint3 operator +(uint a, uint3 b) => new uint3((uint)(a + b.x), (uint)(a + b.y), (uint)(a + b.z));
    public static uint3 operator -(uint3 a, uint3 b) => new uint3((uint)(a.x - b.x), (uint)(a.y - b.y), (uint)(a.z - b.z));
    public static uint3 operator -(uint3 a, uint b) => new uint3((uint)(a.x - b), (uint)(a.y - b), (uint)(a.z - b));
    public static uint3 operator -(uint a, uint3 b) => new uint3((uint)(a - b.x), (uint)(a - b.y), (uint)(a - b.z));
    public static uint3 operator *(uint3 a, uint3 b) => new uint3((uint)(a.x * b.x), (uint)(a.y * b.y), (uint)(a.z * b.z));
    public static uint3 operator *(uint3 a, uint b) => new uint3((uint)(a.x * b), (uint)(a.y * b), (uint)(a.z * b));
    public static uint3 operator *(uint a, uint3 b) => new uint3((uint)(a * b.x), (uint)(a * b.y), (uint)(a * b.z));
    public static uint3 operator /(uint3 a, uint3 b) => new uint3((uint)(a.x / b.x), (uint)(a.y / b.y), (uint)(a.z / b.z));
    public static uint3 operator /(uint3 a, uint b) => new uint3((uint)(a.x / b), (uint)(a.y / b), (uint)(a.z / b));
    public static uint3 operator /(uint a, uint3 b) => new uint3((uint)(a / b.x), (uint)(a / b.y), (uint)(a / b.z));
    public static uint3 operator %(uint3 a, uint3 b) => new uint3((uint)(a.x % b.x), (uint)(a.y % b.y), (uint)(a.z % b.z));
    public static uint3 operator %(uint3 a, uint b) => new uint3((uint)(a.x % b), (uint)(a.y % b), (uint)(a.z % b));
    public static uint3 operator %(uint a, uint3 b) => new uint3((uint)(a % b.x), (uint)(a % b.y), (uint)(a % b.z));
    public static uint3 operator +(uint3 a) => a;
    public static uint3 operator ++(uint3 a) => new uint3((uint)(a.x + 1u), (uint)(a.y + 1u), (uint)(a.z + 1u));
    public static uint3 operator --(uint3 a) => new uint3((uint)(a.x - 1u), (uint)(a.y - 1u), (uint)(a.z - 1u));
    public static bool3 operator <(uint3 a, uint3 b) => new bool3(a.x < b.x, a.y < b.y, a.z < b.z);
    public static bool3 operator <(uint3 a, uint b) => new bool3(a.x < b, a.y < b, a.z < b);
    public static bool3 operator <(uint a, uint3 b) => new bool3(a < b.x, a < b.y, a < b.z);
    public static bool3 operator >(uint3 a, uint3 b) => new bool3(a.x > b.x, a.y > b.y, a.z > b.z);
    public static bool3 operator >(uint3 a, uint b) => new bool3(a.x > b, a.y > b, a.z > b);
    public static bool3 operator >(uint a, uint3 b) => new bool3(a > b.x, a > b.y, a > b.z);
    public static bool3 operator <=(uint3 a, uint3 b) => new bool3(a.x <= b.x, a.y <= b.y, a.z <= b.z);
    public static bool3 operator <=(uint3 a, uint b) => new bool3(a.x <= b, a.y <= b, a.z <= b);
    public static bool3 operator <=(uint a, uint3 b) => new bool3(a <= b.x, a <= b.y, a <= b.z);
    public static bool3 operator >=(uint3 a, uint3 b) => new bool3(a.x >= b.x, a.y >= b.y, a.z >= b.z);
    public static bool3 operator >=(uint3 a, uint b) => new bool3(a.x >= b, a.y >= b, a.z >= b);
    public static bool3 operator >=(uint a, uint3 b) => new bool3(a >= b.x, a >= b.y, a >= b.z);
    public static uint3 operator &(uint3 a, uint3 b) => new uint3((uint)(a.x & b.x), (uint)(a.y & b.y), (uint)(a.z & b.z));
    public static uint3 operator &(uint3 a, uint b) => new uint3((uint)(a.x & b), (uint)(a.y & b), (uint)(a.z & b));
    public static uint3 operator |(uint3 a, uint3 b) => new uint3((uint)(a.x | b.x), (uint)(a.y | b.y), (uint)(a.z | b.z));
    public static uint3 operator |(uint3 a, uint b) => new uint3((uint)(a.x | b), (uint)(a.y | b), (uint)(a.z | b));
    public static uint3 operator ^(uint3 a, uint3 b) => new uint3((uint)(a.x ^ b.x), (uint)(a.y ^ b.y), (uint)(a.z ^ b.z));
    public static uint3 operator ^(uint3 a, uint b) => new uint3((uint)(a.x ^ b), (uint)(a.y ^ b), (uint)(a.z ^ b));
    public static uint3 operator <<(uint3 a, int b) => new uint3((uint)(a.x << b), (uint)(a.y << b), (uint)(a.z << b));
    public static uint3 operator >>(uint3 a, int b) => new uint3((uint)(a.x >> b), (uint)(a.y >> b), (uint)(a.z >> b));
    public static uint3 operator ~(uint3 a) => new uint3((uint)(~a.x), (uint)(~a.y), (uint)(~a.z));
    public static bool3 operator ==(uint3 a, uint3 b) => new bool3(a.x == b.x, a.y == b.y, a.z == b.z);
    public static bool3 operator !=(uint3 a, uint3 b) => new bool3(a.x != b.x, a.y != b.y, a.z != b.z);
    public static bool3 operator ==(uint3 a, uint b) => new bool3(a.x == b, a.y == b, a.z == b);
    public static bool3 operator !=(uint3 a, uint b) => new bool3(a.x != b, a.y != b, a.z != b);
    public bool Equals(uint3 other) => x == other.x && y == other.y && z == other.z;
    public override bool Equals(object? obj) => obj is uint3 other && Equals(other);
    public override int GetHashCode() => HashCode.Combine(x, y, z);
    public override string ToString() => $"uint3({x}, {y}, {z})";

    // Swizzles, xyzw and rgba. Setters only where no component repeats.
    public uint2 xx => new uint2(x, x);
    public uint2 xy { get => new uint2(x, y); set { x = value.x; y = value.y; } }
    public uint2 xz { get => new uint2(x, z); set { x = value.x; z = value.y; } }
    public uint2 yx { get => new uint2(y, x); set { y = value.x; x = value.y; } }
    public uint2 yy => new uint2(y, y);
    public uint2 yz { get => new uint2(y, z); set { y = value.x; z = value.y; } }
    public uint2 zx { get => new uint2(z, x); set { z = value.x; x = value.y; } }
    public uint2 zy { get => new uint2(z, y); set { z = value.x; y = value.y; } }
    public uint2 zz => new uint2(z, z);
    public uint3 xxx => new uint3(x, x, x);
    public uint3 xxy => new uint3(x, x, y);
    public uint3 xxz => new uint3(x, x, z);
    public uint3 xyx => new uint3(x, y, x);
    public uint3 xyy => new uint3(x, y, y);
    public uint3 xyz { get => new uint3(x, y, z); set { x = value.x; y = value.y; z = value.z; } }
    public uint3 xzx => new uint3(x, z, x);
    public uint3 xzy { get => new uint3(x, z, y); set { x = value.x; z = value.y; y = value.z; } }
    public uint3 xzz => new uint3(x, z, z);
    public uint3 yxx => new uint3(y, x, x);
    public uint3 yxy => new uint3(y, x, y);
    public uint3 yxz { get => new uint3(y, x, z); set { y = value.x; x = value.y; z = value.z; } }
    public uint3 yyx => new uint3(y, y, x);
    public uint3 yyy => new uint3(y, y, y);
    public uint3 yyz => new uint3(y, y, z);
    public uint3 yzx { get => new uint3(y, z, x); set { y = value.x; z = value.y; x = value.z; } }
    public uint3 yzy => new uint3(y, z, y);
    public uint3 yzz => new uint3(y, z, z);
    public uint3 zxx => new uint3(z, x, x);
    public uint3 zxy { get => new uint3(z, x, y); set { z = value.x; x = value.y; y = value.z; } }
    public uint3 zxz => new uint3(z, x, z);
    public uint3 zyx { get => new uint3(z, y, x); set { z = value.x; y = value.y; x = value.z; } }
    public uint3 zyy => new uint3(z, y, y);
    public uint3 zyz => new uint3(z, y, z);
    public uint3 zzx => new uint3(z, z, x);
    public uint3 zzy => new uint3(z, z, y);
    public uint3 zzz => new uint3(z, z, z);
    public uint4 xxxx => new uint4(x, x, x, x);
    public uint4 xxxy => new uint4(x, x, x, y);
    public uint4 xxxz => new uint4(x, x, x, z);
    public uint4 xxyx => new uint4(x, x, y, x);
    public uint4 xxyy => new uint4(x, x, y, y);
    public uint4 xxyz => new uint4(x, x, y, z);
    public uint4 xxzx => new uint4(x, x, z, x);
    public uint4 xxzy => new uint4(x, x, z, y);
    public uint4 xxzz => new uint4(x, x, z, z);
    public uint4 xyxx => new uint4(x, y, x, x);
    public uint4 xyxy => new uint4(x, y, x, y);
    public uint4 xyxz => new uint4(x, y, x, z);
    public uint4 xyyx => new uint4(x, y, y, x);
    public uint4 xyyy => new uint4(x, y, y, y);
    public uint4 xyyz => new uint4(x, y, y, z);
    public uint4 xyzx => new uint4(x, y, z, x);
    public uint4 xyzy => new uint4(x, y, z, y);
    public uint4 xyzz => new uint4(x, y, z, z);
    public uint4 xzxx => new uint4(x, z, x, x);
    public uint4 xzxy => new uint4(x, z, x, y);
    public uint4 xzxz => new uint4(x, z, x, z);
    public uint4 xzyx => new uint4(x, z, y, x);
    public uint4 xzyy => new uint4(x, z, y, y);
    public uint4 xzyz => new uint4(x, z, y, z);
    public uint4 xzzx => new uint4(x, z, z, x);
    public uint4 xzzy => new uint4(x, z, z, y);
    public uint4 xzzz => new uint4(x, z, z, z);
    public uint4 yxxx => new uint4(y, x, x, x);
    public uint4 yxxy => new uint4(y, x, x, y);
    public uint4 yxxz => new uint4(y, x, x, z);
    public uint4 yxyx => new uint4(y, x, y, x);
    public uint4 yxyy => new uint4(y, x, y, y);
    public uint4 yxyz => new uint4(y, x, y, z);
    public uint4 yxzx => new uint4(y, x, z, x);
    public uint4 yxzy => new uint4(y, x, z, y);
    public uint4 yxzz => new uint4(y, x, z, z);
    public uint4 yyxx => new uint4(y, y, x, x);
    public uint4 yyxy => new uint4(y, y, x, y);
    public uint4 yyxz => new uint4(y, y, x, z);
    public uint4 yyyx => new uint4(y, y, y, x);
    public uint4 yyyy => new uint4(y, y, y, y);
    public uint4 yyyz => new uint4(y, y, y, z);
    public uint4 yyzx => new uint4(y, y, z, x);
    public uint4 yyzy => new uint4(y, y, z, y);
    public uint4 yyzz => new uint4(y, y, z, z);
    public uint4 yzxx => new uint4(y, z, x, x);
    public uint4 yzxy => new uint4(y, z, x, y);
    public uint4 yzxz => new uint4(y, z, x, z);
    public uint4 yzyx => new uint4(y, z, y, x);
    public uint4 yzyy => new uint4(y, z, y, y);
    public uint4 yzyz => new uint4(y, z, y, z);
    public uint4 yzzx => new uint4(y, z, z, x);
    public uint4 yzzy => new uint4(y, z, z, y);
    public uint4 yzzz => new uint4(y, z, z, z);
    public uint4 zxxx => new uint4(z, x, x, x);
    public uint4 zxxy => new uint4(z, x, x, y);
    public uint4 zxxz => new uint4(z, x, x, z);
    public uint4 zxyx => new uint4(z, x, y, x);
    public uint4 zxyy => new uint4(z, x, y, y);
    public uint4 zxyz => new uint4(z, x, y, z);
    public uint4 zxzx => new uint4(z, x, z, x);
    public uint4 zxzy => new uint4(z, x, z, y);
    public uint4 zxzz => new uint4(z, x, z, z);
    public uint4 zyxx => new uint4(z, y, x, x);
    public uint4 zyxy => new uint4(z, y, x, y);
    public uint4 zyxz => new uint4(z, y, x, z);
    public uint4 zyyx => new uint4(z, y, y, x);
    public uint4 zyyy => new uint4(z, y, y, y);
    public uint4 zyyz => new uint4(z, y, y, z);
    public uint4 zyzx => new uint4(z, y, z, x);
    public uint4 zyzy => new uint4(z, y, z, y);
    public uint4 zyzz => new uint4(z, y, z, z);
    public uint4 zzxx => new uint4(z, z, x, x);
    public uint4 zzxy => new uint4(z, z, x, y);
    public uint4 zzxz => new uint4(z, z, x, z);
    public uint4 zzyx => new uint4(z, z, y, x);
    public uint4 zzyy => new uint4(z, z, y, y);
    public uint4 zzyz => new uint4(z, z, y, z);
    public uint4 zzzx => new uint4(z, z, z, x);
    public uint4 zzzy => new uint4(z, z, z, y);
    public uint4 zzzz => new uint4(z, z, z, z);
    public uint r { get => x; set => x = value; }
    public uint g { get => y; set => y = value; }
    public uint b { get => z; set => z = value; }
    public uint2 rr => new uint2(x, x);
    public uint2 rg { get => new uint2(x, y); set { x = value.x; y = value.y; } }
    public uint2 rb { get => new uint2(x, z); set { x = value.x; z = value.y; } }
    public uint2 gr { get => new uint2(y, x); set { y = value.x; x = value.y; } }
    public uint2 gg => new uint2(y, y);
    public uint2 gb { get => new uint2(y, z); set { y = value.x; z = value.y; } }
    public uint2 br { get => new uint2(z, x); set { z = value.x; x = value.y; } }
    public uint2 bg { get => new uint2(z, y); set { z = value.x; y = value.y; } }
    public uint2 bb => new uint2(z, z);
    public uint3 rrr => new uint3(x, x, x);
    public uint3 rrg => new uint3(x, x, y);
    public uint3 rrb => new uint3(x, x, z);
    public uint3 rgr => new uint3(x, y, x);
    public uint3 rgg => new uint3(x, y, y);
    public uint3 rgb { get => new uint3(x, y, z); set { x = value.x; y = value.y; z = value.z; } }
    public uint3 rbr => new uint3(x, z, x);
    public uint3 rbg { get => new uint3(x, z, y); set { x = value.x; z = value.y; y = value.z; } }
    public uint3 rbb => new uint3(x, z, z);
    public uint3 grr => new uint3(y, x, x);
    public uint3 grg => new uint3(y, x, y);
    public uint3 grb { get => new uint3(y, x, z); set { y = value.x; x = value.y; z = value.z; } }
    public uint3 ggr => new uint3(y, y, x);
    public uint3 ggg => new uint3(y, y, y);
    public uint3 ggb => new uint3(y, y, z);
    public uint3 gbr { get => new uint3(y, z, x); set { y = value.x; z = value.y; x = value.z; } }
    public uint3 gbg => new uint3(y, z, y);
    public uint3 gbb => new uint3(y, z, z);
    public uint3 brr => new uint3(z, x, x);
    public uint3 brg { get => new uint3(z, x, y); set { z = value.x; x = value.y; y = value.z; } }
    public uint3 brb => new uint3(z, x, z);
    public uint3 bgr { get => new uint3(z, y, x); set { z = value.x; y = value.y; x = value.z; } }
    public uint3 bgg => new uint3(z, y, y);
    public uint3 bgb => new uint3(z, y, z);
    public uint3 bbr => new uint3(z, z, x);
    public uint3 bbg => new uint3(z, z, y);
    public uint3 bbb => new uint3(z, z, z);
    public uint4 rrrr => new uint4(x, x, x, x);
    public uint4 rrrg => new uint4(x, x, x, y);
    public uint4 rrrb => new uint4(x, x, x, z);
    public uint4 rrgr => new uint4(x, x, y, x);
    public uint4 rrgg => new uint4(x, x, y, y);
    public uint4 rrgb => new uint4(x, x, y, z);
    public uint4 rrbr => new uint4(x, x, z, x);
    public uint4 rrbg => new uint4(x, x, z, y);
    public uint4 rrbb => new uint4(x, x, z, z);
    public uint4 rgrr => new uint4(x, y, x, x);
    public uint4 rgrg => new uint4(x, y, x, y);
    public uint4 rgrb => new uint4(x, y, x, z);
    public uint4 rggr => new uint4(x, y, y, x);
    public uint4 rggg => new uint4(x, y, y, y);
    public uint4 rggb => new uint4(x, y, y, z);
    public uint4 rgbr => new uint4(x, y, z, x);
    public uint4 rgbg => new uint4(x, y, z, y);
    public uint4 rgbb => new uint4(x, y, z, z);
    public uint4 rbrr => new uint4(x, z, x, x);
    public uint4 rbrg => new uint4(x, z, x, y);
    public uint4 rbrb => new uint4(x, z, x, z);
    public uint4 rbgr => new uint4(x, z, y, x);
    public uint4 rbgg => new uint4(x, z, y, y);
    public uint4 rbgb => new uint4(x, z, y, z);
    public uint4 rbbr => new uint4(x, z, z, x);
    public uint4 rbbg => new uint4(x, z, z, y);
    public uint4 rbbb => new uint4(x, z, z, z);
    public uint4 grrr => new uint4(y, x, x, x);
    public uint4 grrg => new uint4(y, x, x, y);
    public uint4 grrb => new uint4(y, x, x, z);
    public uint4 grgr => new uint4(y, x, y, x);
    public uint4 grgg => new uint4(y, x, y, y);
    public uint4 grgb => new uint4(y, x, y, z);
    public uint4 grbr => new uint4(y, x, z, x);
    public uint4 grbg => new uint4(y, x, z, y);
    public uint4 grbb => new uint4(y, x, z, z);
    public uint4 ggrr => new uint4(y, y, x, x);
    public uint4 ggrg => new uint4(y, y, x, y);
    public uint4 ggrb => new uint4(y, y, x, z);
    public uint4 gggr => new uint4(y, y, y, x);
    public uint4 gggg => new uint4(y, y, y, y);
    public uint4 gggb => new uint4(y, y, y, z);
    public uint4 ggbr => new uint4(y, y, z, x);
    public uint4 ggbg => new uint4(y, y, z, y);
    public uint4 ggbb => new uint4(y, y, z, z);
    public uint4 gbrr => new uint4(y, z, x, x);
    public uint4 gbrg => new uint4(y, z, x, y);
    public uint4 gbrb => new uint4(y, z, x, z);
    public uint4 gbgr => new uint4(y, z, y, x);
    public uint4 gbgg => new uint4(y, z, y, y);
    public uint4 gbgb => new uint4(y, z, y, z);
    public uint4 gbbr => new uint4(y, z, z, x);
    public uint4 gbbg => new uint4(y, z, z, y);
    public uint4 gbbb => new uint4(y, z, z, z);
    public uint4 brrr => new uint4(z, x, x, x);
    public uint4 brrg => new uint4(z, x, x, y);
    public uint4 brrb => new uint4(z, x, x, z);
    public uint4 brgr => new uint4(z, x, y, x);
    public uint4 brgg => new uint4(z, x, y, y);
    public uint4 brgb => new uint4(z, x, y, z);
    public uint4 brbr => new uint4(z, x, z, x);
    public uint4 brbg => new uint4(z, x, z, y);
    public uint4 brbb => new uint4(z, x, z, z);
    public uint4 bgrr => new uint4(z, y, x, x);
    public uint4 bgrg => new uint4(z, y, x, y);
    public uint4 bgrb => new uint4(z, y, x, z);
    public uint4 bggr => new uint4(z, y, y, x);
    public uint4 bggg => new uint4(z, y, y, y);
    public uint4 bggb => new uint4(z, y, y, z);
    public uint4 bgbr => new uint4(z, y, z, x);
    public uint4 bgbg => new uint4(z, y, z, y);
    public uint4 bgbb => new uint4(z, y, z, z);
    public uint4 bbrr => new uint4(z, z, x, x);
    public uint4 bbrg => new uint4(z, z, x, y);
    public uint4 bbrb => new uint4(z, z, x, z);
    public uint4 bbgr => new uint4(z, z, y, x);
    public uint4 bbgg => new uint4(z, z, y, y);
    public uint4 bbgb => new uint4(z, z, y, z);
    public uint4 bbbr => new uint4(z, z, z, x);
    public uint4 bbbg => new uint4(z, z, z, y);
    public uint4 bbbb => new uint4(z, z, z, z);
}
