using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using Csl.Generators.Sdsl;

namespace Csl.Generators;

/// <summary>
/// The *Keys class of a shader written in C#, in the shape the engine's own generator gives a .sdsl
/// file: one ParameterKey per parameter, named after the field. The engine's assembly processor
/// then names each key "Shader.Member" from the class name, exactly as for a .sdsl shader.
/// </summary>
public static class KeysEmitter
{
    private static readonly Regex VectorLiteral = new Regex(@"^(float|int|uint)([2-4])\((.*)\)$", RegexOptions.Compiled);

    public static string Emit(SdslShader shader, string keysNamespace)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Generated by Csl.Generators from the C# shader " + shader.Name + ". Do not edit.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable disable");
        sb.AppendLine("using System;");
        sb.AppendLine("using Stride.Core;");
        sb.AppendLine("using Stride.Rendering;");
        sb.AppendLine("using Stride.Graphics;");
        sb.AppendLine("using Stride.Shaders;");
        sb.AppendLine("using Stride.Core.Mathematics;");
        sb.AppendLine("using Buffer = Stride.Graphics.Buffer;");
        sb.AppendLine();
        sb.Append("namespace ").AppendLine(keysNamespace);
        sb.AppendLine("{");
        sb.Append("    public static partial class ").Append(shader.Name).AppendLine("Keys");
        sb.AppendLine("    {");
        foreach (var member in shader.Members)
        {
            if (member.IsStream || member.IsCompose || member.IsConst || member.IsStatic || member.IsGroupShared)
                continue;
            var type = SdslTypes.ToCSharp(member);
            if (type == null)
                continue;
            var kind = SdslTypes.IsObjectKey(member) ? "Object" : "Value";
            sb.Append("        public static readonly ").Append(kind).Append("ParameterKey<").Append(type).Append("> ").Append(member.Name)
              .Append(" = ParameterKeys.New").Append(kind).Append('<').Append(type).Append(">(");
            if (kind == "Value" && !member.IsArray && member.Initializer != null)
                sb.Append(InitialValue(member.Initializer, member.Type, type));
            sb.AppendLine(");");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>The C# for an SDSL initializer, or nothing when it is more than a literal.</summary>
    private static string InitialValue(string initializer, string sdslType, string csharpType)
    {
        var text = initializer.Trim();
        if (text == "true" || text == "false")
            return csharpType == "bool" ? text : string.Empty;
        var vector = VectorLiteral.Match(text);
        if (vector.Success && !csharpType.EndsWith("[]"))
        {
            var parts = vector.Groups[3].Value.Split(',');
            var converted = new string[parts.Length];
            for (int i = 0; i < parts.Length; i++)
            {
                converted[i] = Scalar(parts[i].Trim(), vector.Groups[1].Value);
                if (converted[i].Length == 0)
                    return string.Empty;
            }
            return "new " + csharpType + "(" + string.Join(", ", converted) + ")";
        }
        return Scalar(text, sdslType);
    }

    private static string Scalar(string text, string sdslType)
    {
        switch (sdslType)
        {
            case "float":
            case "half":
                return double.TryParse(text.TrimEnd('f', 'F'), NumberStyles.Float, CultureInfo.InvariantCulture, out var f)
                    ? ((float)f).ToString("R", CultureInfo.InvariantCulture) + "f" : string.Empty;
            case "double":
                return double.TryParse(text, NumberStyles.Float, CultureInfo.InvariantCulture, out var d) ? d.ToString("R", CultureInfo.InvariantCulture) + "d" : string.Empty;
            case "int":
                return int.TryParse(text, NumberStyles.Integer, CultureInfo.InvariantCulture, out var i) ? i.ToString(CultureInfo.InvariantCulture) : string.Empty;
            case "uint":
                return uint.TryParse(text.TrimEnd('u', 'U'), NumberStyles.Integer, CultureInfo.InvariantCulture, out var u) ? u.ToString(CultureInfo.InvariantCulture) + "u" : string.Empty;
            case "bool":
                return text == "true" || text == "false" ? text : string.Empty;
            default:
                return string.Empty;
        }
    }
}
