using System.Collections.Generic;
using System.Text;
using Csl.Generators.CSharp;

namespace Csl.Generators;

/// <summary>The SDSL of a C# shader as C#: a constant on the class, and the start-up registration.</summary>
public static class SdslSourceEmitter
{
    public static string EmitPartial(TranslatedShader shader)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Generated by Csl.Generators: the SDSL translated from this class.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        if (shader.Namespace != null)
        {
            sb.Append("namespace ").AppendLine(shader.Namespace);
            sb.AppendLine("{");
        }
        var indent = shader.Namespace != null ? "    " : string.Empty;
        sb.Append(indent).Append("partial class ").AppendLine(shader.ClassName);
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).AppendLine("    /// <summary>The SDSL shader class name.</summary>");
        sb.Append(indent).Append("    public const string ShaderName = \"").Append(shader.ShaderName).AppendLine("\";");
        sb.AppendLine();
        sb.Append(indent).AppendLine("    /// <summary>The SDSL this class was translated to: what the effect compiler receives.</summary>");
        sb.Append(indent).Append("    public const string SdslSource = ").Append(Quote(shader.Sdsl ?? string.Empty)).AppendLine(";");
        sb.Append(indent).AppendLine("}");
        if (shader.Namespace != null)
            sb.AppendLine("}");
        return sb.ToString();
    }

    public static string EmitRegistration(IEnumerable<TranslatedShader> shaders)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Generated by Csl.Generators: hands the SDSL of every C# shader of this assembly to the effect compiler.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace Csl.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    internal static class CslShaderSources");
        sb.AppendLine("    {");
        sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("        internal static void Register()");
        sb.AppendLine("        {");
        foreach (var shader in shaders)
        {
            var type = shader.Namespace == null ? shader.ClassName : shader.Namespace + "." + shader.ClassName;
            sb.Append("            global::Csl.ShaderSourceRegistry.Add(global::").Append(type).Append(".ShaderName, global::").Append(type)
              .Append(".SdslSource, ").Append(Quote(shader.Path)).AppendLine(");");
        }
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string Quote(string text)
    {
        var sb = new StringBuilder("\"");
        foreach (var c in text)
        {
            switch (c)
            {
                case '\\': sb.Append("\\\\"); break;
                case '"': sb.Append("\\\""); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': break;
                case '\t': sb.Append("\\t"); break;
                default:
                    if (c < 32) sb.Append("\\u").Append(((int)c).ToString("x4"));
                    else sb.Append(c);
                    break;
            }
        }
        return sb.Append('"').ToString();
    }
}
