using System.Collections.Generic;
using System.Text;
using Csl.Generators.Sdsl;

namespace Csl.Generators;

/// <summary>Writes the C# of one wrapper class.</summary>
public static class WrapperEmitter
{
    public static string Emit(WrapperModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Generated by Csl.Generators from " + model.ShaderName + ".sdsl. Do not edit; edit the shader.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS1591");
        sb.AppendLine("using System;");
        sb.AppendLine("using Stride.Core;");
        sb.AppendLine("using Stride.Core.Mathematics;");
        sb.AppendLine("using Stride.Graphics;");
        sb.AppendLine("using Stride.Rendering;");
        sb.AppendLine("using Csl;");
        sb.AppendLine("using Buffer = Stride.Graphics.Buffer;");
        sb.AppendLine();

        string indent = string.Empty;
        if (model.Namespace != null)
        {
            sb.Append("namespace ").AppendLine(model.Namespace);
            sb.AppendLine("{");
            indent = "    ";
        }

        EmitDoc(sb, model.Doc, indent);
        var baseType = model.BaseClassName == null
            ? "global::Csl.ComputeEffect"
            : "global::" + (model.BaseClassNamespace == null ? model.BaseClassName : model.BaseClassNamespace + "." + model.BaseClassName);
        sb.Append(indent).Append("public ").Append(model.IsCompute ? string.Empty : "abstract ").Append("partial class ")
          .Append(model.ClassName).Append(" : ").AppendLine(baseType);
        sb.Append(indent).AppendLine("{");
        var inner = indent + "    ";

        if (model.IsCompute)
        {
            sb.Append(inner).AppendLine("/// <summary>The SDSL shader this class dispatches.</summary>");
            sb.Append(inner).Append("public ").Append(model.BaseIsCompute ? "new " : string.Empty)
              .Append("const string ShaderName = \"").Append(model.ShaderName).AppendLine("\";");
            sb.AppendLine();
            sb.Append(inner).AppendLine("/// <summary>Creates the shader with its thread group size; ThreadGroupCounts come from Dispatch.</summary>");
            sb.Append(inner).Append("public ").Append(model.ClassName)
              .AppendLine("(IServiceRegistry services, Int3 threadNumbers) : base(services, ShaderName, threadNumbers) { }");
            sb.Append(inner).AppendLine("/// <summary>Creates the shader with the same thread count on every axis.</summary>");
            sb.Append(inner).Append("public ").Append(model.ClassName)
              .AppendLine("(IServiceRegistry services, int threads) : this(services, new Int3(threads)) { }");
            if (model.DefaultThreads is { } threads)
            {
                sb.Append(inner).Append("/// <summary>The thread group size the shader declares: [NumThreads(")
                  .Append(threads.X).Append(", ").Append(threads.Y).Append(", ").Append(threads.Z).AppendLine(")].</summary>");
                sb.Append(inner).Append("public static ").Append(model.BaseIsCompute ? "new " : string.Empty).Append("readonly Int3 DefaultThreadNumbers = new Int3(")
                  .Append(threads.X).Append(", ").Append(threads.Y).Append(", ").Append(threads.Z).AppendLine(");");
                sb.Append(inner).AppendLine("/// <summary>Creates the shader with the thread group size it declares.</summary>");
                sb.Append(inner).Append("public ").Append(model.ClassName)
                  .AppendLine("(IServiceRegistry services) : this(services, DefaultThreadNumbers) { }");
            }
            sb.AppendLine();
        }
        sb.Append(inner).AppendLine("/// <summary>For a shader that inherits this one.</summary>");
        sb.Append(inner).Append("protected ").Append(model.ClassName)
          .AppendLine("(IServiceRegistry services, string shaderName, Int3 threadNumbers) : base(services, shaderName, threadNumbers) { }");

        foreach (var property in model.Properties)
        {
            sb.AppendLine();
            var field = FieldName(property.Name);
            var key = "global::" + property.KeysType + "." + property.Name;
            if (property.Slot != null)
            {
                sb.Append(inner).Append("private ").Append(property.CSharpType).Append("? ").Append(field).AppendLine(";");
                EmitDoc(sb, property.Doc, inner, DescribeSlot(property.Slot));
                sb.Append(inner).Append("public ").Append(property.CSharpType).Append("? ").Append(property.Name)
                  .Append(" { get => ").Append(field).Append("; set => ");
                switch (property.Slot.Kind)
                {
                    case SdslResourceKind.Texture:
                        sb.Append("SetTexture(ref ").Append(field).Append(", ").Append(key).Append(", value, Slots.").Append(property.Name).AppendLine("); }");
                        break;
                    case SdslResourceKind.Sampler:
                        sb.Append("SetSampler(ref ").Append(field).Append(", ").Append(key).AppendLine(", value); }");
                        break;
                    default:
                        sb.Append("SetBuffer(ref ").Append(field).Append(", ").Append(key).Append(", value, Slots.").Append(property.Name).AppendLine("); }");
                        break;
                }
            }
            else
            {
                sb.Append(inner).Append("private ").Append(property.CSharpType).Append(' ').Append(field).AppendLine(";");
                EmitDoc(sb, property.Doc, inner);
                sb.Append(inner).Append("public ").Append(property.CSharpType).Append(' ').Append(property.Name)
                  .Append(" { get => ").Append(field).Append("; set { ").Append(field).Append(" = value; Parameters.Set(")
                  .Append(key).AppendLine(", value); } }");
            }
        }

        // Slots: how the shader uses each resource, for allocation helpers and the analyzer.
        bool hasSlots = model.Properties.Exists(p => p.Slot != null);
        if (hasSlots)
        {
            sb.AppendLine();
            sb.Append(inner).AppendLine("/// <summary>Each resource of the shader with the access it makes: what to allocate for it.</summary>");
            sb.Append(inner).Append("public ").Append(model.BaseHasSlots ? "new " : string.Empty).AppendLine("static class Slots");
            sb.Append(inner).AppendLine("{");
            foreach (var property in model.Properties)
            {
                var slot = property.Slot;
                if (slot == null)
                    continue;
                sb.Append(inner).Append("    [global::Csl.Slot(global::Csl.ResourceAccess.").Append(slot.Access)
                  .Append(", global::Csl.ResourceKind.").Append(slot.Kind).AppendLine(")]");
                sb.Append(inner).Append("    public static readonly global::Csl.ResourceSlot ").Append(property.Name)
                  .Append(" = new global::Csl.ResourceSlot(\"").Append(slot.ShaderName).Append("\", \"").Append(property.Name)
                  .Append("\", global::Csl.ResourceKind.").Append(slot.Kind)
                  .Append(", global::Csl.ResourceAccess.").Append(slot.Access)
                  .Append(", \"").Append(slot.HlslType).Append("\", ")
                  .Append(slot.ElementType == null ? "null" : "\"" + slot.ElementType + "\"").AppendLine(");");
            }
            sb.Append(inner).AppendLine("}");
        }

        sb.Append(indent).AppendLine("}");
        if (model.Namespace != null)
            sb.AppendLine("}");
        return sb.ToString();
    }

    private static string DescribeSlot(SlotModel slot)
    {
        var access = slot.Access switch
        {
            SdslAccess.ReadWrite => "read and written",
            SdslAccess.Write => "written",
            SdslAccess.Read => "read",
            _ => "declared but unused",
        };
        return $"{slot.HlslType}, {access} by the shader.";
    }

    private static string FieldName(string name) => "_" + char.ToLowerInvariant(name[0]) + name.Substring(1);

    private static void EmitDoc(StringBuilder sb, List<string> doc, string indent, string? trailer = null)
    {
        bool hasTags = false;
        foreach (var line in doc)
        {
            if (line.Contains("<summary>") || line.Contains("<remarks>") || line.Contains("<para>"))
                hasTags = true;
        }
        if (hasTags)
        {
            foreach (var line in doc)
                sb.Append(indent).Append(line.Length == 0 ? "///" : "/// ").AppendLine(line);
            return;
        }
        sb.Append(indent).AppendLine("/// <summary>");
        foreach (var line in doc)
            sb.Append(indent).Append(line.Length == 0 ? "///" : "/// ").AppendLine(Escape(line));
        if (trailer != null)
            sb.Append(indent).Append("/// ").AppendLine(Escape(trailer));
        sb.Append(indent).AppendLine("/// </summary>");
    }

    private static string Escape(string text) => text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
}
