using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Csl.Generators.Sdsl;

/// <summary>
/// A C# stub of an existing shader (the engine's ComputeShaderBase, say): a [Shader(External = true)]
/// class with the same members, so a shader written in C# can inherit it, read its streams and
/// override its methods. Bodies are not translated; the shader itself stays where it is.
/// </summary>
public static class SdslStubEmitter
{
    public static string Emit(SdslShader shader, string ns, string sourceDescription)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.Append("// Stub of ").Append(sourceDescription).AppendLine(", written by Csl.Stubs. Do not edit; run the tool again.");
        sb.AppendLine("// Nothing is generated from this class: it describes a shader that exists elsewhere, so C# shaders");
        sb.AppendLine("// can inherit it. Method bodies are placeholders.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS0649, CS8618, CS1591");
        sb.AppendLine("using Csl.Hlsl;");
        sb.AppendLine();
        sb.Append("namespace ").Append(ns).AppendLine(";");
        sb.AppendLine();
        foreach (var line in shader.Doc)
            sb.Append("/// ").AppendLine(line);
        sb.AppendLine("[Shader(External = true)]");
        var bases = shader.Bases.Count > 0 ? " : " + shader.Bases[0] : string.Empty;
        if (shader.Bases.Count > 1)
            sb.Append("[Mixin(").Append(string.Join(", ", shader.Bases.Skip(1).Select(b => "typeof(" + b + ")"))).AppendLine(")]");
        sb.Append("public abstract partial class ").Append(shader.Name).AppendLine(bases);
        sb.AppendLine("{");

        foreach (var member in shader.Members)
        {
            if (member.IsConst || member.IsStatic)
                continue;
            var type = CSharpType(member);
            if (type == null)
                continue;
            foreach (var line in member.Doc)
                sb.Append("    /// ").AppendLine(line);
            var attributes = new List<string>();
            if (member.IsStage) attributes.Add("Stage");
            if (member.IsStream) attributes.Add(member.Semantic == null ? "Stream" : "Stream(\"" + member.Semantic + "\")");
            if (member.IsCompose) attributes.Add("Compose");
            if (member.IsGroupShared) attributes.Add("GroupShared");
            foreach (var (name, argument) in member.Attributes)
            {
                if (name == "Link" && argument != null) attributes.Add("Link(\"" + argument + "\")");
                if (name == "Color") attributes.Add("Color");
            }
            sb.Append("    ");
            if (attributes.Count > 0)
                sb.Append('[').Append(string.Join(", ", attributes)).Append("] ");
            sb.Append("public ").Append(type).Append(' ').Append(member.Name).AppendLine(";");
        }

        foreach (var method in shader.Methods)
        {
            var signature = method.Signature;
            if (signature == null)
                continue;
            var returnType = CSharpType(signature.ReturnType, signature.ReturnGeneric);
            if (returnType == null)
                continue;
            var parameters = new List<string>();
            bool ok = true;
            foreach (var parameter in signature.Parameters)
            {
                var parameterType = CSharpType(parameter.Type, parameter.Generic);
                if (parameterType == null)
                {
                    ok = false;
                    break;
                }
                parameters.Add((parameter.Modifier == "inout" ? "ref " : parameter.Modifier == "out" ? "out " : string.Empty) + parameterType + " " + parameter.Name);
            }
            if (!ok)
                continue;
            sb.AppendLine();
            foreach (var line in method.Doc)
                sb.Append("    /// ").AppendLine(line);
            sb.Append("    public ").Append(method.IsAbstract ? "abstract " : "virtual ").Append(returnType).Append(' ').Append(method.Name)
              .Append('(').Append(string.Join(", ", parameters)).Append(')');
            if (method.IsAbstract)
                sb.AppendLine(";");
            else if (returnType == "void")
                sb.AppendLine(" { }");
            else
            {
                var outs = signature.Parameters.Where(p => p.Modifier == "out").Select(p => p.Name + " = default; ");
                sb.Append(" { ").Append(string.Concat(outs)).AppendLine("return default; }");
            }
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string? CSharpType(SdslMember member) => member.IsArray ? null : CSharpType(member.Type, member.GenericArgument);

    /// <summary>The Csl.Hlsl name of an HLSL type: the same, for everything the library declares.</summary>
    private static string? CSharpType(string type, string? generic)
    {
        switch (type)
        {
            case "void": case "bool": case "int": case "uint": case "float": case "double": return type;
            case "half": return "float";
        }
        if (SdslTypes.IsResource(type))
            return generic == null ? type : type + "<" + CSharpType(generic, null) + ">";
        if (System.Text.RegularExpressions.Regex.IsMatch(type, @"^(float|int|uint|bool)([2-4])(x[2-4])?$"))
            return type;
        return null;
    }
}
